'use strict';
const DE_STOP=new Set('aber alle allem allen aller alles als also am an andere anderen anderer anderes auch auf aus bei bin bis bist da damit dann das dass dein deine dem den denn der des die dies diese doch dort du durch ein eine einem einen einer eines er es etwas für gegen gewesen hat hatte haben hier hin hinter ich im in ist ja jede jedem jeden jeder jedes jener jenes jetzt kann kein keine mit muss nach nicht nichts noch nun nur ob oder ohne sehr sein seine selbst sich sie sind so solche um und uns unser unter vom von vor war waren warst was weg weil weiter welche welcher welches wenn werde werden wie wieder will wir wird wo zu zum zur über'.split(' '));
const EN_STOP=new Set('a about after again all am an and any are as at be because been before being below between both but by can did do does doing down during each few for from further had has have having he her here hers herself him himself his how i if in into is it its itself just me more most my myself no nor not of off on once only or other our ours ourselves out over own same she should so some such than that the their theirs them themselves then there these they this those through to too under until up very was we were what when where which while who whom why will with you your yours yourself yourselves'.split(' '));
const WEEK=['So','Mo','Di','Mi','Do','Fr','Sa'];
const EMOJI_RE=/\p{Extended_Pictographic}/u;
const URL_RE=/https?:\/\/[^\s<>]+|www\.[^\s<>]+/giu;
let rawText='';let parsed=null;
self.onmessage=async e=>{const m=e.data||{};try{if(m.type==='parse'){rawText=m.file?await m.file.text():(m.text||'');parsed=parseChat(rawText,m.dateOrder);postMessage({type:'parsed',data:summary(parsed)});}else if(m.type==='reparse'){parsed=parseChat(rawText,m.dateOrder);postMessage({type:'parsed',data:summary(parsed)});}else if(m.type==='metrics'){postMessage({type:'metrics',requestId:m.requestId,data:metrics(parsed,m.options||{})});}else if(m.type==='clear'){rawText='';parsed=null;postMessage({type:'cleared'});}}catch(err){postMessage({type:'error',requestId:m.requestId,message:err&&err.message?err.message:String(err)})}};
function stripMarks(s){return s.replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').trimEnd()}
function detectHeader(line){line=stripMarks(line);let m=line.match(/^\[(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4}),?\s+(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\s*([AP]M))?\]\s*(.*)$/i);if(m)return{style:'bracket',a:+m[1],b:+m[2],y:+m[3],h:+m[4],min:+m[5],sec:+(m[6]||0),ampm:m[7],rest:m[8],sample:line};m=line.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4}),?\s+(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\s*([AP]M))?\s+-\s+(.*)$/i);if(m)return{style:'dash',a:+m[1],b:+m[2],y:+m[3],h:+m[4],min:+m[5],sec:+(m[6]||0),ampm:m[7],rest:m[8],sample:line};return null}
function determineOrder(headers,forced){if(forced)return{order:forced,ambiguous:false};let d=0,m=0;for(const h of headers){if(h.a>12&&h.b<=12)d++;if(h.b>12&&h.a<=12)m++;}if(d&&!m)return{order:'DMY',ambiguous:false};if(m&&!d)return{order:'MDY',ambiguous:false};return{order:'DMY',ambiguous:true}}
function makeDate(h,order){let day=order==='DMY'?h.a:h.b,month=order==='DMY'?h.b:h.a,year=h.y<100?2000+h.y:h.y,hour=h.h;if(h.ampm){if(/pm/i.test(h.ampm)&&hour<12)hour+=12;if(/am/i.test(h.ampm)&&hour===12)hour=0}if(month<1||month>12||day<1||day>31||hour>23||h.min>59||h.sec>59)return null;const d=new Date(year,month-1,day,hour,h.min,h.sec);if(d.getFullYear()!==year||d.getMonth()!==month-1||d.getDate()!==day)return null;return d}
function splitSender(rest){const idx=rest.indexOf(': ');if(idx<1)return{sender:null,text:rest,system:true};const sender=rest.slice(0,idx).trim();if(!sender||sender.length>120)return{sender:null,text:rest,system:true};return{sender,text:rest.slice(idx+2),system:false}}
function attachmentType(text){const t=stripMarks(text).toLowerCase();if(/audio (weggelassen|omitted)|<anhang:.*-audio-|<attached:.*-audio-|\.opus>?$/.test(t))return'audio';if(/bild (weggelassen)|image omitted|foto (weggelassen)|photo omitted|<anhang:.*\.(jpe?g|png|heic|webp)>|<attached:.*\.(jpe?g|png|heic|webp)>/.test(t))return'image';if(/video (weggelassen|omitted)|<anhang:.*\.(mp4|mov|m4v)>|<attached:.*\.(mp4|mov|m4v)>/.test(t))return'video';if(/sticker (weggelassen|omitted)|<anhang:.*sticker|<attached:.*sticker/.test(t))return'sticker';if(/gif (weggelassen|omitted)|<anhang:.*\.gif>|<attached:.*\.gif>/.test(t))return'gif';if(/dokument (weggelassen)|document omitted|<anhang:|<attached:/.test(t))return'document';if(/medien (weggelassen)|media omitted/.test(t))return'media';return null}
function parseChat(text,forcedOrder){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/);const candidates=[];for(const line of lines){const h=detectHeader(line);if(h)candidates.push(h)}if(!candidates.length)throw new Error('Keine unterstützten WhatsApp-Nachrichten erkannt. Bitte eine unveränderte WhatsApp-.txt-Datei auswählen.');const ord=determineOrder(candidates,forcedOrder);const messages=[];let current=null,unclassified=0;for(const raw of lines){const h=detectHeader(raw);if(h){if(current)messages.push(current);const date=makeDate(h,ord.order);const s=splitSender(h.rest);if(!date){current=null;unclassified++;continue}current={date,dateMs:date.getTime(),sender:s.sender,text:stripMarks(s.text),system:s.system,attachment:attachmentType(s.text)};}else if(current){current.text+='\n'+stripMarks(raw)}else if(raw.trim())unclassified++}if(current)messages.push(current);if(!messages.length)throw new Error('Die Datei enthält keine auswertbaren Nachrichten.');messages.sort((a,b)=>a.dateMs-b.dateMs);const participants=[...new Set(messages.filter(x=>!x.system&&x.sender).map(x=>x.sender))];return{messages,participants,unclassified,order:ord.order,ambiguous:ord.ambiguous&&!forcedOrder,ambiguousExample:candidates.find(h=>h.a<=12&&h.b<=12)?.sample||'',style:candidates[0].style,hasSeconds:candidates.some(h=>h.sec),twelveHour:candidates.some(h=>h.ampm),totalLines:lines.length}}
function summary(p){const user=p.messages.filter(m=>!m.system&&m.sender);return{participants:p.participants,totalMessages:user.length,systemRecords:p.messages.length-user.length,unclassified:p.unclassified,order:p.order,ambiguous:p.ambiguous,ambiguousExample:p.ambiguousExample,style:p.style,hasSeconds:p.hasSeconds,twelveHour:p.twelveHour,first:user[0]?.dateMs,last:user[user.length-1]?.dateMs}}
function dayKey(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monthKey(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function weekKey(d){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return dayKey(x)}
function tokenize(text){return(text.toLocaleLowerCase().match(/[\p{L}\p{N}][\p{L}\p{N}'’_-]*/gu)||[]).filter(w=>w.length>1)}
function emojis(text){if(Intl.Segmenter){const seg=new Intl.Segmenter(undefined,{granularity:'grapheme'});return[...seg.segment(text)].map(x=>x.segment).filter(x=>EMOJI_RE.test(x))}return Array.from(text).filter(x=>EMOJI_RE.test(x))}
function inc(map,k,n=1){map.set(k,(map.get(k)||0)+n)}
function top(map,n=20){return[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n).map(([label,value])=>({label,value}))}
function quantile(a,q){if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*q,lo=Math.floor(i),hi=Math.ceil(i);return s[lo]+(s[hi]-s[lo])*(i-lo)}
function fmtDomain(url){try{const u=new URL(/^www\./i.test(url)?'https://'+url:url);return u.hostname.replace(/^www\./,'').toLowerCase()}catch{return null}}
function metrics(p,o){if(!p)return null;const start=o.start?new Date(o.start+'T00:00:00').getTime():-Infinity,end=o.end?new Date(o.end+'T23:59:59.999').getTime():Infinity,gapMs=(o.gapHours||6)*3600000,stop=o.stopwords==='en'?EN_STOP:o.stopwords==='none'?new Set():DE_STOP;const msgs=p.messages.filter(m=>!m.system&&m.sender&&m.dateMs>=start&&m.dateMs<=end);const byPerson=new Map(),days=new Map(),months=new Map(),weeks=new Map(),hours=Array(24).fill(0),weekdays=Array(7).fill(0),matrix=Array.from({length:7},()=>Array(24).fill(0)),words=new Map(),emoji=new Map(),phrases=new Map(),domains=new Map(),attachments=new Map();let questions=0,links=0,chars=0,wordCount=0;const lengthLabels=['1–10','11–25','26–50','51–100','101–250','251+'];const lengthIndex=n=>n<=10?0:n<=25?1:n<=50?2:n<=100?3:n<=250?4:5;const lengthCounts=Array(6).fill(0);const personDetail=new Map(p.participants.map(x=>[x,{messages:0,words:0,chars:0,activeDays:new Set(),emoji:new Map(),wordMap:new Map(),lengthCounts:Array(6).fill(0)}]));for(const m of msgs){inc(byPerson,m.sender);inc(days,dayKey(m.date));inc(months,monthKey(m.date));inc(weeks,weekKey(m.date));hours[m.date.getHours()]++;weekdays[m.date.getDay()]++;matrix[m.date.getDay()][m.date.getHours()]++;const pd=personDetail.get(m.sender)||{messages:0,words:0,chars:0,activeDays:new Set(),emoji:new Map(),wordMap:new Map(),lengthCounts:Array(6).fill(0)};pd.messages++;pd.activeDays.add(dayKey(m.date));personDetail.set(m.sender,pd);if(m.attachment){inc(attachments,m.attachment);continue}chars+=m.text.length;lengthCounts[lengthIndex(m.text.length)]++;pd.lengthCounts[lengthIndex(m.text.length)]++;const toks=tokenize(m.text);wordCount+=toks.length;pd.words+=toks.length;pd.chars+=m.text.length;const filtered=toks.filter(w=>!stop.has(w)&&!/^[0-9]+$/.test(w));for(const w of filtered){inc(words,w);inc(pd.wordMap,w)}for(let i=0;i<filtered.length-1;i++)inc(phrases,filtered.slice(i,i+2).join(' '));for(let i=0;i<filtered.length-2;i++)inc(phrases,filtered.slice(i,i+3).join(' '));for(const e of emojis(m.text)){inc(emoji,e);inc(pd.emoji,e)}const urls=m.text.match(URL_RE)||[];links+=urls.length;for(const u of urls){const d=fmtDomain(u);if(d)inc(domains,d)}if(m.text.includes('?'))questions++}
 const sessions=[];const starters=new Map(),switches=[],switchDir=new Map();let sess=null,prev=null;for(const m of msgs){if(!prev||m.dateMs-prev.dateMs>=gapMs){if(sess)sessions.push(sess);sess={start:m.dateMs,end:m.dateMs,count:1,starter:m.sender};inc(starters,m.sender)}else{sess.end=m.dateMs;sess.count++}if(prev&&m.sender!==prev.sender&&m.dateMs-prev.dateMs<gapMs){const d=m.dateMs-prev.dateMs;switches.push(d);const key=prev.sender+' → '+m.sender;if(!switchDir.has(key))switchDir.set(key,[]);switchDir.get(key).push(d)}prev=m}if(sess)sessions.push(sess);
 const sortedDays=[...days.entries()].sort((a,b)=>a[0].localeCompare(b[0]));let longestStreak=0,cur=0,prevDay=null,longestPause=0,pauseStart=null,pauseEnd=null;for(const [k] of sortedDays){const d=new Date(k+'T12:00:00');if(prevDay&&Math.round((d-prevDay)/86400000)===1)cur++;else cur=1;if(cur>longestStreak)longestStreak=cur;prevDay=d}for(let i=1;i<msgs.length;i++){const gap=msgs[i].dateMs-msgs[i-1].dateMs;if(gap>longestPause){longestPause=gap;pauseStart=msgs[i-1].dateMs;pauseEnd=msgs[i].dateMs}}
 const activeDay=top(days,1)[0]||null,activeMonth=top(months,1)[0]||null,activeHour=hours.indexOf(Math.max(...hours)),activeWeekday=weekdays.indexOf(Math.max(...weekdays));const durationSessions=sessions.map(s=>s.end-s.start);const switchDirections=[...switchDir.entries()].map(([label,a])=>({label,median:quantile(a,.5),count:a.length})).sort((a,b)=>b.count-a.count);return{count:msgs.length,wordCount,chars,avgWords:msgs.length?wordCount/msgs.length:0,avgChars:msgs.length?chars/msgs.length:0,activeDays:days.size,byPerson:top(byPerson,999),days:[...days.entries()].map(([date,value])=>({date,value})),months:[...months.entries()].sort().map(([date,value])=>({date,value})),weeks:[...weeks.entries()].sort().map(([date,value])=>({date,value})),hours,weekdays,matrix,topWords:top(words,20),topEmoji:top(emoji,20),topPhrases:top(new Map([...phrases].filter(([,v])=>v>=2)),15),domains:top(domains,15),attachments:top(attachments,20),questions,links,activeDay,activeMonth,activeHour,activeWeekday,longestStreak,longestPause,pauseStart,pauseEnd,sessions:{count:sessions.length,medianMessages:quantile(sessions.map(s=>s.count),.5),medianDuration:quantile(durationSessions,.5),longestDuration:Math.max(0,...durationSessions),starters:top(starters,999)},switches:{count:switches.length,median:quantile(switches,.5),p75:quantile(switches,.75),p90:quantile(switches,.9),directions:switchDirections},lengthBuckets:lengthLabels.map((label,i)=>({label,value:lengthCounts[i]})),participantBreakdowns:[...personDetail.entries()].map(([name,d])=>({name,topWords:top(d.wordMap,20),topEmoji:top(d.emoji,20),lengthBuckets:lengthLabels.map((label,i)=>({label,value:d.lengthCounts[i]}))})),participants:[...personDetail.entries()].map(([name,d])=>({name,messages:d.messages,words:d.words,chars:d.chars,activeDays:d.activeDays.size,topEmoji:top(d.emoji,3)})).sort((a,b)=>b.messages-a.messages),first:msgs[0]?.dateMs,last:msgs[msgs.length-1]?.dateMs,rangeStart:Number.isFinite(start)?start:msgs[0]?.dateMs,rangeEnd:Number.isFinite(end)?end:msgs[msgs.length-1]?.dateMs,gapHours:o.gapHours||6,stopwords:o.stopwords||'de'} }
