'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={worker:null,summary:null,metrics:null,fileName:'',dateOrder:null,range:{start:null,end:null,label:'Gesamter Zeitraum'},gapHours:6,stopwords:'de',granularity:'month',request:0};
const views=['import-view','loading-view','review-view','dashboard'];
function show(id){views.forEach(v=>$('#'+v).hidden=v!==id);scrollTo(0,0)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nf(n,d=0){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:d}).format(n||0)}
function date(ms,opt={day:'2-digit',month:'short',year:'numeric'}){return ms?new Intl.DateTimeFormat('de-DE',opt).format(new Date(ms)):'–'}
function dur(ms){if(!ms)return'0 Min.';const s=Math.round(ms/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;if(d)return`${d} T ${h} Std.`;if(h)return`${h} Std. ${m} Min.`;if(m)return`${m} Min. ${sec} Sek.`;return`${sec} Sek.`}
function localISO(ms){const d=new Date(ms),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function initWorker(){state.worker?.terminate();state.worker=new Worker('./analyzer-worker.js');state.worker.onmessage=onWorker}
function onWorker(e){const m=e.data;if(m.type==='error'){showError(m.message);return}if(m.type==='parsed'){state.summary=m.data;renderReview();show('review-view');return}if(m.type==='metrics'&&m.requestId===state.request){state.metrics=m.data;renderDashboard();}}
function showError(msg){show('import-view');$('#import-error').textContent=msg;$('#import-error').hidden=false}
async function loadFile(file){if(!file)return;if(!/\.txt$/i.test(file.name)){showError('Bitte eine WhatsApp-.txt-Datei auswählen. ZIP-Archive werden in V1 nicht unterstützt.');return}$('#import-error').hidden=true;state.fileName=file.name;show('loading-view');$('#loading-status').textContent='Datei wird nur in diesem Browser gelesen.';try{const text=await file.text();initWorker();state.worker.postMessage({type:'parse',text});}catch(e){showError('Die Datei konnte nicht gelesen werden: '+e.message)}}
function renderReview(){const s=state.summary;$('#review-grid').innerHTML=[['Nachrichten',nf(s.totalMessages)],['Teilnehmer',nf(s.participants.length)],['Zeitraum',`${date(s.first)} – ${date(s.last)}`],['Format',`${s.order==='DMY'?'Tag/Monat':'Monat/Tag'} · ${s.twelveHour?'12 h':'24 h'}${s.hasSeconds?' · Sekunden':''}`]].map(([a,b])=>`<div class="review-item"><span>${a}</span><strong>${esc(b)}</strong></div>`).join('');$('#date-warning').hidden=!s.ambiguous;$('#ambiguous-example').textContent=s.ambiguousExample;$$('[data-date-order]').forEach(b=>b.classList.toggle('selected',b.dataset.dateOrder===s.order));$('#diagnostics').innerHTML=`<strong>Importdiagnostik</strong><p class="muted">${nf(s.systemRecords)} Systemeinträge · ${nf(s.unclassified)} nicht klassifizierte Zeilen · ${s.style==='bracket'?'Klammerformat':'Bindestrichformat'}</p>`;$('#analyze-button').disabled=s.ambiguous}
function requestMetrics(){if(!state.summary)return;state.request++;state.worker.postMessage({type:'metrics',requestId:state.request,options:{...state.range,gapHours:state.gapHours,stopwords:state.stopwords}})}
function openDashboard(){const s=state.summary;state.range={start:null,end:null,label:'Gesamter Zeitraum'};$('#range-start').min=localISO(s.first);$('#range-start').max=localISO(s.last);$('#range-end').min=localISO(s.first);$('#range-end').max=localISO(s.last);buildPresets();show('dashboard');requestMetrics()}
function renderDashboard(){const m=state.metrics,s=state.summary;if(!m)return;$('#chat-title').textContent=s.participants.length===2?s.participants.join(' × '):`${s.participants.length} Personen`;$('#chat-subtitle').textContent=`${nf(s.totalMessages)} Nachrichten im Import · ${date(s.first)} – ${date(s.last)}`;$('#range-label').textContent=state.range.label;$('#range-dates').textContent=m.first?`${date(m.first)} – ${date(m.last)}`:'Keine Nachrichten im Zeitraum';$('#report-range').textContent=$('#range-dates').textContent;renderKpis(m);renderShare(m);renderActivity(m);renderTiming(m);renderConversation(m);renderLanguage(m);renderParticipants(m)}
function kpi(value,label,sub=''){return`<div class="kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function renderKpis(m){const topE=m.topEmoji[0]?.label||'–';$('#kpi-grid').innerHTML=kpi(nf(m.count),'Nachrichten')+kpi(nf(m.wordCount),'Wörter')+kpi(nf(m.avgWords,1),'Wörter / Nachricht')+kpi(nf(m.activeDays),'Aktive Tage')+kpi(m.count?`${String(m.activeHour).padStart(2,'0')}:00`:'–','Aktivste Stunde')+kpi(topE,'Top Emoji')}
function shareRows(data,total){return data.map(x=>`<div class="share-row"><span title="${esc(x.label)}">${esc(x.label)}</span><div class="track"><div class="fill" style="width:${total?x.value/total*100:0}%"></div></div><strong>${total?nf(x.value/total*100,1):0}%</strong></div>`).join('')||'<p class="muted">Keine Daten.</p>'}
function renderShare(m){$('#share-chart').innerHTML=shareRows(m.byPerson,m.count)}
function series(m){return state.granularity==='day'?m.days:state.granularity==='week'?m.weeks:m.months}
function renderLine(data){const svg=$('#activity-chart'),w=900,h=240,p=28,max=Math.max(1,...data.map(x=>x.value));if(!data.length){svg.innerHTML='';return}const pts=data.map((x,i)=>[p+(w-2*p)*(data.length===1?.5:i/(data.length-1)),h-p-(h-2*p)*x.value/max]);const line=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' '),area=`M${pts[0][0]},${h-p} `+line+` L${pts.at(-1)[0]},${h-p} Z`;let labels='';const steps=Math.min(5,data.length);for(let i=0;i<steps;i++){const idx=Math.round(i*(data.length-1)/Math.max(1,steps-1));labels+=`<text class="chart-label" x="${pts[idx][0]}" y="${h-5}" text-anchor="middle">${esc(data[idx].date.slice(0,7))}</text>`}svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=`<line class="chart-grid" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><line class="chart-grid" x1="${p}" y1="${p}" x2="${w-p}" y2="${p}"/><path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/>${labels}`}
function renderCalendar(m){const map=new Map(m.days.map(x=>[x.date,x.value])),max=Math.max(1,...m.days.map(x=>x.value));if(!m.days.length){$('#calendar-heatmap').innerHTML='<p class="muted">Keine Aktivität.</p>';return}const start=new Date(m.rangeStart),end=new Date(m.rangeEnd),parts=[];let cur=new Date(start.getFullYear(),start.getMonth(),1);while(cur<=end&&parts.length<36){const y=cur.getFullYear(),mo=cur.getMonth(),first=new Date(y,mo,1),last=new Date(y,mo+1,0),cells=[];['Mo','Di','Mi','Do','Fr','Sa','So'].forEach(x=>cells.push(`<span class="cal-head">${x}</span>`));for(let i=0;i<(first.getDay()+6)%7;i++)cells.push('<span class="cal-day empty"></span>');for(let d=1;d<=last.getDate();d++){const dt=new Date(y,mo,d),key=localISO(dt),v=map.get(key)||0,level=v?Math.min(4,Math.ceil(v/max*4)):0;cells.push(`<span class="cal-day" data-level="${level}" title="${date(dt.getTime())}: ${v} Nachrichten">${d}</span>`)}parts.push(`<div class="calendar-month"><h4>${new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(first)}</h4><div class="calendar-grid">${cells.join('')}</div></div>`);cur=new Date(y,mo+1,1)}$('#calendar-heatmap').innerHTML=parts.join('')}
function renderActivity(m){renderLine(series(m));renderCalendar(m);const active=m.activeDay?`${date(new Date(m.activeDay.label+'T12:00').getTime())} · ${nf(m.activeDay.value)}`:'–';$('#activity-records').innerHTML=`<div class="record"><span>Aktivster Tag</span><strong>${esc(active)}</strong></div><div class="record"><span>Längste tägliche Serie</span><strong>${nf(m.longestStreak)} Tage</strong></div><div class="record"><span>Längste Pause</span><strong>${dur(m.longestPause)}</strong></div>`}
function renderTiming(m){const max=Math.max(1,...m.hours);$('#hour-chart').innerHTML=m.hours.map((v,i)=>`<div class="bar-col" title="${i}:00 · ${v}"><div class="bar" style="height:${v/max*90}%"></div><small>${i%3===0?String(i).padStart(2,'0'):''}</small></div>`).join('');const names=['So','Mo','Di','Mi','Do','Fr','Sa'],wm=Math.max(1,...m.weekdays);$('#weekday-chart').innerHTML=[1,2,3,4,5,6,0].map(i=>`<div class="hbar"><span>${names[i]}</span><div class="track"><div class="fill" style="width:${m.weekdays[i]/wm*100}%"></div></div><strong>${nf(m.weekdays[i])}</strong></div>`).join('');const mm=Math.max(1,...m.matrix.flat()),order=[1,2,3,4,5,6,0];let html='<div class="matrix"><span></span>'+Array.from({length:24},(_,h)=>`<span class="matrix-cell head">${h%3===0?h:''}</span>`).join('');for(const d of order){html+=`<span class="matrix-cell head">${names[d]}</span>`+m.matrix[d].map((v,h)=>`<span class="matrix-cell ${v?'level'+Math.min(4,Math.ceil(v/mm*4)):''}" title="${names[d]} ${h}:00 · ${v}"></span>`).join('')}html+='</div>';$('#hour-weekday').innerHTML=html}
function renderConversation(m){$('#gap-button').textContent=state.gapHours+' Stunden';$('#conversation-kpis').innerHTML=kpi(nf(m.sessions.count),'Aktive Phasen')+kpi(nf(m.sessions.medianMessages,1),'Median Nachrichten / Phase')+kpi(dur(m.sessions.medianDuration),'Median Phasendauer')+kpi(dur(m.switches.median),'Median Sprecherwechsel');$('#starter-chart').innerHTML=shareRows(m.sessions.starters,m.sessions.count)}
function rankRows(data){const max=Math.max(1,...data.map(x=>x.value));return data.map(x=>`<div class="rank-row"><span class="word" title="${esc(x.label)}">${esc(x.label)}</span><div class="track"><div class="fill" style="width:${x.value/max*100}%"></div></div><strong>${nf(x.value)}</strong></div>`).join('')||'<p class="muted">Keine Daten.</p>'}
function renderLanguage(m){$('#word-chart').innerHTML=rankRows(m.topWords);$('#emoji-chart').innerHTML=rankRows(m.topEmoji);$('#phrase-list').innerHTML=rankRows(m.topPhrases);const att=Object.fromEntries(m.attachments.map(x=>[x.label,x.value]));$('#content-stats').innerHTML=[['Nachrichten mit ?',m.questions],['Links',m.links],...m.domains.slice(0,5).map(x=>['Domain · '+x.label,x.value]),['Audio-Anhänge',att.audio||0],['Bilder',att.image||0],['Videos',att.video||0],['Dokumente',att.document||0],['Sonstige Medienplatzhalter',att.media||0]].map(([a,b])=>`<div class="content-stat"><span>${esc(a)}</span><strong>${nf(b)}</strong></div>`).join('')}
function renderParticipants(m){$('#participant-cards').innerHTML=m.participants.map(p=>`<article class="participant-card"><h3>${esc(p.name)}</h3><div class="participant-stat"><span>Nachrichten</span><strong>${nf(p.messages)}</strong></div><div class="participant-stat"><span>Wörter</span><strong>${nf(p.words)}</strong></div><div class="participant-stat"><span>Aktive Tage</span><strong>${nf(p.activeDays)}</strong></div><div class="participant-stat"><span>Top Emoji</span><strong>${esc(p.topEmoji.map(x=>x.label).join(' · ')||'–')}</strong></div></article>`).join('')}
function buildPresets(){const s=state.summary,start=new Date(s.first),end=new Date(s.last),years=[];for(let y=start.getFullYear();y<=end.getFullYear();y++)years.push(y);const prevMonthEnd=new Date(end.getFullYear(),end.getMonth(),0),prevMonthStart=new Date(prevMonthEnd.getFullYear(),prevMonthEnd.getMonth(),1),prevYear=end.getFullYear()-1;const presets=[{label:'Gesamter Zeitraum',start:null,end:null},{label:'Letzte 30 Tage',start:localISO(new Date(end.getFullYear(),end.getMonth(),end.getDate()-29)),end:localISO(end)},{label:'Vorheriger Monat',start:localISO(prevMonthStart),end:localISO(prevMonthEnd)},{label:'Letzte 12 Monate',start:localISO(new Date(end.getFullYear()-1,end.getMonth(),end.getDate()+1)),end:localISO(end)},{label:'Vorheriges Kalenderjahr',start:`${prevYear}-01-01`,end:`${prevYear}-12-31`},...years.slice(-6).reverse().map(y=>({label:String(y),start:`${y}-01-01`,end:`${y}-12-31`}))];$('#preset-grid').innerHTML=presets.map((p,i)=>`<button type="button" data-preset="${i}">${esc(p.label)}</button>`).join('');$('#preset-grid').onclick=e=>{const b=e.target.closest('[data-preset]');if(!b)return;const p=presets[+b.dataset.preset];state.range={start:p.start,end:p.end,label:p.label};$('#filter-dialog').close();requestMetrics()}}
function clearAll(){state.worker?.postMessage({type:'clear'});state.worker?.terminate();state.worker=null;state.summary=null;state.metrics=null;state.fileName='';$('#file-input').value='';show('import-view')}
$('#file-input').addEventListener('change',e=>loadFile(e.target.files[0]));const drop=$('#file-drop');['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));$('#review-back').onclick=clearAll;$$('[data-date-order]').forEach(b=>b.onclick=()=>{state.dateOrder=b.dataset.dateOrder;state.worker.postMessage({type:'reparse',dateOrder:state.dateOrder})});$('#analyze-button').onclick=openDashboard;$('#clear-button').onclick=()=>{if(confirm('Geladene Chatdaten und Analyse aus diesem Tab löschen?'))clearAll()};$('#filter-button').onclick=()=>{$('#range-start').value=state.range.start||localISO(state.summary.first);$('#range-end').value=state.range.end||localISO(state.summary.last);$('#filter-dialog').showModal()};$('#apply-range').onclick=()=>{const a=$('#range-start').value,b=$('#range-end').value;if(!a||!b||a>b)return;state.range={start:a,end:b,label:'Eigener Zeitraum'};$('#filter-dialog').close();requestMetrics()};$('#apply-month').onclick=()=>{const v=$('#range-month').value;if(!v)return;const [y,m]=v.split('-').map(Number),a=`${y}-${String(m).padStart(2,'0')}-01`,last=new Date(y,m,0),b=localISO(last);state.range={start:a,end:b,label:new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))};$('#filter-dialog').close();requestMetrics()};$('#granularity').onclick=e=>{const b=e.target.closest('[data-granularity]');if(!b)return;state.granularity=b.dataset.granularity;$$('#granularity button').forEach(x=>x.classList.toggle('active',x===b));renderLine(series(state.metrics))};$('#gap-button').onclick=()=>$('#gap-dialog').showModal();$('#gap-options').innerHTML=[1,2,4,6,8,12,24,48].map(h=>`<button type="button" data-gap="${h}">${h} h</button>`).join('');$('#gap-options').onclick=e=>{const b=e.target.closest('[data-gap]');if(!b)return;state.gapHours=+b.dataset.gap;$('#gap-dialog').close();requestMetrics()};$('#stopword-select').onchange=e=>{state.stopwords=e.target.value;requestMetrics()};$('#report-button').onclick=()=>{$('#report-status').textContent='';$('#report-range').textContent=$('#range-dates').textContent;$('#report-dialog').showModal()};$('#generate-report').onclick=async()=>{const btn=$('#generate-report');btn.disabled=true;$('#report-status').textContent='Report wird lokal gerendert …';try{const style=$('input[name="report-style"]:checked').value,anon=$('#report-anonymize').checked;await window.WhatsAppReport.generate({summary:state.summary,metrics:state.metrics,style,anonymize:anon,rangeLabel:state.range.label});$('#report-status').textContent='PDF wurde erstellt.'}catch(e){$('#report-status').textContent='PDF konnte nicht erstellt werden: '+e.message}finally{btn.disabled=false}};window.addEventListener('pagehide',()=>state.worker?.terminate());
