'use strict';
(()=>{const W=1240,H=1754,M=90,INK='#172019',MUTED='#667168',ACC='#1d7a4b',PALE='#e8f2e9',LINE='#d8ded6',BG='#f6f7f3';const nf=n=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:1}).format(n||0);const dt=ms=>ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(ms)):'–';const duration=ms=>{if(!ms)return'0 Min.';const s=Math.round(ms/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d} T ${h} Std.`:h?`${h} Std. ${m} Min.`:m?`${m} Min.`:`${s} Sek.`};
function canvas(){const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle=BG;x.fillRect(0,0,W,H);x.textBaseline='top';return[c,x]}
function txt(x,t,px,y,size=28,weight=400,color=INK,max=1060){x.fillStyle=color;x.font=`${weight} ${size}px Arial, sans-serif`;const words=String(t).split(/\s+/);let line='',yy=y;for(const w of words){const test=line?line+' '+w:w;if(x.measureText(test).width>max&&line){x.fillText(line,px,yy);line=w;yy+=size*1.25}else line=test}if(line)x.fillText(line,px,yy);return yy+size*1.25}
function eyebrow(x,t,y){return txt(x,t.toUpperCase(),M,y,18,700,ACC)}
function title(x,t,y,size=62){return txt(x,t,M,y,size,700,INK,1000)}
function footer(x,page,style){x.strokeStyle=LINE;x.beginPath();x.moveTo(M,H-75);x.lineTo(W-M,H-75);x.stroke();txt(x,style==='analytical'?'LOCAL WHATSAPP ANALYSIS':'LOCAL COMMUNICATIONS DOSSIER',M,H-58,14,700,MUTED);x.textAlign='right';txt(x,String(page),W-M,H-58,14,700,MUTED);x.textAlign='left'}
function box(x,xx,y,w,h){x.fillStyle='#fff';x.strokeStyle=LINE;x.lineWidth=2;x.beginPath();x.roundRect(xx,y,w,h,22);x.fill();x.stroke()}
function kpis(x,items,y){const gap=14,w=(W-2*M-gap*2)/3,h=150;items.forEach((it,i)=>{const xx=M+(i%3)*(w+gap),yy=y+Math.floor(i/3)*(h+gap);box(x,xx,yy,w,h);txt(x,it[0],xx+22,yy+24,18,700,MUTED,w-44);txt(x,it[1],xx+22,yy+59,38,700,INK,w-44)});return y+Math.ceil(items.length/3)*(h+gap)}
function bars(x,data,y,h=360,label=''){const max=Math.max(1,...data.map(d=>d.value));if(label)txt(x,label,M,y,20,700,MUTED);y+=label?38:0;data.slice(0,10).forEach((d,i)=>{const yy=y+i*31;txt(x,d.label,M,yy,17,400,INK,260);x.fillStyle='#e4e9e3';x.fillRect(M+290,yy+3,600,17);x.fillStyle=ACC;x.fillRect(M+290,yy+3,600*d.value/max,17);txt(x,nf(d.value),M+915,yy,16,700,MUTED)});return y+Math.min(10,data.length)*31+20}
function lineChart(x,data,y,h=360){const xx=M,ww=W-2*M,p=45,max=Math.max(1,...data.map(d=>d.value));box(x,xx,y,ww,h);if(data.length<2)return y+h;const pts=data.map((d,i)=>[xx+p+(ww-2*p)*i/(data.length-1),y+h-p-(h-2*p)*d.value/max]);x.strokeStyle='#dfe5de';x.beginPath();x.moveTo(xx+p,y+h-p);x.lineTo(xx+ww-p,y+h-p);x.stroke();x.strokeStyle=ACC;x.lineWidth=5;x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.stroke();x.fillStyle=ACC;for(const pnt of pts.filter((_,i)=>i%Math.max(1,Math.ceil(pts.length/20))===0)){x.beginPath();x.arc(pnt[0],pnt[1],4,0,Math.PI*2);x.fill()}return y+h}
function pageHead(x,kicker,heading,desc){eyebrow(x,kicker,85);let y=title(x,heading,120,58);if(desc)y=txt(x,desc,M,y+12,24,400,MUTED,980);return y+35}
function names(summary,anon){if(!anon)return summary.participants;return summary.participants.map((_,i)=>`Person ${String.fromCharCode(65+i)}`)}
function remap(data,map){return data.map(d=>({...d,label:map.get(d.label)||d.label}))}
function copyMetrics(m,map){return{...m,byPerson:remap(m.byPerson,map),participants:m.participants.map(p=>({...p,name:map.get(p.name)||p.name})),sessions:{...m.sessions,starters:remap(m.sessions.starters,map)},switches:{...m.switches,directions:m.switches.directions.map(d=>({...d,label:d.label.split(' → ').map(n=>map.get(n)||n).join(' → ')}))}}}
const copy={analytical:{cover:'WhatsApp Chat Analysis',sub:'Lokaler, deskriptiver Analysebericht',activity:'Aktivität über Zeit',timing:'Zeitliche Muster',people:'Teilnehmer & Gesprächsdynamik',language:'Text, Emoji & Links',method:'Methodik & Datenqualität'},serious:{cover:'THE OFFICIAL COMMUNICATION AUDIT',sub:'Eine vollkommen angemessene Untersuchung des Nachrichtenaufkommens',activity:'THE ESCALATION TIMELINE',timing:'OPERATING HOURS',people:'COMMUNICATION COMMAND STRUCTURE',language:'LINGUISTIC INTELLIGENCE',method:'MANDATORY METHODOLOGICAL DISCLOSURE'},bureaucracy:{cover:'KOMMUNIKATIONS-PRÜFBERICHT',sub:'Vorgang WA-01 · Statistische Bestandsaufnahme gemäß interner Neugier',activity:'ABSCHNITT II — NACHRICHTENAUFKOMMEN',timing:'ABSCHNITT III — ZEITLICHE BETRIEBSMUSTER',people:'ABSCHNITT IV — BETEILIGTENSTATISTIK',language:'ABSCHNITT V — SPRACHLICHE KENNZAHLEN',method:'ANLAGE A — METHODISCHE HINWEISE'}};
function buildPages({summary,metrics,style,anonymize,rangeLabel}){const C=copy[style]||copy.analytical,ns=names(summary,anonymize),map=new Map(summary.participants.map((n,i)=>[n,ns[i]])),m=copyMetrics(metrics,map),pages=[];
{const[c,x]=canvas();eyebrow(x,style==='analytical'?'LOCAL PERSONAL DATA REPORT':'CONFIDENTIAL · LOCALLY GENERATED',180);let y=title(x,C.cover,235,76);y=txt(x,C.sub,M,y+20,29,400,MUTED,900);x.fillStyle=ACC;x.fillRect(M,y+60,90,8);y+=130;txt(x,ns.length===2?ns.join(' × '):`${ns.length} Teilnehmer`,M,y,34,700,INK);y+=58;txt(x,`${dt(m.first)} – ${dt(m.last)}`,M,y,25,400,MUTED);y+=85;box(x,M,y,W-2*M,270);txt(x,nf(m.count),M+35,y+34,74,700,INK);txt(x,'Nachrichten im ausgewählten Zeitraum',M+35,y+122,24,400,MUTED);txt(x,rangeLabel,M+35,y+190,18,700,ACC);txt(x,'Dieser Bericht wurde vollständig lokal im Browser aus einem WhatsApp-Text-Export erzeugt. Keine Chatdaten wurden für die Erstellung übertragen.',M,H-230,20,400,MUTED,980);footer(x,1,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'01 · SUMMARY',style==='analytical'?'Executive Summary':'Lageübersicht',style==='analytical'?'Die wichtigsten Kennzahlen für den ausgewählten Zeitraum.':'Die Zahlenlage ist eindeutig. Ihre Bedeutung bleibt erfreulich unpsychologisch.');y=kpis(x,[["Nachrichten",nf(m.count)],["Wörter",nf(m.wordCount)],["Aktive Tage",nf(m.activeDays)],["Wörter / Nachricht",nf(m.avgWords)],["Aktivste Stunde",m.count?String(m.activeHour).padStart(2,'0')+':00':'–'],["Top Emoji",m.topEmoji[0]?.label||'–']],y);y+=25;txt(x,'Nachrichtenanteile',M,y,25,700);y=bars(x,m.byPerson,y+45);footer(x,2,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'02 · ACTIVITY',C.activity,style==='analytical'?'Nachrichtenvolumen und Aktivitätsrekorde im Zeitverlauf.':'Dokumentation des fortlaufenden Kommunikationsgeschehens.');y=lineChart(x,m.months.length>1?m.months:m.days,y,420)+35;y=kpis(x,[["Aktivster Tag",m.activeDay?dt(new Date(m.activeDay.label+'T12:00').getTime()):'–'],["Nachrichten an diesem Tag",m.activeDay?nf(m.activeDay.value):'–'],["Längste tägliche Serie",nf(m.longestStreak)+' Tage'],["Längste Pause",duration(m.longestPause)],["Aktivster Monat",m.activeMonth?.label||'–'],["Aktive Tage",nf(m.activeDays)]],y);if(style!=='analytical'&&m.longestPause){y+=30;txt(x,style==='bureaucracy'?'VORFALL: KOMMUNIKATIONSUNTERBRECHUNG':'THE GREAT SILENCE',M,y,25,700,ACC);txt(x,`Für ${duration(m.longestPause)} wurde keine Nachricht registriert. Der Betrieb wurde anschließend offenbar wieder aufgenommen.`,M,y+42,21,400,MUTED,1000)}footer(x,3,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'03 · TIMING',C.timing,'Verteilung nach Uhrzeit und Wochentag. Zeitangaben entsprechen den lokalen Zeitstempeln des Exports.');const hd=m.hours.map((v,i)=>({label:String(i).padStart(2,'0')+':00',value:v}));y=bars(x,hd.sort((a,b)=>b.value-a.value).slice(0,10),y,360,'Aktivste Stunden')+25;const wd=['So','Mo','Di','Mi','Do','Fr','Sa'].map((label,i)=>({label,value:m.weekdays[i]})).sort((a,b)=>b.value-a.value);y=bars(x,wd,y,300,'Wochentage');footer(x,4,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'04 · DYNAMICS',C.people,`Eine aktive Phase beginnt nach mindestens ${m.gapHours} Stunden ohne Nachricht. Sprecherwechsel sind Zeitabstände, keine semantisch erkannten Antworten.`);y=kpis(x,[["Aktive Phasen",nf(m.sessions.count)],["Median Nachrichten / Phase",nf(m.sessions.medianMessages)],["Median Phasendauer",duration(m.sessions.medianDuration)],["Median Sprecherwechsel",duration(m.switches.median)],["75. Perzentil Sprecherwechsel",duration(m.switches.p75)],["90. Perzentil Sprecherwechsel",duration(m.switches.p90)]],y);y+=30;txt(x,'Starts aktiver Phasen',M,y,25,700);y=bars(x,m.sessions.starters,y+42);footer(x,5,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'05 · LANGUAGE',C.language,'Häufigkeiten werden rein lokal aus dem geschriebenen Text berechnet; URLs werden nicht aufgerufen.');txt(x,'Häufigste Wörter',M,y,25,700);y=bars(x,m.topWords,y+42);txt(x,'Emoji',M,y,25,700);y=bars(x,m.topEmoji,y+42);footer(x,6,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'06 · DETAILS','Links, Anhänge & Teilnehmer','Anhänge werden in V1 ausschließlich anhand expliziter Hinweise im TXT klassifiziert; Mediendateien selbst werden nicht analysiert.');const att=Object.fromEntries(m.attachments.map(a=>[a.label,a.value]));y=kpis(x,[["Links",nf(m.links)],["Nachrichten mit ?",nf(m.questions)],["Audio-Hinweise",nf(att.audio||0)],["Bilder",nf(att.image||0)],["Videos",nf(att.video||0)],["Dokumente",nf(att.document||0)]],y);y+=25;for(const p of m.participants.slice(0,8)){box(x,M,y,W-2*M,105);txt(x,p.name,M+25,y+18,23,700);txt(x,`${nf(p.messages)} Nachrichten · ${nf(p.words)} Wörter · ${nf(p.activeDays)} aktive Tage · Top Emoji: ${p.topEmoji.map(e=>e.label).join(' ')||'–'}`,M+25,y+55,17,400,MUTED,990);y+=117;if(y>H-190)break}footer(x,7,style);pages.push(c)}
{const[c,x]=canvas();let y=pageHead(x,'APPENDIX',C.method,'Was dieser Bericht misst – und was ausdrücklich nicht.');const paras=[`Quelle: WhatsApp-Text-Export. Analysierter Zeitraum: ${dt(m.first)} bis ${dt(m.last)}.`, `Import: ${nf(summary.totalMessages)} Nachrichten erkannt, ${nf(summary.systemRecords)} Systemeinträge und ${nf(summary.unclassified)} nicht klassifizierte Zeilen. Datumsreihenfolge: ${summary.order}.`, `Aktive Phase: Eine neue Phase beginnt nach mindestens ${m.gapHours} Stunden ohne Nachricht. Diese Schwelle ist eine technische Definition und keine Aussage über Gesprächsqualität.`, `Sprecherwechsel: Zeit zwischen einer Nachricht einer Person und der nächsten Nachricht einer anderen Person innerhalb einer aktiven Phase. Dies erkennt keine direkte Antwortbeziehung.`, `Textstatistik: Wörter, Phrasen, Emoji, Fragezeichen, Links und Domains werden aus dem vorhandenen Text gezählt. Häufigkeiten erlauben keine psychologischen oder sozialen Schlussfolgerungen.`, `Anhänge: V1 liest keine Mediendateien. Kategorien wie Audio, Bild, Video oder Dokument werden nur gezählt, wenn der TXT-Export einen entsprechenden Platzhalter oder Anhangsnamen enthält. Audiodauern werden nicht geschätzt.`, `Datenschutz: Die Analyse und PDF-Erzeugung erfolgen im Browser. Die Anwendung verwendet für die geladenen Daten weder Server-Upload noch localStorage, sessionStorage, Cookies oder externe Analyse-APIs.`];for(const p of paras){y=txt(x,p,M,y,22,400,INK,1000)+28}footer(x,8,style);pages.push(c)}return pages}
async function jpegBytes(c){const blob=await new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Canvas export failed')),'image/jpeg',.9));return new Uint8Array(await blob.arrayBuffer())}
function ascii(s){return new TextEncoder().encode(s)}function concat(parts){const n=parts.reduce((a,b)=>a+b.length,0),o=new Uint8Array(n);let p=0;for(const b of parts){o.set(b,p);p+=b.length}return o}
async function pdfFromCanvases(canvases){const imgs=[];for(const c of canvases)imgs.push(await jpegBytes(c));const count=2+canvases.length*3,objs=new Array(count+1);objs[1]=ascii('<< /Type /Catalog /Pages 2 0 R >>');const kids=[];for(let i=0;i<canvases.length;i++)kids.push(`${3+i*3} 0 R`);objs[2]=ascii(`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${canvases.length} >>`);for(let i=0;i<canvases.length;i++){const page=3+i*3,img=page+1,content=page+2,name=`Im${i+1}`,stream=`q\n595 0 0 842 0 0 cm\n/${name} Do\nQ\n`;objs[page]=ascii(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /${name} ${img} 0 R >> >> /Contents ${content} 0 R >>`);objs[img]=concat([ascii(`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imgs[i].length} >>\nstream\n`),imgs[i],ascii('\nendstream')]);objs[content]=ascii(`<< /Length ${ascii(stream).length} >>\nstream\n${stream}endstream`)}const header=ascii('%PDF-1.4\n%LOCAL\n'),parts=[header],offs=new Array(count+1).fill(0);let pos=header.length;for(let i=1;i<=count;i++){offs[i]=pos;const pre=ascii(`${i} 0 obj\n`),post=ascii('\nendobj\n');parts.push(pre,objs[i],post);pos+=pre.length+objs[i].length+post.length}const xref=pos;let table=`xref\n0 ${count+1}\n0000000000 65535 f \n`;for(let i=1;i<=count;i++)table+=String(offs[i]).padStart(10,'0')+' 00000 n \n';table+=`trailer\n<< /Size ${count+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(ascii(table));return new Blob(parts,{type:'application/pdf'})}
async function generate(opts){const pages=buildPages(opts),pdf=await pdfFromCanvases(pages),url=URL.createObjectURL(pdf),a=document.createElement('a'),slug=opts.style==='analytical'?'analysis':opts.style;a.href=url;a.download=`whatsapp-${slug}-${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}window.WhatsAppReport={generate};})();
