export {
  CONVERSATION_SCHEMA_VERSION,
  CONVERSATION_CATEGORIES,
  CONVERSATION_INTENSITIES,
  CONVERSATION_CONTEXTS,
  CONVERSATION_TOPICS,
  CONVERSATION_STATUSES
} from "../../x/conversation/shared/schema.js";
