import { adminApi } from "/x/admin/shared/api.js";
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const statusLabel={running:"Läuft",paused:"Pausiert","level-change":"Blindwechsel",finished:"Beendet"};
function timeAgo(value){const ms=Date.now()-Number(value||0);if(!Number.isFinite(ms)||ms<0)return "–";const m=Math.floor(ms/60000);if(m<1)return "gerade eben";if(m<60)return `vor ${m} Min.`;const h=Math.floor(m/60);if(h<24)return `vor ${h} Std.`;const d=Math.floor(h/24);return `vor ${d} Tag${d===1?"":"en"}`;}
function dateTime(value){if(!value)return "–";return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(Number(value)));}
function metric(label,value){return `<div class="metric"><span class="metric-label">${esc(label)}</span><strong class="metric-value">${esc(value)}</strong></div>`;}
function render(data){const sessions=data.sessions||[];const live=sessions.filter(s=>["running","paused","level-change"].includes(s.status));$("[data-metrics]").innerHTML=metric("Live",live.length)+metric("Erfasst",sessions.length)+metric("Beendet",sessions.filter(s=>s.status==="finished").length)+metric("Aktiv zuletzt",sessions[0]?timeAgo(sessions[0].lastActivityAt):"–");const box=$("[data-sessions]");if(!sessions.length){box.innerHTML='<div class="event-empty">Noch keine Poker-Sessions in der Registry.</div>';return;}box.innerHTML=sessions.map(s=>`<article class="poker-session-row"><div class="poker-session-main"><div class="poker-session-title"><strong>${esc(s.code)}</strong><span class="status-pill status-${s.status==="finished"?"neutral":s.status==="paused"?"attention":"healthy"}">${esc(statusLabel[s.status]||s.status)}</span></div><p>${s.currentBlinds?`Blinds ${esc(s.currentBlinds.sb)} / ${esc(s.currentBlinds.bb)} · `:""}Hand ${esc(s.hand)} · ${esc(s.activePlayerCount)} von ${esc(s.playerCount)} Spielern aktiv</p></div><div class="poker-session-meta"><strong>${esc(timeAgo(s.lastActivityAt))}</strong><span>${esc(dateTime(s.lastActivityAt))}</span><span>Erstellt ${esc(dateTime(s.createdAt))}</span></div></article>`).join("");}
async function load(){const button=$("[data-refresh]");button.disabled=true;try{render(await adminApi("/poker/sessions"));}catch(error){$("[data-sessions]").innerHTML=`<div class="load-error">${esc(error.message)}</div>`;}finally{button.disabled=false;}}
$("[data-refresh]").addEventListener("click",load);load();
