import { adminApi } from "/x/admin/shared/api.js";
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const statusLabel={running:"Läuft",paused:"Pausiert","level-change":"Blindwechsel",finished:"Beendet"};
function timeAgo(v){const ms=Date.now()-Number(v||0);if(!Number.isFinite(ms)||ms<0)return"–";const m=Math.floor(ms/60000);if(m<1)return"gerade eben";if(m<60)return`vor ${m} Min.`;const h=Math.floor(m/60);if(h<24)return`vor ${h} Std.`;const d=Math.floor(h/24);return`vor ${d} Tag${d===1?"":"en"}`}
function dateTime(v){return v?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(Number(v))):"–"}
function metric(l,v){return`<div class="metric"><span class="metric-label">${esc(l)}</span><strong class="metric-value">${esc(v)}</strong></div>`}
function toast(msg){const el=$("[data-toast]");el.textContent=msg;el.hidden=false;setTimeout(()=>el.hidden=true,2600)}
function render(data){const sessions=data.sessions||[],live=sessions.filter(s=>["running","paused","level-change"].includes(s.status));$("[data-metrics]").innerHTML=metric("Live",live.length)+metric("Erfasst",sessions.length)+metric("Beendet",sessions.filter(s=>s.status==="finished").length)+metric("Aktiv zuletzt",sessions[0]?timeAgo(sessions[0].lastActivityAt):"–");$("[data-auto-delete]").value=String(data.settings?.autoDeleteHours||0);const box=$("[data-sessions]");if(!sessions.length){box.innerHTML='<div class="event-empty">Keine Poker-Sessions gespeichert.</div>';return}box.innerHTML=sessions.map(s=>`<article class="poker-session-row"><div class="poker-session-main"><div class="poker-session-title"><strong>${esc(s.code)}</strong><span class="status-pill status-${s.status==="finished"?"neutral":s.status==="paused"?"attention":"healthy"}">${esc(statusLabel[s.status]||s.status)}</span></div><p>Session-/Display-Code · ${s.currentBlinds?`Blinds ${esc(s.currentBlinds.sb)} / ${esc(s.currentBlinds.bb)} · `:""}Hand ${esc(s.hand)} · ${esc(s.activePlayerCount)} von ${esc(s.playerCount)} aktiv</p><div class="poker-session-actions"><a class="button button-secondary" href="/x/poker/live/display/?code=${esc(s.code)}" target="_blank" rel="noopener">Display öffnen</a><button class="button button-secondary" data-recover="${esc(s.code)}">Controller-Link neu erzeugen</button><button class="button button-danger" data-delete="${esc(s.code)}">Löschen</button></div></div><div class="poker-session-meta"><strong>${esc(timeAgo(s.lastActivityAt))}</strong><span>${esc(dateTime(s.lastActivityAt))}</span><span>Erstellt ${esc(dateTime(s.createdAt))}</span></div></article>`).join("")}
async function load(){const b=$("[data-refresh]");b.disabled=true;try{render(await adminApi("/poker/sessions"))}catch(e){$("[data-sessions]").innerHTML=`<div class="load-error">${esc(e.message)}</div>`}finally{b.disabled=false}}
$("[data-refresh]").addEventListener("click",load);
$("[data-save-settings]").addEventListener("click",async()=>{await adminApi("/poker/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({autoDeleteHours:Number($("[data-auto-delete]").value)})});toast("Bereinigung gespeichert.");await load()});
$("[data-delete-all]").addEventListener("click",async()=>{if(!confirm("Wirklich ALLE Poker-Sessions endgültig löschen? Laufende Pokerabende werden dabei ebenfalls gelöscht."))return;if(!confirm("Letzte Bestätigung: Alle Sessions und ihre gespeicherten Zustände löschen?"))return;await adminApi("/poker/sessions",{method:"DELETE"});toast("Alle Sessions gelöscht.");await load()});
$("[data-sessions]").addEventListener("click",async e=>{const recover=e.target.closest("[data-recover]"),del=e.target.closest("[data-delete]");if(recover){const code=recover.dataset.recover;if(!confirm(`Neuen Controller-Link für ${code} erzeugen? Der bisherige Controller-Token wird ungültig.`))return;const r=await adminApi(`/poker/sessions/${code}/recover`,{method:"POST"});window.open(r.controllerUrl,"_blank","noopener");toast("Neuer Controller-Link erzeugt.");await load()}if(del){const code=del.dataset.delete;if(!confirm(`Session ${code} endgültig löschen?`))return;await adminApi(`/poker/sessions/${code}`,{method:"DELETE"});toast(`Session ${code} gelöscht.`);await load()}});load();
