const nextSeat = (seat, seats) => seat % seats + 1;
const activePlayers = (s) => s.players.filter(p => p.status === 'active');
const activeAt = (s, seat) => s.players.find(p => p.seat === seat && p.status === 'active');
function nextActiveSeat(s, from) { let seat=from; for(let i=0;i<s.players.length;i++){ seat=nextSeat(seat,s.players.length); if(activeAt(s,seat)) return seat; } return null; }
function rolesFromDealer(s,dealerSeat){ const count=activePlayers(s).length; if(count===2){ const button=activeAt(s,dealerSeat)?dealerSeat:nextActiveSeat(s,dealerSeat); return {buttonSeat:button,smallBlindSeat:button,smallBlindPosition:button,bigBlindSeat:nextActiveSeat(s,button)}; } const button=dealerSeat; const sb=nextActiveSeat(s,button); return {buttonSeat:button,smallBlindSeat:sb,smallBlindPosition:sb,bigBlindSeat:nextActiveSeat(s,sb)}; }
function ensureBlindPositions(s){ if(!Number.isInteger(s.smallBlindPosition)) s.smallBlindPosition=s.smallBlindSeat ?? s.bigBlindSeat; }
function nextRolesDeadButton(s){
  const count=activePlayers(s).length;
  if(count===2){ const bb=nextActiveSeat(s,s.bigBlindSeat); const button=nextActiveSeat(s,bb); return {buttonSeat:button,smallBlindSeat:button,smallBlindPosition:button,bigBlindSeat:bb}; }
  ensureBlindPositions(s); const bb=nextActiveSeat(s,s.bigBlindSeat); const nominalSb=s.bigBlindSeat; const sb=activeAt(s,nominalSb)?nominalSb:null; const button=s.smallBlindPosition; return {buttonSeat:button,smallBlindSeat:sb,smallBlindPosition:nominalSb,bigBlindSeat:bb};
}
function normalizeRoundSeen(s){ const activeIds=new Set(activePlayers(s).map(p=>p.id)); s.roundSeenBigBlind=(s.roundSeenBigBlind||[]).filter(id=>activeIds.has(id)); }
function recordCompletedBigBlind(s){ const bb=s.players.find(p=>p.seat===s.bigBlindSeat); if(bb && !(s.roundSeenBigBlind||[]).includes(bb.id)) (s.roundSeenBigBlind||(s.roundSeenBigBlind=[])).push(bb.id); }
function finishRoundIfComplete(s){ normalizeRoundSeen(s); const ids=activePlayers(s).map(p=>p.id); if(ids.length && ids.every(id=>s.roundSeenBigBlind.includes(id))){ s.round+=1; s.roundSeenBigBlind=[]; if(s.round>s.roundsPerLevel) s.status='level-change'; } }
function log(s,label){ s.eventLog||(s.eventLog=[]); s.eventLog.unshift({at:Date.now(),label}); s.eventLog=s.eventLog.slice(0,60); }
function snapshot(s){ const copy=structuredClone(s); delete copy.controllerToken; delete copy.undoStack; return copy; }
function checkpoint(s,label){ s.undoStack||(s.undoStack=[]); s.undoStack.push({label,state:snapshot(s)}); s.undoStack=s.undoStack.slice(-20); }
export function createSession(input){ const players=(input.players||[]).map((name,i)=>({id:`p${i+1}`,name:String(name||`Spieler ${i+1}`).slice(0,30),seat:i+1,status:'active'})); if(players.length<2) throw new Error('Mindestens zwei Spieler erforderlich.'); const dealer=Math.max(1,Math.min(players.length,Number(input.dealerSeat)||1)); const s={version:3,status:'running',players,level:1,round:1,hand:1,roundsPerLevel:Math.max(1,Number(input.roundsPerLevel)||2),blindLevels:input.blindLevels||[{sb:5,bb:10}],colorUps:Array.isArray(input.colorUps)?input.colorUps.map(x=>({value:Number(x.value),afterSb:Number(x.afterSb),afterBb:Number(x.afterBb)})).filter(x=>x.value>0):[],pendingEliminations:[],roundSeenBigBlind:[],overlay:null,displayMode:'table',eventLog:[],undoStack:[],createdAt:Date.now()}; Object.assign(s,rolesFromDealer(s,dealer)); log(s,'Turnier gestartet'); return s; }
export function completeHand(s){ if(s.status!=='running') throw new Error('Aktuell kann keine Hand beendet werden.'); checkpoint(s,`Hand ${s.hand} wiederherstellen`); recordCompletedBigBlind(s); for(const id of s.pendingEliminations){ const p=s.players.find(x=>x.id===id); if(p) p.status='out'; } s.pendingEliminations=[]; normalizeRoundSeen(s); if(activePlayers(s).length<2){ s.status='finished'; log(s,'Turnier beendet'); return s; } const roles=nextRolesDeadButton(s); Object.assign(s,roles); s.hand+=1; finishRoundIfComplete(s); log(s,s.status==='level-change'?'Blindstufe abgeschlossen':'Nächste Hand'); return s; }
export function eliminatePlayer(s,id){ const p=s.players.find(x=>x.id===id && x.status==='active'); if(!p) throw new Error('Spieler nicht aktiv.'); if(activePlayers(s).length<=2) throw new Error('Beim letzten Duell beendet der Gewinner das Turnier.'); if(!s.pendingEliminations.includes(id)){ checkpoint(s,`${p.name} wieder aktiv setzen`); s.pendingEliminations.push(id); log(s,`${p.name}: Ausscheiden nach dieser Hand`); } return s; }
export function cancelElimination(s,id){ if(s.pendingEliminations.includes(id)){ const p=s.players.find(x=>x.id===id); checkpoint(s,`${p?.name||'Spieler'}-Markierung wiederherstellen`); s.pendingEliminations=s.pendingEliminations.filter(x=>x!==id); log(s,`${p?.name||'Spieler'}: Ausscheiden zurückgenommen`); } return s; }
export function startNextLevel(s){ if(s.status!=='level-change') throw new Error('Blindstufe ist noch nicht abgeschlossen.'); checkpoint(s,'Vorherige Blindstufe wiederherstellen'); if(s.level>=s.blindLevels.length) s.blindLevels.push({sb:s.blindLevels.at(-1).sb*2,bb:s.blindLevels.at(-1).bb*2}); s.level+=1;s.round=1;s.roundSeenBigBlind=[];s.status='running';log(s,`Blinds ${s.blindLevels[s.level-1].sb}/${s.blindLevels[s.level-1].bb} gestartet`);return s; }
export function togglePause(s){ if(s.status==='paused'){s.status='running';log(s,'Pause beendet');} else if(s.status==='running'){s.status='paused';log(s,'Pause gestartet');} return s; }
export function finishSession(s){ if(s.status==='finished') return s; checkpoint(s,'Pokerabend fortsetzen'); s.status='finished';s.pendingEliminations=[];log(s,'Pokerabend manuell beendet');return s; }
export function correctRoles(s,{buttonSeat,smallBlindSeat,bigBlindSeat}){ const seats=s.players.length; const d=Number(buttonSeat), sb=smallBlindSeat===null||Number(smallBlindSeat)===0?null:Number(smallBlindSeat), bb=Number(bigBlindSeat); if(!Number.isInteger(d)||d<1||d>seats) throw new Error('Ungültiger Dealer-Sitz.'); if(sb!==null&&(!Number.isInteger(sb)||!activeAt(s,sb))) throw new Error('Small Blind muss ein aktiver Sitz sein oder 0 für keinen SB.'); if(!Number.isInteger(bb)||!activeAt(s,bb)) throw new Error('Big Blind muss ein aktiver Sitz sein.'); if(activePlayers(s).length===2 && (sb!==d || !activeAt(s,d))) throw new Error('Heads-up muss Dealer und Small Blind derselbe aktive Spieler sein.'); checkpoint(s,'Positionskorrektur zurücknehmen'); s.buttonSeat=d;s.smallBlindSeat=sb;s.smallBlindPosition=sb??d;s.bigBlindSeat=bb;log(s,`Positionen korrigiert: D Sitz ${d} · SB ${sb??'–'} · BB Sitz ${bb}`);return s; }
export function undoLast(s){ const item=(s.undoStack||[]).pop(); if(!item) throw new Error('Keine Aktion zum Rückgängigmachen vorhanden.'); const token=s.controllerToken,remaining=s.undoStack; for(const key of Object.keys(s)) delete s[key]; Object.assign(s,structuredClone(item.state)); s.controllerToken=token;s.undoStack=remaining;log(s,`Rückgängig: ${item.label}`);return s; }
export function setOverlay(s,overlay){s.overlay=overlay||null;return s;}
export function setDisplayMode(s,mode){s.displayMode=['table','broadcast','minimal'].includes(mode)?mode:'table';return s;}
export function publicState(s){ ensureBlindPositions(s); const {controllerToken,undoStack,...safe}=s; const currentBlinds=s.blindLevels[Math.min(s.level-1,s.blindLevels.length-1)],nextBlinds=s.blindLevels[s.level]||null; const colorUps=(s.colorUps||[]).filter(x=>x.afterSb===currentBlinds.sb&&x.afterBb===currentBlinds.bb).map(x=>x.value); return {...safe,currentBlinds,nextBlinds,colorUpsDue:colorUps,canUndo:Boolean(s.undoStack?.length),undoLabel:s.undoStack?.at(-1)?.label||null}; }
