const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow, noarchive, nosnippet'}});
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const a=new Uint8Array(6);crypto.getRandomValues(a);return [...a].map(x=>chars[x%chars.length]).join('');}
function token(){const a=new Uint8Array(24);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/[+/=]/g,'').slice(0,32);}
function registryStub(env){const id=env.POKER_LIVE_REGISTRY.idFromName('poker-sessions');return env.POKER_LIVE_REGISTRY.get(id);}
function registryMeta(code,state){return {code,status:state.status,playerCount:state.players?.length||0,activePlayerCount:(state.players||[]).filter(p=>p.status==='active').length,hand:state.hand,level:state.level,currentBlinds:state.currentBlinds||null,createdAt:state.createdAt,lastActivityAt:state.updatedAt||state.createdAt};}
async function syncRegistry(env,displayCode,state){if(!state)return;try{await registryStub(env).fetch(new Request('https://registry/upsert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(registryMeta(displayCode,state))}));}catch(error){console.error('Poker registry sync failed',error)}}
async function syncFromResponse(env,displayCode,response){if(!response.ok||response.status===101)return;const type=response.headers.get('Content-Type')||'';if(!type.includes('application/json'))return;try{const payload=await response.clone().json();if(payload?.state)await syncRegistry(env,displayCode,payload.state);}catch(error){console.error('Poker registry response sync failed',error)}}
export async function handlePokerLiveRequest(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/x/poker/live/api/'))return null;
  if(request.method==='POST'&&url.pathname==='/x/poker/live/api/sessions'){const body=await request.json();const displayCode=code(),controllerToken=token();const id=env.POKER_LIVE.idFromName(displayCode);const stub=env.POKER_LIVE.get(id);const init=new Request(`${url.origin}/init`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({setup:body,controllerToken})});const res=await stub.fetch(init);if(!res.ok)return res;await syncFromResponse(env,displayCode,res);return json({code:displayCode,token:controllerToken,controllerUrl:`/x/poker/live/?code=${displayCode}#token=${controllerToken}`,displayUrl:`/x/poker/live/display/?code=${displayCode}`},201);}
  const m=url.pathname.match(/^\/x\/poker\/live\/api\/sessions\/([A-Z0-9]{6})(?:\/(.*))?$/);if(!m)return json({error:'Nicht gefunden.'},404);const displayCode=m[1];const id=env.POKER_LIVE.idFromName(displayCode);const stub=env.POKER_LIVE.get(id);const path=m[2]||'';const headers=new Headers(request.headers);headers.delete('X-Poker-Admin-Internal');const response=await stub.fetch(new Request(`${url.origin}/${path}`,{method:request.method,headers,body:['GET','HEAD'].includes(request.method)?undefined:request.body}));await syncFromResponse(env,displayCode,response);return response;}
