import { HAND_RANKINGS } from "./hands-data.js";
import { RANKS, SUITS, cardLabel, parseCard, canonicalStartingHand } from "./poker-engine.js";
import { planPokerSetup } from "./planner.js";
import { PREFLOP_DATA, PREFLOP_META } from "./preflop-data.js";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
let uidCounter = 0;
const makeId = () => typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `poker-${Date.now()}-${uidCounter += 1}`;
const formatNumber = (value) => Number(value).toLocaleString("de-DE", { maximumFractionDigits: 0 });
const formatPercent = (value) => `${(Number(value || 0) * 100).toFixed(1).replace(".", ",")} %`;

function suitMeta(card) { const parsed = parseCard(card); return parsed ? SUITS.find((suit) => suit.key === parsed.suit) : null; }
function renderMiniCard(card) { const parsed = parseCard(card); const suit = suitMeta(card); return `<span class="mini-card ${suit?.color === "red" ? "red" : ""}">${parsed?.rank || ""}<br>${suit?.symbol || ""}</span>`; }
function renderRankings() {
  $("#ranking-list").innerHTML = HAND_RANKINGS.map((hand) => `<article class="hand-rank-card"><div class="rank-number">${hand.rank}</div><div><div class="hand-card-head"><div><h3>${hand.name}</h3><small>${hand.strength}</small></div></div><div class="mini-cards">${hand.example.map(renderMiniCard).join("")}</div><div class="hand-explanation"><p>${hand.build}</p><p><strong>Gleichstand:</strong> ${hand.tie}</p></div></div></article>`).join("");
}
function activateTab(tab) {
  $$(".tab-panel").forEach((panel) => { const active = panel.dataset.panel === tab; panel.hidden = !active; panel.classList.toggle("is-active", active); });
  $$(".nav-item").forEach((button) => { const active = button.dataset.tab === tab; button.classList.toggle("is-active", active); active ? button.setAttribute("aria-current", "page") : button.removeAttribute("aria-current"); });
  window.scrollTo({ top: 0, behavior: "instant" });
}
$$(".nav-item").forEach((button) => button.addEventListener("click", () => activateTab(button.dataset.tab)));

// SETUP ---------------------------------------------------------------------
const chipPalette = ["#a6a6a6", "#c83e46", "#315d9a", "#2e7c51", "#292e2b", "#7d52a8", "#d4a52c"];
const chipDefaults = [[1,150],[5,100],[10,100],[25,50],[100,50],[500,25],[1000,25]];
let chipRows = chipDefaults.map(([value,count], index) => ({ id: makeId(), color: chipPalette[index], value: String(value), count: String(count) }));
let blindMode = "rounds";
let pace = "relaxed";
let allowSmallBlinds = false;

function syncChipRowsFromDom() { $$(".chip-row", $("#chip-editor")).forEach((row) => { const item = chipRows.find((chip) => chip.id === row.dataset.id); if (!item) return; item.color = $(".chip-color", row).value; item.value = $(".chip-value", row).value; item.count = $(".chip-count", row).value; }); }
function renderChipEditor() {
  $("#chip-editor").innerHTML = chipRows.map((chip) => `<div class="chip-row" data-id="${chip.id}"><label class="chip-color-wrap" aria-label="Chipfarbe"><input class="chip-color" type="color" value="${chip.color}"></label><input class="chip-value" type="number" inputmode="numeric" min="1" aria-label="Chipwert" value="${chip.value}"><input class="chip-count" type="number" inputmode="numeric" min="0" aria-label="Vorhandene Anzahl" value="${chip.count}"><button class="remove-chip" type="button" aria-label="Chipsorte entfernen" ${chipRows.length <= 1 ? "disabled" : ""}>×</button></div>`).join("");
  $$("input", $("#chip-editor")).forEach((input) => input.addEventListener("input", () => { syncChipRowsFromDom(); calculateSetup(); }));
  $$(".remove-chip", $("#chip-editor")).forEach((button) => button.addEventListener("click", () => { syncChipRowsFromDom(); chipRows = chipRows.filter((chip) => chip.id !== button.closest(".chip-row").dataset.id); renderChipEditor(); calculateSetup(); }));
}
$("#add-chip").addEventListener("click", () => { syncChipRowsFromDom(); if (chipRows.length >= 10) return; const previous = Number(chipRows.at(-1)?.value) || 1000; chipRows.push({ id: makeId(), color: chipPalette[chipRows.length % chipPalette.length], value: String(previous * 2), count: "" }); renderChipEditor(); calculateSetup(); });

$$("[data-blind-mode]").forEach((button) => button.addEventListener("click", () => { blindMode = button.dataset.blindMode; $$("[data-blind-mode]").forEach((candidate) => { const active = candidate === button; candidate.classList.toggle("is-active", active); candidate.setAttribute("aria-pressed", String(active)); }); $("#time-level-field").hidden = blindMode !== "time"; $("#round-level-field").hidden = blindMode !== "rounds"; calculateSetup(); }));
$$("[data-pace]").forEach((button) => button.addEventListener("click", () => { pace = button.dataset.pace; $$("[data-pace]").forEach((candidate) => { const active = candidate === button; candidate.classList.toggle("is-active", active); candidate.setAttribute("aria-pressed", String(active)); }); calculateSetup(); }));
["#setup-players", "#setup-duration", "#setup-stack", "#setup-level-minutes", "#setup-rounds"].forEach((selector) => $(selector).addEventListener("input", calculateSetup));
$("#setup-small-blinds").addEventListener("change", (event) => { allowSmallBlinds = event.target.checked; calculateSetup(); });
$$("[data-level-preset]").forEach((button) => button.addEventListener("click", () => { $("#setup-level-minutes").value = button.dataset.levelPreset; $$("[data-level-preset]").forEach((candidate) => candidate.classList.toggle("is-active", candidate === button)); calculateSetup(); }));
function setupInput() { return { players: $("#setup-players").value, durationMinutes: $("#setup-duration").value, startingStack: $("#setup-stack").value, blindMode, levelMinutes: $("#setup-level-minutes").value, roundsPerLevel: $("#setup-rounds").value, pace, allowSmallBlinds, chips: chipRows.map((chip) => ({ ...chip })) }; }
function metricCard(label, value, detail = "") { return `<div class="metric-card"><span>${label}</span><strong>${value}</strong>${detail ? `<small>${detail}</small>` : ""}</div>`; }
function calculateSetup() { syncChipRowsFromDom(); renderSetupPlan(planPokerSetup(setupInput())); }
function renderSetupPlan(plan) {
  const opening = plan.openingBlinds;
  $("#setup-metrics").innerHTML = [metricCard("Starting Stack", formatNumber(plan.startingStack), plan.requestedStack ? (plan.exactStackMatch ? "wie gewählt" : "nächster sinnvoller Wert") : "automatisch geplant"), metricCard("Opening Blinds", `${formatNumber(opening.sb)} / ${formatNumber(opening.bb)}`, `Starttiefe · ~${Math.round(plan.startingStack / opening.bb)} BB`), metricCard("Spieler", String(plan.players), `${formatNumber(plan.startingStack * plan.players)} Chips im Spiel`), metricCard("Blindwechsel", plan.blindMode === "rounds" ? `alle ${plan.roundsPerLevel} ${plan.roundsPerLevel === 1 ? "Runde" : "Runden"}` : `alle ${formatNumber(plan.levelMinutes)} min`, plan.blindMode === "rounds" ? ($("#setup-rounds").value.trim() ? "manuell gewählt" : "automatisch ermittelt") : "zeitbasiert"), metricCard("Bank / Reserve", plan.totalReserveValue == null ? "teilw. offen" : formatNumber(plan.totalReserveValue), "bewusst nicht verteilt")].join("");
  $("#distribution-list").innerHTML = plan.perPlayer.filter((chip) => chip.perPlayer > 0).map((chip) => `<div class="distribution-row"><span class="chip-dot" style="--chip:${chip.color}"></span><strong>${chip.perPlayer} × ${formatNumber(chip.value)}</strong><span>${formatNumber(chip.perPlayer * chip.value)}</span>${chip.reserve != null ? `<small>${chip.reserve} Reserve</small>` : ""}</div>`).join("") || `<p class="helper-copy">Mit diesen Angaben wurde keine sinnvolle gleichmäßige Verteilung gefunden.</p>`;
  $("#blind-table").innerHTML = plan.blindLevels.map((level) => { const trigger = plan.blindMode === "time" ? (level.level === 1 ? "Start" : `ab ${level.startsAtMinutes} min`) : (level.level === 1 ? "Start" : `nach ${level.startsAfterRounds} Runden · ~${level.estimatedStartsAtMinutes} min`); return `<div class="blind-row"><span>${level.level}</span><strong>${formatNumber(level.sb)} / ${formatNumber(level.bb)}</strong><small>${trigger}</small></div>`; }).join("");
  $("#colorup-list").innerHTML = plan.colorUps.length ? `<div class="colorup-list">${plan.colorUps.map((item) => `<div class="colorup-row"><strong>Nach ${formatNumber(item.afterSb)} / ${formatNumber(item.afterBb)}</strong><p>${formatNumber(item.value)}er werden nicht mehr für Blinds benötigt und können gegen größere Chips aus der Bank getauscht werden.</p></div>`).join("")}</div>` : `<p class="helper-copy">Mit dieser Startstruktur ist zunächst kein eigener Color-up-Schritt nötig.</p>`;
  const notes = [...plan.assumptions, ...plan.warnings];
  $("#setup-notes").innerHTML = `<ul>${notes.map((note) => `<li>${note}</li>`).join("")}</ul><details class="explain compact"><summary>Wie entsteht die Zeitschätzung?</summary><p>Bei rundenbasierten Levels sind aktuell ${plan.players * plan.roundsPerLevel} Hände pro Level nötig. Mit ${String(plan.minutesPerHand).replace(".", ",")} Minuten pro Hand ergibt das zu Beginn ungefähr ${Math.round(plan.estimatedLevelMinutes)} Minuten. Scheidet jemand aus, braucht eine volle Tischrunde automatisch eine Hand weniger.</p></details>`;
}

// STARTHÄNDE ----------------------------------------------------------------
const MATRIX_RANKS = ["A","K","Q","J","T","9","8","7","6","5","4","3","2"];
let startingOpponents = 1;
let selectedStarting = null;
let startingCards = [null, null];
let startingPickerTarget = null, startingPickerRank = null, startingPickerSuit = null;
function handKey(row, col) { if (row === col) return `${MATRIX_RANKS[row]}${MATRIX_RANKS[col]}`; const hi = MATRIX_RANKS[Math.min(row,col)], lo = MATRIX_RANKS[Math.max(row,col)]; return `${hi}${lo}${row < col ? "s" : "o"}`; }
function ranksForOpponents(count) { const idx = count - 1; return Object.entries(PREFLOP_DATA).sort((a,b) => b[1].equity[idx] - a[1].equity[idx]).reduce((map,[key],i) => (map[key]=i+1,map),{}); }
function handDescription(key) { if (!key) return "Wähle zwei Handkarten."; if (key.length === 2) return `${key[0]}${key[1]} · Paar`; const suited = key.endsWith("s"); return `${key.slice(0,2)}${suited ? "s" : "o"} · ${suited ? "gleichfarbig (suited)" : "verschiedenfarbig (offsuit)"}`; }
function startingSlotHtml(card,index){const p=parseCard(card),suit=card?suitMeta(card):null;return p?`<button class="card-slot filled ${suit?.color==="red"?"red":""}" type="button" data-starting-slot="${index}"><span><span class="card-rank">${p.rank}</span><span class="card-suit">${suit?.symbol}</span></span></button>`:`<button class="card-slot" type="button" data-starting-slot="${index}"><span><span class="slot-plus">+</span><span class="slot-label">Hand ${index+1}</span></span></button>`;}
function matrixRank(rank){return rank === "10" ? "T" : rank;}
function cardRank(rank){return rank === "T" ? "10" : rank;}
function normalizeStartingKey(key){return key ? key.replaceAll("10", "T") : null;}
function syncStartingClass(){selectedStarting=startingCards.every(Boolean)?normalizeStartingKey(canonicalStartingHand(startingCards)):null;}
function representativeCards(key){const ranks=key.length===2?[key[0],key[1]]:[key[0],key[1]];const first=cardRank(ranks[0]),second=cardRank(ranks[1]);if(key.length===2)return [`${first}s`,`${second}h`];if(key.endsWith("s"))return [`${first}s`,`${second}s`];return [`${first}s`,`${second}h`];}
function renderStartingCards(){ $("#starting-card-slots").innerHTML=startingCards.map(startingSlotHtml).join(""); $("#starting-notation").textContent=selectedStarting||"2 Karten wählen"; $$('[data-starting-slot]').forEach(b=>b.addEventListener('click',()=>openStartingPicker(Number(b.dataset.startingSlot)))); }
function openStartingPicker(index){startingPickerTarget=index;const p=parseCard(startingCards[index]);startingPickerRank=p?.rank||null;startingPickerSuit=p?.suit||null;renderStartingPicker();$("#starting-card-picker").showModal();}
function renderStartingPicker(){const used=new Set(startingCards.filter(Boolean));$("#starting-picker-title").textContent=`${startingPickerRank||"Rang"} · ${SUITS.find(s=>s.key===startingPickerSuit)?.name||"Farbe"}`;$("#starting-rank-picker").innerHTML=RANKS.map(r=>{const c=startingPickerSuit?`${r}${startingPickerSuit}`:null;const disabled=c&&used.has(c)&&c!==startingCards[startingPickerTarget];return `<button type="button" class="rank-choice ${startingPickerRank===r?"is-active":""}" data-start-rank="${r}" ${disabled?"disabled":""}>${r}</button>`;}).join("");$$('[data-start-rank]').forEach(b=>b.addEventListener('click',()=>{startingPickerRank=b.dataset.startRank;commitStartingPicker();if($("#starting-card-picker").open)renderStartingPicker();}));$("#starting-suit-picker").innerHTML=SUITS.map(s=>{const c=startingPickerRank?`${startingPickerRank}${s.key}`:null;return `<button type="button" class="suit-choice ${s.color==="red"?"red":""} ${startingPickerSuit===s.key?"is-active":""}" data-start-suit="${s.key}" ${c&&used.has(c)&&c!==startingCards[startingPickerTarget]?"disabled":""}>${s.symbol}</button>`}).join("");$$('[data-start-suit]').forEach(b=>b.addEventListener('click',()=>{startingPickerSuit=b.dataset.startSuit;commitStartingPicker();if($("#starting-card-picker").open)renderStartingPicker();}));$("#starting-clear-card").disabled=!startingCards[startingPickerTarget];}
function commitStartingPicker(){if(!startingPickerRank||!startingPickerSuit)return;const card=`${startingPickerRank}${startingPickerSuit}`;if(startingCards.some((c,i)=>i!==startingPickerTarget&&c===card))return;startingCards[startingPickerTarget]=card;$("#starting-card-picker").close();syncStartingClass();renderStarting();}
$("#starting-picker-close").addEventListener('click',()=>$("#starting-card-picker").close());$("#starting-clear-card").addEventListener('click',()=>{startingCards[startingPickerTarget]=null;$("#starting-card-picker").close();syncStartingClass();renderStarting();});$("#starting-card-picker").addEventListener('click',e=>{if(e.target===$("#starting-card-picker"))$("#starting-card-picker").close();});
function renderOpponentButtons() { $("#starting-opponents").innerHTML = Array.from({length:8},(_,i)=>i+1).map((n)=>`<button type="button" class="${n===startingOpponents?"is-active":""}" data-starting-opponents="${n}">${n}</button>`).join(""); $$('[data-starting-opponents]').forEach((b)=>b.addEventListener('click',()=>{startingOpponents=Number(b.dataset.startingOpponents);renderStarting();})); }
function renderMatrix() { $("#starting-matrix").innerHTML = MATRIX_RANKS.flatMap((_,r)=>MATRIX_RANKS.map((__,c)=>{const key=handKey(r,c),data=PREFLOP_DATA[key];return `<button type="button" class="starting-cell ${key===selectedStarting?"is-selected":""}" data-starting-hand="${key}" title="${key}: ${formatPercent(data.equity[startingOpponents-1])}"><strong>${key}</strong><span>${formatPercent(data.equity[startingOpponents-1]).replace(" %","")}</span></button>`;})).join(""); $$('[data-starting-hand]').forEach((b)=>b.addEventListener('click',()=>{selectedStarting=b.dataset.startingHand;startingCards=representativeCards(selectedStarting);renderStarting();})); }
function renderStartingDetail() { if(!selectedStarting){$("#starting-detail").innerHTML=`<p class="helper-copy">Wähle oben zwei Handkarten oder tippe eine Handklasse in der Matrix an. Danach erscheinen Equity, Rang und Häufigkeit.</p>`;return;} const data=PREFLOP_DATA[selectedStarting], idx=startingOpponents-1, rank=ranksForOpponents(startingOpponents)[selectedStarting], freq=data.combos/1326; $("#starting-detail").innerHTML=`<div class="surface-head"><div><p class="eyebrow">DEINE STARTHAND</p><h3>${selectedStarting}</h3><p class="helper-copy detail-sub">${handDescription(selectedStarting)}</p></div><span class="soft-badge">${startingOpponents} Gegner</span></div><div class="metric-grid"><div class="metric-card"><span>Equity</span><strong>${formatPercent(data.equity[idx])}</strong><small>erwarteter Pot-Anteil</small></div><div class="metric-card"><span>Rang</span><strong>${rank} / 169</strong><small>für ${startingOpponents} Gegner</small></div><div class="metric-card"><span>Häufigkeit</span><strong>${formatPercent(freq)}</strong><small>${data.combos} von 1.326 Kombinationen</small></div></div><details class="explain"><summary>Was bedeutet Equity?</summary><p>Equity ist dein erwarteter Anteil am Pot, wenn dieselbe Ausgangslage sehr oft ausgespielt würde. Gewinne zählen vollständig, geteilte Pots anteilig. Sie ist keine Garantie für eine einzelne Hand.</p></details><details class="explain"><summary>Wie entsteht der Rang?</summary><p>Alle 169 Starthandklassen werden für genau ${startingOpponents} zufällige Gegner nach ihrer vorberechneten Equity sortiert. Position, vorherige Einsätze, Stacktiefe und Spielstil sind bewusst nicht enthalten. Der Rang ist daher keine Call-/Raise-/Fold-Empfehlung.</p></details><p class="data-note">${PREFLOP_META.method}: ${formatNumber(PREFLOP_META.simulationsPerClass)} vollständige Deals je Handklasse und Gegnerzahl. Die Werte werden statisch ausgeliefert und nicht auf deinem Gerät simuliert.</p>`; }
function renderStarting(){ renderStartingCards(); renderOpponentButtons(); renderStartingDetail(); renderMatrix(); }

renderRankings(); renderChipEditor(); calculateSetup(); renderStarting();
