import {renderTable,renderOverlay} from '../ui.js';
const $=s=>document.querySelector(s);let code=(new URLSearchParams(location.search).get('code')||'').toUpperCase(),state=null,ws=null,retry=null;
function normalizeCode(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)}
function showJoin(message=''){if(ws){ws.close();ws=null}$('#display-view').hidden=true;$('#display-join').hidden=false;$('#display-code').value=code;$('#display-error').textContent=message;setTimeout(()=>$('#display-code').focus(),0)}
function render(){if(!state)return;$('#display-join').hidden=true;$('#display-view').hidden=false;$('#blinds').textContent=`${state.currentBlinds.sb} / ${state.currentBlinds.bb}`;$('#round-label').textContent=`Runde ${Math.min(state.round,state.roundsPerLevel)} von ${state.roundsPerLevel}`;const active=state.players.filter(p=>p.status==='active').length;$('#player-count').textContent=`${active} ${active===1?'Spieler':'Spieler'} · Hand ${state.hand}`;$('#next-blinds').textContent=state.nextBlinds?`${state.nextBlinds.sb} / ${state.nextBlinds.bb}`:'–';renderTable($('#table'),state);renderDisplayMode();$('#status-banner').innerHTML=state.status==='level-change'?'<div class="live-status display-status"><strong>NEUE BLINDS BEREIT</strong> · Am Controller starten</div>':state.status==='paused'?'<div class="live-status display-status"><strong>PAUSE</strong></div>':'';renderOverlay($('#overlay'),state.overlay);$('#overlay').classList.toggle('ranks-panel',state.overlay==='ranks');document.body.classList.toggle('has-assist',Boolean(state.overlay));}

function renderDisplayMode(){const mode=state.displayMode||'table',minimal=mode==='minimal',broadcast=mode==='broadcast';document.body.classList.toggle('display-minimal',minimal);document.body.classList.toggle('display-broadcast',broadcast);$('#table').hidden=minimal||broadcast;$('#minimal-board').hidden=!minimal;$('#broadcast-board').hidden=!broadcast;const active=state.players.filter(p=>p.status==='active');if(broadcast){$('#broadcast-blinds').textContent=`${state.currentBlinds.sb} / ${state.currentBlinds.bb}`;$('#broadcast-round').textContent=`${Math.min(state.round,state.roundsPerLevel)} / ${state.roundsPerLevel}`;$('#broadcast-next').textContent=state.nextBlinds?`${state.nextBlinds.sb} / ${state.nextBlinds.bb}`:'–';$('#broadcast-count').textContent=String(active.length);renderTable($('#broadcast-table'),state);return}if(!minimal)return;const bySeat=seat=>state.players.find(p=>p.seat===seat);const buttonPlayer=bySeat(state.buttonSeat),sbPlayer=bySeat(state.smallBlindSeat),bbPlayer=bySeat(state.bigBlindSeat);const roles=[['D',buttonPlayer&&buttonPlayer.status==='active'?buttonPlayer.name:`Dead Button · Sitz ${state.buttonSeat}`],['SB',sbPlayer&&sbPlayer.status==='active'?sbPlayer.name:'kein Small Blind'],['BB',bbPlayer?bbPlayer.name:'–']];$('#minimal-roles').innerHTML=roles.map(([role,label])=>`<div class="minimal-role role-${role.toLowerCase()}"><span>${role}</span><strong>${escapeHtml(label)}</strong></div>`).join('');$('#minimal-players').textContent=active.map(p=>p.name).join(' · ');}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function connect(){clearTimeout(retry);if(ws)ws.close();const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/x/poker/live/api/sessions/${code}/ws`);let received=false;ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.state){received=true;state=d.state;history.replaceState(null,'',`?code=${code}`);render()}};ws.onerror=()=>{};ws.onclose=()=>{if(received&&code)retry=setTimeout(connect,1800);else showJoin('Session nicht gefunden. Prüfe den Display-Code.');};}
function submit(){code=normalizeCode($('#display-code').value);$('#display-code').value=code;if(code.length!==6){$('#display-error').textContent='Der Display-Code hat 6 Zeichen.';return}$('#display-error').textContent='Verbindung wird hergestellt …';connect()}
$('#display-code').addEventListener('input',e=>{e.target.value=normalizeCode(e.target.value)});$('#display-code').addEventListener('keydown',e=>{if(e.key==='Enter')submit()});$('#display-connect').addEventListener('click',submit);if(code.length===6)connect();else showJoin();
