import { RANKS, SUITS, analyzeDraws, cardLabel, describePartialHand, parseCard, canonicalStartingHand } from "../poker-engine.js";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const formatNumber=(v)=>{try{return BigInt(v).toLocaleString("de-DE");}catch{return Number(v).toLocaleString("de-DE",{maximumFractionDigits:0});}};
const formatPercent=(v)=>`${(Number(v||0)*100).toFixed(1).replace(".",",")} %`;
function suitMeta(card){const p=parseCard(card);return p?SUITS.find(s=>s.key===p.suit):null;}
function metricCard(l,v){return `<div class="metric-card"><span>${l}</span><strong>${v}</strong></div>`;}
const oddsState={hero:[null,null],board:[null,null,null,null,null],opponentCount:1,opponents:Array.from({length:8},()=>[null,null]),pickerTarget:null,pickerRank:null,pickerSuit:null,calculationToken:0,lastResult:null};
const worker=new Worker(new URL("../odds-worker.js",import.meta.url),{type:"module"});
function targetValue(t){if(!t)return null;if(t.type==="hero")return oddsState.hero[t.index];if(t.type==="board")return oddsState.board[t.index];return oddsState.opponents[t.opponentIndex][t.index];}
function setTargetValue(t,v){if(t.type==="hero")oddsState.hero[t.index]=v;else if(t.type==="board")oddsState.board[t.index]=v;else oddsState.opponents[t.opponentIndex][t.index]=v;}
function allSelectedCards({excludeTarget=null}={}){const a=[];oddsState.hero.forEach((c,i)=>{if(c&&!(excludeTarget?.type==="hero"&&excludeTarget.index===i))a.push(c)});oddsState.board.forEach((c,i)=>{if(c&&!(excludeTarget?.type==="board"&&excludeTarget.index===i))a.push(c)});oddsState.opponents.slice(0,oddsState.opponentCount).forEach((h,oi)=>h.forEach((c,i)=>{if(c&&!(excludeTarget?.type==="opponent"&&excludeTarget.opponentIndex===oi&&excludeTarget.index===i))a.push(c)}));return a;}
function slotHtml(card,label,target){const p=parseCard(card),s=card?suitMeta(card):null,d=encodeURIComponent(JSON.stringify(target));return p?`<button class="card-slot filled ${s?.color==="red"?"red":""}" type="button" data-card-target="${d}"><span><span class="card-rank">${p.rank}</span><span class="card-suit">${s?.symbol}</span></span></button>`:`<button class="card-slot" type="button" data-card-target="${d}"><span><span class="slot-plus">+</span><span class="slot-label">${label}</span></span></button>`;}
function bindCardSlots(){$$('[data-card-target]').forEach(b=>b.addEventListener('click',()=>openCardPicker(JSON.parse(decodeURIComponent(b.dataset.cardTarget)))));}
function renderOpponentRows(){$("#opponent-card-rows").innerHTML=Array.from({length:oddsState.opponentCount},(_,oi)=>`<div class="opponent-card-row"><span>Gegner ${oi+1}</span>${oddsState.opponents[oi].map((c,i)=>slotHtml(c,`Karte ${i+1}`,{type:"opponent",opponentIndex:oi,index:i})).join("")}</div>`).join("");}
function renderCards(){$("#hero-slots").innerHTML=oddsState.hero.map((c,i)=>slotHtml(c,`Hand ${i+1}`,{type:"hero",index:i})).join("");$("#board-slots").innerHTML=oddsState.board.map((c,i)=>slotHtml(c,["Flop 1","Flop 2","Flop 3","Turn","River"][i],{type:"board",index:i})).join("");renderOpponentRows();bindCardSlots();const h=oddsState.hero.filter(Boolean);$("#preflop-notation").textContent=h.length===2?canonicalStartingHand(h):"2 Karten wählen";}
function openCardPicker(target){oddsState.pickerTarget=target;const p=parseCard(targetValue(target));oddsState.pickerRank=p?.rank||null;oddsState.pickerSuit=p?.suit||null;renderPicker();$("#card-picker").showModal();}
function maybeCommitPicker(){if(!oddsState.pickerRank||!oddsState.pickerSuit)return;const card=`${oddsState.pickerRank}${oddsState.pickerSuit}`;if(new Set(allSelectedCards({excludeTarget:oddsState.pickerTarget})).has(card))return;setTargetValue(oddsState.pickerTarget,card);$("#card-picker").close();afterCardsChanged();}
function renderPicker(){const used=new Set(allSelectedCards({excludeTarget:oddsState.pickerTarget}));$("#picker-title").textContent=`${oddsState.pickerRank||"Rang"} · ${SUITS.find(s=>s.key===oddsState.pickerSuit)?.name||"Farbe"}`;$("#rank-picker").innerHTML=RANKS.map(r=>{const card=oddsState.pickerSuit?`${r}${oddsState.pickerSuit}`:null;return `<button type="button" class="rank-choice ${oddsState.pickerRank===r?"is-active":""}" data-rank="${r}" ${card&&used.has(card)?"disabled":""}>${r}</button>`;}).join("");$$('.rank-choice').forEach(b=>b.addEventListener('click',()=>{oddsState.pickerRank=b.dataset.rank;maybeCommitPicker();if($("#card-picker").open)renderPicker();}));$("#suit-picker").innerHTML=SUITS.map(s=>{const card=oddsState.pickerRank?`${oddsState.pickerRank}${s.key}`:null;return `<button type="button" class="suit-choice ${s.color==="red"?"red":""} ${oddsState.pickerSuit===s.key?"is-active":""}" data-suit="${s.key}" ${card&&used.has(card)?"disabled":""}>${s.symbol}</button>`}).join("");$$('.suit-choice').forEach(b=>b.addEventListener('click',()=>{oddsState.pickerSuit=b.dataset.suit;maybeCommitPicker();if($("#card-picker").open)renderPicker();}));$("#clear-card").disabled=!targetValue(oddsState.pickerTarget);}
$("#picker-close").addEventListener('click',()=>$("#card-picker").close());$("#clear-card").addEventListener('click',()=>{if(oddsState.pickerTarget)setTargetValue(oddsState.pickerTarget,null);$("#card-picker").close();afterCardsChanged();});$("#card-picker").addEventListener('click',e=>{if(e.target===$("#card-picker"))$("#card-picker").close();});$("#clear-board").addEventListener('click',()=>{oddsState.board=[null,null,null,null,null];afterCardsChanged();});
$("#opponent-count").addEventListener('input',e=>{oddsState.opponentCount=Number(e.target.value);$("#opponent-count-label").textContent=String(oddsState.opponentCount);renderCards();calculateOdds();});
function afterCardsChanged(){renderCards();calculateOdds();}
function validBoardCards(){const s=oddsState.board.filter(Boolean);return [0,3,4,5].includes(s.length)?s:null;}
function calculationPlaceholder(m){$("#odds-placeholder").hidden=false;$("#odds-results").hidden=true;$("#odds-placeholder").innerHTML=`<span class="placeholder-card">%</span><p>${m}</p>`;}
function calculateOdds(){const hero=oddsState.hero.filter(Boolean),board=validBoardCards();oddsState.lastResult=null;if(hero.length!==2){calculationPlaceholder("Wähle beide Handkarten. Danach startet die Berechnung automatisch.");return;}if(!board){calculationPlaceholder("Flop bitte vollständig mit drei Karten wählen; danach sind Turn und River einzeln möglich.");return;}const token=++oddsState.calculationToken,opponents=oddsState.opponents.slice(0,oddsState.opponentCount).map(h=>[...h]);$("#odds-placeholder").hidden=true;$("#odds-results").hidden=false;$("#odds-metrics").innerHTML=[metricCard("Win","…"),metricCard("Tie","…"),metricCard("Loss","…")].join("");$("#calculation-meta").innerHTML=`<span>Berechnung läuft lokal …</span>`;renderHandAnalysis(hero,board);worker.postMessage({type:"calculate",token,hero,board,opponents});}
worker.addEventListener('message',e=>{const r=e.data||{};if(r.token!==oddsState.calculationToken)return;oddsState.lastResult=r;renderOddsResult(r);});
function renderOddsResult(r){$("#odds-metrics").innerHTML=`<div class="metric-card win"><span>Win</span><strong>${formatPercent(r.win)}</strong></div><div class="metric-card"><span>Tie</span><strong>${formatPercent(r.tie)}</strong></div><div class="metric-card loss"><span>Loss</span><strong>${formatPercent(r.loss)}</strong></div><div class="metric-card"><span>Equity</span><strong>${formatPercent(r.equity)}</strong><small>erwarteter Pot-Anteil</small></div>`;const exact=r.mode==="exact",possible=formatNumber(r.estimatedStates),examined=formatNumber(r.iterations);$("#calculation-meta").innerHTML=`<span><strong>${exact?"Exakte Berechnung":"Monte-Carlo-Schätzung"}</strong> · ${examined} ${exact?"von":"untersuchte"} ${possible}${exact?" Zuständen":" möglichen Endzuständen"}</span>`;$("#method-explanation").innerHTML=exact?`<p>Der Zustandsraum ist klein genug: Alle ${possible} möglichen vollständigen Endzustände werden untersucht. Das Ergebnis enthält daher keinen Stichprobenfehler.</p>`:`<p>Es gibt ungefähr ${possible} mögliche vollständige Endzustände. Statt alle durchzurechnen, werden zufällige legale Verläufe gezogen und ausgewertet. Mehr Durchläufe machen die Schätzung stabiler; alles passiert lokal im Browser.</p>`;}
function drawCompletionInfo(hero,board,draws){
  const known=[...hero,...board].filter(Boolean), unseen=52-known.length, outs=new Set();
  if(draws.flushDraw){const parsed=known.map(parseCard),counts={};parsed.forEach(c=>counts[c.suit]=(counts[c.suit]||0)+1);const suit=Object.keys(counts).find(k=>counts[k]===4);if(suit)RANKS.forEach(r=>{const c=`${r}${suit}`;if(!known.includes(c))outs.add(c);});}
  if(draws.straightDraw)draws.straightOutRanks.forEach(rank=>SUITS.forEach(s=>{const c=`${rank}${s.key}`;if(!known.includes(c))outs.add(c);}));
  const n=outs.size, next=n/unseen, cardsToCome=5-board.length;
  const byRiver=cardsToCome>=2&&n?1-((unseen-n)/unseen)*((unseen-n-1)/(unseen-1)):next;
  return {outs:n,next,byRiver,cardsToCome};
}
function renderHandAnalysis(hero,board){const handName=describePartialHand([...hero,...board]),draws=board.length>=3&&board.length<5?analyzeDraws(hero,board):null;const items=[["Aktuelle Hand",handName]];let info=null;if(draws){if(draws.flushDraw)items.push(["Flush","möglich"]);if(draws.straightDraw)items.push(["Straight","möglich"]);info=drawCompletionInfo(hero,board,draws);items.push(["Verbesserungskarten",formatNumber(info.outs)]);items.push(["Nächste Karte",`~${formatPercent(info.next)}`]);if(info.cardsToCome>=2)items.push(["Bis zum River",`~${formatPercent(info.byRiver)}`]);}$("#hand-analysis").innerHTML=`<div class="analysis-grid">${items.map(([l,v])=>`<div class="analysis-pill"><span>${l}</span><strong>${v}</strong></div>`).join("")}</div>${draws?`<p class="analysis-note">Gezählt werden hier Karten, die den angezeigten Flush- oder Straight-Draw vervollständigen. Das sind keine garantierten Gewinnkarten: Ein Gegner kann trotzdem eine bessere Hand halten oder dieselbe Karte ebenfalls nutzen.</p>`:""}`;}

renderCards();calculateOdds();
