'use strict';
const EMOJI_RE=/\p{Extended_Pictographic}/u, URL_RE=/https?:\/\/[^\s<>]+|www\.[^\s<>]+/giu;
const STOP=new Set('aber alle allem allen aller alles als also am an andere anderen anderer anderes auch auf aus bei bin bis bist da damit dann das dass dein deine dem den denn der des die dies diese doch dort du durch ein eine einem einen einer eines er es etwas für gegen gewesen hat hatte haben hier hin hinter ich im in ist ja jede jedem jeden jeder jedes jener jenes jetzt kann kein keine mit muss nach nicht nichts noch nun nur ob oder ohne sehr sein seine selbst sich sie sind so solche um und uns unser unter vom von vor war waren warst was weg weil weiter welche welcher welches wenn werde werden wie wieder will wir wird wo zu zum zur über'.split(' '));
self.onmessage=e=>{const m=e.data||{};try{if(m.type==='inspect')postMessage({type:'inspected',requestId:m.requestId,data:m.files.map(f=>inspect(f))});else if(m.type==='build')postMessage({type:'built',requestId:m.requestId,data:build(m.files,m.config)});else if(m.type==='metrics')postMessage({type:'metrics',requestId:m.requestId,data:metrics(dataset,m.range)});else if(m.type==='clear'){dataset=null;postMessage({type:'cleared'})}}catch(err){postMessage({type:'error',requestId:m.requestId,message:err?.message||String(err)})}};
let dataset=null;
function clean(s){return String(s||'').replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').trimEnd()}
function header(line){line=clean(line);let m=line.match(/^\[(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4}),?\s+(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\s*([AP]M))?\]\s*(.*)$/i);if(!m)m=line.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4}),?\s+(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\s*([AP]M))?\s+-\s+(.*)$/i);return m?{a:+m[1],b:+m[2],y:+m[3],h:+m[4],min:+m[5],sec:+(m[6]||0),ampm:m[7],rest:m[8],sample:line}:null}
function order(headers,forced){if(forced)return{value:forced,ambiguous:false};let d=0,mo=0;for(const h of headers){if(h.a>12&&h.b<=12)d++;if(h.b>12&&h.a<=12)mo++}if(d&&!mo)return{value:'DMY',ambiguous:false};if(mo&&!d)return{value:'MDY',ambiguous:false};return{value:'DMY',ambiguous:true}}
function dateOf(h,o){let d=o==='DMY'?h.a:h.b,mo=o==='DMY'?h.b:h.a,y=h.y<100?2000+h.y:h.y,hr=h.h;if(h.ampm){if(/pm/i.test(h.ampm)&&hr<12)hr+=12;if(/am/i.test(h.ampm)&&hr===12)hr=0}const x=new Date(y,mo-1,d,hr,h.min,h.sec);return x.getFullYear()===y&&x.getMonth()===mo-1&&x.getDate()===d?x:null}
function sender(rest){const i=rest.indexOf(': ');if(i<1)return{sender:null,text:rest,system:true};const s=rest.slice(0,i).trim();return !s||s.length>120?{sender:null,text:rest,system:true}:{sender:s,text:rest.slice(i+2),system:false}}
function attachment(text){const t=clean(text).toLowerCase();if(/audio (weggelassen|omitted)|<anhang:.*-audio-|<attached:.*-audio-|\.opus>?$/.test(t))return'audio';if(/bild (weggelassen)|image omitted|foto (weggelassen)|photo omitted|<anhang:.*\.(jpe?g|png|heic|webp)>|<attached:.*\.(jpe?g|png|heic|webp)>/.test(t))return'image';if(/video (weggelassen|omitted)|<anhang:.*\.(mp4|mov|m4v)>|<attached:.*\.(mp4|mov|m4v)>/.test(t))return'video';if(/dokument (weggelassen)|document omitted|<anhang:|<attached:/.test(t))return'document';if(/medien (weggelassen)|media omitted/.test(t))return'media';return null}
function parse(text,forced){const lines=String(text).replace(/^\ufeff/,'').split(/\r?\n/),hs=lines.map(header).filter(Boolean);if(!hs.length)throw Error('Keine unterstützten WhatsApp-Nachrichten erkannt.');const ord=order(hs,forced),messages=[];let cur=null;for(const raw of lines){const h=header(raw);if(h){if(cur)messages.push(cur);const d=dateOf(h,ord.value),s=sender(h.rest);cur=d?{dateMs:d.getTime(),sender:s.sender,text:clean(s.text),system:s.system,attachment:attachment(s.text)}:null}else if(cur)cur.text+='\n'+clean(raw)}if(cur)messages.push(cur);messages.sort((a,b)=>a.dateMs-b.dateMs);const people=[...new Set(messages.filter(x=>!x.system&&x.sender).map(x=>x.sender))];return{messages,people,order:ord.value,ambiguous:ord.ambiguous&&!forced,example:hs.find(h=>h.a<=12&&h.b<=12)?.sample||''}}
function fingerprint(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)+':'+text.length}
function inspect(f){const p=parse(f.text,null),u=p.messages.filter(x=>!x.system);return{id:f.id,name:f.name,size:f.text.length,fingerprint:fingerprint(f.text),participants:p.people,total:u.length,first:u[0]?.dateMs||null,last:u.at(-1)?.dateMs||null,ambiguous:p.ambiguous,dateOrder:p.order,example:p.example}}
function normText(s){return clean(s).toLocaleLowerCase().replace(/\s+/g,' ').trim()}
function build(files,config){const parsed=files.map(f=>{const c=config[f.id];if(!c?.me)throw Error('Bitte deine Identität für jede Datei bestätigen.');const p=parse(f.text,c.dateOrder);const others=p.people.filter(x=>x!==c.me).sort((a,b)=>a.localeCompare(b,'de'));const chat=others.length?others.join(' · '):'Chat ohne weitere erkannte Person';return{...f,p,me:c.me,chat,fingerprint:fingerprint(f.text)}});const whole=new Map(),wholeDuplicates=[];for(const f of parsed){if(whole.has(f.fingerprint))wholeDuplicates.push({file:f.name,duplicateOf:whole.get(f.fingerprint).name});else whole.set(f.fingerprint,f)}const seen=new Map(),messages=[],duplicateRecords=[];let duplicateRecordCount=0;const fileStats=[];for(const f of parsed){let unique=0,dups=0;for(const m of f.p.messages){if(m.system||!m.sender)continue;const who=m.sender===f.me?'Ich':m.sender;const type=m.attachment||'text';const normalized=normText(m.text),key=[f.chat,m.dateMs,who,type,normalized].join('\u241f');if(seen.has(key)){dups++;duplicateRecordCount++;if(duplicateRecords.length<500){const first=seen.get(key);duplicateRecords.push({file:f.name,duplicateOf:first.file,chat:f.chat,dateMs:m.dateMs,sender:who,type,preview:normalized.slice(0,140)})}continue}seen.set(key,{file:f.name});unique++;messages.push({...m,sender:who,chat:f.chat,source:f.name})}fileStats.push({name:f.name,chat:f.chat,total:f.p.messages.filter(x=>!x.system&&x.sender).length,unique,duplicates:dups,first:f.p.messages.find(x=>!x.system&&x.sender)?.dateMs||null,last:[...f.p.messages].reverse().find(x=>!x.system&&x.sender)?.dateMs||null})}messages.sort((a,b)=>a.dateMs-b.dateMs);const overlaps=[];for(let i=0;i<fileStats.length;i++)for(let j=i+1;j<fileStats.length;j++){const a=fileStats[i],b=fileStats[j];if(a.chat!==b.chat||!a.first||!b.first)continue;const start=Math.max(a.first,b.first),end=Math.min(a.last,b.last);if(start<=end)overlaps.push({chat:a.chat,a:a.name,b:b.name,start,end,exactDuplicates:a.duplicates+b.duplicates,note:(a.duplicates+b.duplicates)>0?'Exakte doppelte Nachrichten wurden entfernt.':'Datumsbereiche überlappen; ohne exakte Übereinstimmung wurde nichts entfernt.'})}dataset={messages,fileStats,overlaps,wholeDuplicates,first:messages[0]?.dateMs||null,last:messages.at(-1)?.dateMs||null};return{summary:{files:files.length,chats:new Set(fileStats.map(x=>x.chat)).size,records:fileStats.reduce((s,x)=>s+x.total,0),unique:messages.length,duplicates:duplicateRecordCount,first:dataset.first,last:dataset.last},fileStats,overlaps,wholeDuplicates,duplicateRecords,duplicateRecordsTruncated:duplicateRecordCount>duplicateRecords.length,metrics:metrics(dataset,null)}}
function month(ms){const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function day(ms){const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function toks(s){return(normText(s).match(/[\p{L}\p{N}][\p{L}\p{N}'’_-]*/gu)||[]).filter(x=>x.length>1)}
function ems(s){if(Intl.Segmenter){const seg=new Intl.Segmenter(undefined,{granularity:'grapheme'});return[...seg.segment(s)].map(x=>x.segment).filter(x=>EMOJI_RE.test(x))}return Array.from(s).filter(x=>EMOJI_RE.test(x))}
function inc(m,k,n=1){m.set(k,(m.get(k)||0)+n)}function top(m,n=15){return[...m].sort((a,b)=>b[1]-a[1]).slice(0,n).map(([label,value])=>({label,value}))}function median(a){if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2}
function styleSnapshot(messages){const emoji=new Map(),words=new Map(),phrases=new Map();let totalWords=0;for(const m of messages){if(m.attachment)continue;const ts=toks(m.text);totalWords+=ts.length;for(const e of ems(m.text))inc(emoji,e);const filtered=ts.filter(w=>!STOP.has(w)&&!/^\d+$/.test(w));for(const w of filtered)inc(words,w);for(let i=0;i<filtered.length-1;i++)inc(phrases,filtered.slice(i,i+2).join(' '))}return{messages:messages.length,totalWords,emoji,words,phrases}}
function trendRows(all,earlier,later,kind,limit,scale,type){const a=all[kind],e=earlier[kind],l=later[kind],denAll=kind==='emoji'?all.messages:all.totalWords,denE=kind==='emoji'?earlier.messages:earlier.totalWords,denL=kind==='emoji'?later.messages:later.totalWords;return top(a,limit).map(x=>({label:x.label,type,rate:denAll?x.value/denAll*scale:0,earlier:denE?(e.get(x.label)||0)/denE*scale:0,later:denL?(l.get(x.label)||0)/denL*scale:0}))}
function metrics(ds,range){if(!ds)return null;const start=range?.start?new Date(range.start+'T00:00:00').getTime():-Infinity,end=range?.end?new Date(range.end+'T23:59:59.999').getTime():Infinity;const mine=ds.messages.filter(m=>m.sender==='Ich'&&m.dateMs>=start&&m.dateMs<=end),months=new Map(),monthLengths=new Map(),monthChats=new Map(),days=new Map(),hours=Array(24).fill(0),weekdays=Array(7).fill(0),yearHour=new Map(),chatCounts=new Map(),chatMonth=new Map();let questions=0,links=0,attachments=0,textMessages=0;for(const m of mine){const mo=month(m.dateMs),dy=day(m.dateMs),d=new Date(m.dateMs);inc(months,mo);inc(days,dy);hours[d.getHours()]++;weekdays[d.getDay()]++;if(!yearHour.has(d.getFullYear()))yearHour.set(d.getFullYear(),Array(24).fill(0));yearHour.get(d.getFullYear())[d.getHours()]++;inc(chatCounts,m.chat);if(!monthChats.has(mo))monthChats.set(mo,new Set());monthChats.get(mo).add(m.chat);if(!chatMonth.has(mo))chatMonth.set(mo,new Map());inc(chatMonth.get(mo),m.chat);if(m.attachment){attachments++;continue}textMessages++;if(m.text.trim().endsWith('?'))questions++;links+=(m.text.match(URL_RE)||[]).length}const series=[...months].sort().map(([label,value])=>({label,value})),lengthSeries=[...monthLengths].sort().map(([label,a])=>({label,value:median(a)})),activeSeries=[...monthChats].sort().map(([label,s])=>({label,value:s.size}));
// Fill message lengths separately so attachment placeholders stay excluded.
for(const m of mine){if(m.attachment)continue;const mo=month(m.dateMs);if(!monthLengths.has(mo))monthLengths.set(mo,[]);monthLengths.get(mo).push(m.text.length)}
const fixedLengthSeries=[...monthLengths].sort().map(([label,a])=>({label,value:median(a)}));const first=mine[0]?.dateMs||null,last=mine.at(-1)?.dateMs||null,mid=first&&last?first+(last-first)/2:null,earlyMessages=mid?mine.filter(m=>m.dateMs<=mid):[],lateMessages=mid?mine.filter(m=>m.dateMs>mid):[],allStyle=styleSnapshot(mine),earlyStyle=styleSnapshot(earlyMessages),lateStyle=styleSnapshot(lateMessages);const emojiTrend=trendRows(allStyle,earlyStyle,lateStyle,'emoji',12,1000,null),wordTrend=trendRows(allStyle,earlyStyle,lateStyle,'words',10,10000,'Wort'),phraseTrend=trendRows(allStyle,earlyStyle,lateStyle,'phrases',8,10000,'Phrase');return{count:mine.length,activeDays:days.size,messagesPerActiveDay:days.size?mine.length/days.size:0,textMessages,questions,links,attachments,series,lengthSeries:fixedLengthSeries,activeSeries,hours,weekdays,yearHour:[...yearHour].sort((a,b)=>a[0]-b[0]).map(([year,values])=>({year,values})),emojiTrend,languageTrend:[...wordTrend,...phraseTrend].sort((a,b)=>b.rate-a.rate).slice(0,15),chatCounts:top(chatCounts,30),chatMonth:[...chatMonth].sort().map(([label,map])=>({label,values:[...map].sort((a,b)=>b[1]-a[1]).map(([chat,value])=>({chat,value}))})),first,last}}
