'use strict';
const $=s=>document.querySelector(s), filesEl=$('#files'), views=['#import-view','#loading','#review','#dashboard'];let worker,rawFiles=[],inspection=[],built=null,autoMe=null,req=0,pending=new Map(),lastMetrics=null,chatTimeMode='month',activityMode='month';
function show(id){views.forEach(v=>$(v).hidden=v!==id)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(ms){return ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(ms)):'–'}function num(n,d=0){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:d}).format(n||0)}
function shortSeriesLabel(v){if(/^\d{4}-\d{2}-\d{2}$/.test(v)){const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit'}).format(d)}if(/^\d{4}-\d{2}$/.test(v))return new Intl.DateTimeFormat('de-DE',{month:'short',year:'2-digit'}).format(new Date(v+'-01T12:00:00'));return v}
function seriesTooltipLabel(v){if(/^\d{4}-\d{2}-\d{2}$/.test(v))return formatPeriod(v,'day');if(/^\d{4}-\d{2}$/.test(v))return formatPeriod(v,'month');return v}
function startWorker(){worker?.terminate();worker=new Worker('analyzer-worker.js');worker.onmessage=e=>{const m=e.data||{};if(m.requestId&&pending.has(m.requestId)){const p=pending.get(m.requestId);pending.delete(m.requestId);m.type==='error'?p.reject(Error(m.message)):p.resolve(m.data)}else if(m.type==='error')fail(m.message)}}function ask(type,data={}){const requestId=++req;return new Promise((resolve,reject)=>{pending.set(requestId,{resolve,reject});worker.postMessage({type,requestId,...data})})}function fail(msg){show('#import-view');$('#import-error').hidden=false;$('#import-error').textContent=msg}
filesEl.addEventListener('change',()=>handleFiles([...filesEl.files]));
const drop=$('#file-drop');['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();drop.classList.add('drag')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>handleFiles([...e.dataTransfer.files]));
async function handleFiles(fs){if(!fs.length)return;const bad=fs.find(f=>!f.name.toLowerCase().endsWith('.txt'));if(bad)return fail('Bitte nur WhatsApp-.txt-Exporte auswählen. ZIPs und Medien bleiben außerhalb der Analyse.');try{show('#loading');$('#loading-text').textContent=`${fs.length} Datei${fs.length===1?'':'en'} werden lokal ergänzt · danach ${rawFiles.length+fs.length} insgesamt.`;const offset=rawFiles.length;const added=await Promise.all(fs.map(async(f,i)=>({id:'f'+(offset+i),name:f.name,text:await f.text()})));rawFiles.push(...added);filesEl.value='';
startWorker();inspection=await ask('inspect',{files:rawFiles});autoMe=commonIdentity(inspection);if(autoMe&&inspection.every(f=>!f.ambiguous)){await buildWithConfig(Object.fromEntries(inspection.map(f=>[f.id,{me:autoMe,dateOrder:f.dateOrder}])));return}renderReview();show('#review')}catch(e){fail(e.message)}}
function commonIdentity(files){if(!files.length)return null;let common=new Set(files[0].participants);for(const f of files.slice(1))common=new Set([...common].filter(name=>f.participants.includes(name)));return common.size===1?[...common][0]:null}
function renderReview(){$('#file-review').innerHTML=inspection.map(f=>`<article class="file-card" data-id="${esc(f.id)}"><header><div><strong>${esc(f.name)}</strong><div class="meta">${num(f.total)} Nachrichten · ${fmt(f.first)}–${fmt(f.last)}</div></div><span class="meta">${f.participants.length} Person${f.participants.length===1?'':'en'}</span></header><div class="identity-row">${autoMe?`<label>Als „Ich“ erkannt<div class="identity-fixed">${esc(autoMe)}</div><input class="me" type="hidden" value="${esc(autoMe)}"></label>`:`<label>Wer bist du?<select class="me"><option value="">Bitte bestätigen …</option>${f.participants.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label>`}${f.ambiguous?`<label>Datumsformat<select class="date"><option value="">Bitte bestätigen …</option><option value="DMY">Tag / Monat / Jahr</option><option value="MDY">Monat / Tag / Jahr</option></select><small class="meta">Beispiel: ${esc(f.example)}</small></label>`:`<label>Datumsformat<input value="${f.dateOrder==='DMY'?'Tag / Monat / Jahr':'Monat / Tag / Jahr'}" disabled><input class="date" type="hidden" value="${f.dateOrder}"></label>`}</div></article>`).join('')}
$('#review-back').onclick=reset;$('#clear').onclick=reset;function reset(){worker?.terminate();worker=null;rawFiles=[];inspection=[];built=null;autoMe=null;filesEl.value='';show('#import-view')}
$('#analyze').onclick=async()=>{const config={},cards=[...document.querySelectorAll('.file-card')];for(const c of cards){const me=c.querySelector('.me').value,dateOrder=c.querySelector('.date').value;if(!me||!dateOrder){$('#review-error').hidden=false;$('#review-error').textContent='Bitte die noch mehrdeutigen Angaben bestätigen.';return}config[c.dataset.id]={me,dateOrder}}$('#review-error').hidden=true;await buildWithConfig(config)};
async function buildWithConfig(config){try{show('#loading');$('#loading-text').textContent=autoMe?`„${autoMe}“ wurde in allen Exporten erkannt. Chats werden lokal zusammengeführt.`:'Chats werden lokal zusammengeführt und exakt dedupliziert.';built=await ask('build',{files:rawFiles,config});renderImport();renderMetrics(built.metrics);show('#dashboard')}catch(e){if(inspection.length){renderReview();show('#review');$('#review-error').hidden=false;$('#review-error').textContent=e.message}else fail(e.message)}}
function kpi(value,label){return`<div class="kpi"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function renderImport(){const s=built.summary;$('#dash-sub').textContent=`${s.files} Exporte · ${s.chats} erkannte Chats · ${fmt(s.first)}–${fmt(s.last)}`;$('#from').min=$('#to').min=iso(s.first);$('#from').max=$('#to').max=iso(s.last);$('#import-kpis').innerHTML=kpi(num(s.files),'Dateien')+kpi(num(s.chats),'erkannte Chats')+kpi(num(s.unique),'eindeutige Nachrichten')+kpi(num(s.duplicates),'exakte Dubletten entfernt');const items=[...built.wholeDuplicates.map(x=>`<div class="overlap"><strong>Identische Datei</strong><p>${esc(x.file)} entspricht ${esc(x.duplicateOf)}.</p></div>`),...built.overlaps.map(x=>`<div class="overlap"><strong>${esc(x.chat)}</strong><p>${fmt(x.start)}–${fmt(x.end)} · ${esc(x.a)} ↔ ${esc(x.b)}<br>${esc(x.note)}</p></div>`)];const dups=built.duplicateRecords||[],debug=s.duplicates?`<details class="debug-details"><summary>Debugbericht: ${num(s.duplicates)} entfernte exakte Dublette${s.duplicates===1?'':'n'} anzeigen</summary><div class="debug-body"><p class="debug-note">Lokale Diagnose. Angezeigt werden maximal 500 entfernte Datensätze; nichts davon wird gespeichert oder übertragen.${built.duplicateRecordsTruncated?' Die Liste wurde für die Darstellung gekürzt.':''}</p>${dups.map(x=>`<div class="debug-row"><strong>${esc(x.chat)} · ${fmtDateTime(x.dateMs)}</strong><div>${esc(x.file)} ← bereits aus ${esc(x.duplicateOf)}</div><code>${esc(x.sender)} · ${esc(x.type)}${x.preview?' · '+esc(x.preview):''}</code></div>`).join('')}</div></details>`:'';$('#overlaps').innerHTML=`<h3>Überlappungen & Dubletten</h3>${items.length?items.join(''):'<p class="muted">Keine überlappenden Exportbereiche erkannt.</p>'}${debug}`}
function fmtDateTime(ms){return ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ms)):'–'}
function iso(ms){if(!ms)return'';const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
$('#apply-range').onclick=async()=>{const start=$('#from').value,end=$('#to').value;if(start&&end&&start>end)return;const m=await ask('metrics',{range:{start,end}});$('#range-label').textContent=start||end?`${start||'…'} – ${end||'…'}`:'Gesamter Zeitraum';renderMetrics(m)};$('#all-range').onclick=async()=>{$('#from').value=$('#to').value='';$('#range-label').textContent='Gesamter Zeitraum';renderMetrics(await ask('metrics',{range:null}))};
function activitySeries(m){return activityMode==='day'?m.daySeries:activityMode==='year'?m.yearSeries:m.monthSeries}
function renderMetrics(m){lastMetrics=m;renderActivity(m);drawLine($('#length-chart'),m.lengthSeries,'Median Zeichen');drawLine($('#active-chart'),m.activeSeries,'Aktive Chats');renderHourChart(m.hours);renderWeekdays(m);renderYearHour(m.yearHour);$('#style-kpis').innerHTML=kpi(num(m.messagesPerActiveDay,1),'Nachrichten pro aktivem Tag')+kpi(num(m.questions),'Fragen')+kpi(num(m.links),'Links')+kpi(num(m.attachments),'Anhang-Platzhalter');rateRank($('#emoji'),m.emojiTrend,'1.000');rateRank($('#words'),m.languageTrend,'10.000');const total=m.chatCounts.reduce((s,x)=>s+x.value,0);rank($('#chat-share'),m.chatCounts,x=>`${num(x.value)} · ${num(total?x.value/total*100:0,1)} %`,x=>x.label);renderChatTime()}
function renderActivity(m){drawLine($('#messages-chart'),activitySeries(m),'Nachrichten');$('#activity-unit-label').textContent=activityMode==='day'?'pro Tag':activityMode==='year'?'pro Jahr':'pro Monat';const dayText=m.activeDay?`${formatPeriod(m.activeDay.label,'day')} · ${num(m.activeDay.value)}`:'–',monthText=m.activeMonth?`${formatPeriod(m.activeMonth.label,'month')} · ${num(m.activeMonth.value)}`:'–',yearText=m.activeYear?`${m.activeYear.label} · ${num(m.activeYear.value)}`:'–';$('#activity-records').innerHTML=`<div class="record"><span>Aktivster Tag</span><strong>${esc(dayText)}</strong></div><div class="record"><span>Aktivster Monat</span><strong>${esc(monthText)}</strong></div><div class="record"><span>Aktivstes Jahr</span><strong>${esc(yearText)}</strong></div><div class="record"><span>Längste tägliche Serie</span><strong>${num(m.longestStreak)} Tage</strong><small>${m.streakStart&&m.streakEnd?fmt(m.streakStart)+' – '+fmt(m.streakEnd):'–'}</small></div><div class="record"><span>Längste Pause</span><strong>${num(m.longestPause)} Tage</strong><small>${m.pauseStart&&m.pauseEnd?fmt(m.pauseStart)+' – '+fmt(m.pauseEnd):'–'}</small></div>`}
function formatPeriod(v,mode){if(mode==='day')return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v+'T12:00:00'));if(mode==='month')return new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date(v+'-01T12:00:00'));return v}
function setActivityMode(mode){activityMode=mode;['day','month','year'].forEach(x=>$('#activity-'+x).classList.toggle('active',x===mode));if(lastMetrics)renderActivity(lastMetrics)}
$('#activity-day').onclick=()=>setActivityMode('day');$('#activity-month').onclick=()=>setActivityMode('month');$('#activity-year').onclick=()=>setActivityMode('year');
function bars(el,data){const max=Math.max(1,...data.map(x=>x.value));el.innerHTML=data.map(x=>`<div class="barrow"><span>${esc(x.label)}</span><div class="track"><div class="fill" style="width:${x.value/max*100}%"></div></div><strong>${num(x.value)}</strong></div>`).join('')}
function rank(el,data,val,label){el.innerHTML=data.length?data.map(x=>`<div class="rankrow"><span>${esc(label(x))}</span><strong>${esc(val(x))}</strong></div>`).join(''):'<p class="muted">Keine Daten im Zeitraum.</p>'}
function rateRank(el,data,unit){el.innerHTML=data.length?data.map(x=>`<div class="rankrow"><span>${esc(x.label)}${x.type?` · ${esc(x.type)}`:''}</span><strong>${num(x.rate,1)} / ${unit}</strong></div>`).join(''):'<p class="muted">Keine Daten im Zeitraum.</p>'}
function renderWeekdays(m){const names=['So','Mo','Di','Mi','Do','Fr','Sa'],occ=weekdayOccurrences(m),avgs=m.weekdays.map((v,i)=>occ[i]?v/occ[i]:0),max=Math.max(1,...avgs),total=m.weekdays.reduce((a,b)=>a+b,0);$('#weekday-chart').innerHTML=[1,2,3,4,5,6,0].map(i=>`<div class="hbar weekday-row"><span>${names[i]}</span><div class="track"><div class="fill" style="width:${avgs[i]/max*100}%"></div></div><strong><span>Ø ${num(avgs[i],1)}</span><small>${num(m.weekdays[i])} · ${total?num(m.weekdays[i]/total*100,1):0}%</small></strong></div>`).join('')}
function weekdayOccurrences(m){const out=Array(7).fill(0);if(!m.first||!m.last)return out;const a=new Date(m.first),b=new Date(m.last);a.setHours(12,0,0,0);b.setHours(12,0,0,0);for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))out[d.getDay()]++;return out}
function renderHourChart(hours){const svg=$('#hour-chart'),w=720,h=245,pL=48,pR=14,pT=14,pB=34,max=Math.max(1,...hours),plotH=h-pT-pB,barW=(w-pL-pR)/24,total=hours.reduce((a,b)=>a+b,0);let grid='',barsHtml='',labels='';for(let i=0;i<=4;i++){const value=Math.round(max*(4-i)/4),y=pT+plotH*i/4;grid+=`<line class="gridline" x1="${pL}" y1="${y}" x2="${w-pR}" y2="${y}"/><text class="axistext" x="${pL-8}" y="${y+3}" text-anchor="end">${num(value)}</text>`}hours.forEach((v,i)=>{const bh=v/max*plotH,x=pL+i*barW+2,y=pT+plotH-bh;barsHtml+=`<rect class="hour-bar" x="${x}" y="${y}" width="${Math.max(3,barW-4)}" height="${Math.max(v?2:0,bh)}"></rect>`;if(i%3===0)labels+=`<text class="axistext" x="${x+barW/2-2}" y="${h-10}" text-anchor="middle">${String(i).padStart(2,'0')}</text>`});svg.innerHTML=`${grid}${barsHtml}${labels}<g class="hour-focus" visibility="hidden"><line class="focusline" y1="${pT}" y2="${h-pB}"/><circle class="focusdot" r="5"/><rect class="tooltipbg" rx="5" width="235" height="28"/><text class="tooltiptext"></text></g><rect class="chart-hit" x="${pL}" y="${pT}" width="${w-pL-pR}" height="${h-pT-pB}"/>`;const focus=svg.querySelector('.hour-focus'),line=focus.children[0],dot=focus.children[1],box=focus.children[2],text=focus.children[3];function move(ev){const ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(ctm.inverse()),idx=Math.max(0,Math.min(23,Math.floor((p.x-pL)/barW))),v=hours[idx],cx=pL+(idx+.5)*barW,cy=pT+plotH-v/max*plotH,tx=Math.min(w-245,Math.max(5,cx+8));focus.setAttribute('visibility','visible');line.setAttribute('x1',cx);line.setAttribute('x2',cx);dot.setAttribute('cx',cx);dot.setAttribute('cy',cy);box.setAttribute('x',tx);box.setAttribute('y',Math.max(3,cy-38));text.setAttribute('x',tx+8);text.setAttribute('y',Math.max(21,cy-20));text.textContent=`${String(idx).padStart(2,'0')}:00–${String(idx).padStart(2,'0')}:59 · ${num(v)} · ${total?num(v/total*100,1):0} %`}svg.onpointermove=move;svg.onpointerdown=e=>{svg.setPointerCapture?.(e.pointerId);move(e)};svg.onpointerleave=e=>{if(e.pointerType==='mouse')focus.setAttribute('visibility','hidden')}}
function renderYearHour(rows){const root=$('#year-hour');if(!rows.length){root.innerHTML='<p class="muted">Keine Daten.</p>';return}let h='<div class="matrix year-hour-matrix"><span></span>'+Array.from({length:24},(_,i)=>`<span class="matrix-cell head">${i%3===0?String(i).padStart(2,'0'):''}</span>`).join('');for(const r of rows){const rowMax=Math.max(1,...r.values);h+=`<span class="matrix-cell head year-label">${esc(r.year)}</span>`+r.values.map((v,i)=>`<span class="matrix-cell interactive-cell ${v?'level'+Math.min(4,Math.ceil(v/rowMax*4)):''}" data-year="${esc(r.year)}" data-hour="${i}" data-value="${v}" title="${esc(r.year)} · ${String(i).padStart(2,'0')}:00–${String(i).padStart(2,'0')}:59 · ${num(v)} Nachrichten"></span>`).join('')}root.innerHTML=h+'</div>';bindCells(root)}
function bindCells(root){let tip=root.querySelector('.cell-tip');if(!tip){tip=document.createElement('div');tip.className='cell-tip';root.append(tip)}const cells=[...root.querySelectorAll('.interactive-cell')];const show=(cell,e)=>{tip.textContent=`${cell.dataset.year} · ${String(cell.dataset.hour).padStart(2,'0')}:00–${String(cell.dataset.hour).padStart(2,'0')}:59 · ${num(+cell.dataset.value)} Nachrichten`;tip.hidden=false;const rr=root.getBoundingClientRect();tip.style.left=Math.max(6,Math.min(rr.width-tip.offsetWidth-6,e.clientX-rr.left+root.scrollLeft+10))+'px';tip.style.top=Math.max(6,e.clientY-rr.top+root.scrollTop-38)+'px'};cells.forEach(c=>{c.onpointerenter=e=>show(c,e);c.onpointermove=e=>show(c,e);c.onpointerdown=e=>show(c,e)});root.onpointerleave=e=>{if(e.pointerType==='mouse')tip.hidden=true}}
function aggregateYears(rows){const years=new Map();for(const r of rows){const y=r.label.slice(0,4);if(!years.has(y))years.set(y,new Map());const map=years.get(y);for(const x of r.values)map.set(x.chat,(map.get(x.chat)||0)+x.value)}return[...years].sort().map(([label,map])=>({label,values:[...map].sort((a,b)=>b[1]-a[1]).map(([chat,value])=>({chat,value}))}))}
function renderChatTime(){if(!lastMetrics)return;chatTable(chatTimeMode==='year'?aggregateYears(lastMetrics.chatMonth):lastMetrics.chatMonth,chatTimeMode==='year'?'Jahr':'Monat')}
function chatTable(rows,heading){const chats=[...new Set(rows.flatMap(r=>r.values.map(x=>x.chat)))].slice(0,12);let h=`<table><thead><tr><th>${heading}</th>`+chats.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>';for(const r of rows){const map=new Map(r.values.map(x=>[x.chat,x.value])),sum=r.values.reduce((s,x)=>s+x.value,0);h+=`<tr><td>${esc(r.label)}</td>`+chats.map(c=>`<td>${map.has(c)?num(map.get(c))+' · '+num(map.get(c)/sum*100,0)+' %':'–'}</td>`).join('')+'</tr>'}$('#chat-time').innerHTML=h+'</tbody></table>'}
function setChatTimeMode(mode){chatTimeMode=mode;$('#chat-time-month').classList.toggle('active',mode==='month');$('#chat-time-year').classList.toggle('active',mode==='year');renderChatTime()}
$('#chat-time-month').onclick=()=>setChatTimeMode('month');$('#chat-time-year').onclick=()=>setChatTimeMode('year');
function drawLine(svg,data,label){const W=900,H=280,L=54,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B,max=Math.max(1,...data.map(x=>x.value));svg.innerHTML='';if(!data.length){svg.innerHTML='<text x="450" y="140" text-anchor="middle" class="axistext">Keine Daten im Zeitraum</text>';return}for(let i=0;i<=4;i++){const y=T+ih*i/4;svg.insertAdjacentHTML('beforeend',`<line class="gridline" x1="${L}" y1="${y}" x2="${W-R}" y2="${y}"/><text class="axistext" x="${L-8}" y="${y+4}" text-anchor="end">${num(max*(1-i/4),0)}</text>`)}const pts=data.map((d,i)=>({x:L+(data.length===1?iw/2:i*iw/(data.length-1)),y:T+ih-(d.value/max*ih),...d}));svg.insertAdjacentHTML('beforeend',`<path class="series" d="${pts.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')}"/>`);const ticks=[0,Math.floor((data.length-1)/2),data.length-1].filter((v,i,a)=>a.indexOf(v)===i);ticks.forEach(i=>svg.insertAdjacentHTML('beforeend',`<text class="axistext" x="${pts[i].x}" y="${H-12}" text-anchor="middle">${esc(shortSeriesLabel(data[i].label))}</text>`));const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('visibility','hidden');g.innerHTML=`<line class="focusline" y1="${T}" y2="${H-B}"/><circle class="focusdot" r="5"/><rect class="tooltipbg" rx="5" width="190" height="28"/><text class="tooltiptext" y="18"></text>`;svg.append(g);const line=g.children[0],dot=g.children[1],box=g.children[2],text=g.children[3];function move(ev){const ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(ctm.inverse()),idx=Math.max(0,Math.min(pts.length-1,Math.round((p.x-L)/iw*(pts.length-1)))),q=pts[idx],tx=Math.min(W-200,Math.max(8,q.x+10));g.setAttribute('visibility','visible');line.setAttribute('x1',q.x);line.setAttribute('x2',q.x);dot.setAttribute('cx',q.x);dot.setAttribute('cy',q.y);box.setAttribute('x',tx);box.setAttribute('y',Math.max(4,q.y-38));text.setAttribute('x',tx+8);text.setAttribute('y',Math.max(22,q.y-20));text.textContent=`${seriesTooltipLabel(q.label)} · ${num(q.value,1)} ${label}`}
svg.onpointermove=move;svg.onpointerdown=e=>{svg.setPointerCapture?.(e.pointerId);move(e)};svg.onpointerleave=e=>{if(e.pointerType==='mouse')g.setAttribute('visibility','hidden')}}
startWorker();
