'use strict';
const $=s=>document.querySelector(s), filesEl=$('#files'), views=['#import-view','#loading','#review','#dashboard'];let worker,rawFiles=[],inspection=[],built=null,autoMe=null,req=0,pending=new Map();
function show(id){views.forEach(v=>$(v).hidden=v!==id)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(ms){return ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(ms)):'–'}function num(n,d=0){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:d}).format(n||0)}
function startWorker(){worker?.terminate();worker=new Worker('analyzer-worker.js');worker.onmessage=e=>{const m=e.data||{};if(m.requestId&&pending.has(m.requestId)){const p=pending.get(m.requestId);pending.delete(m.requestId);m.type==='error'?p.reject(Error(m.message)):p.resolve(m.data)}else if(m.type==='error')fail(m.message)}}function ask(type,data={}){const requestId=++req;return new Promise((resolve,reject)=>{pending.set(requestId,{resolve,reject});worker.postMessage({type,requestId,...data})})}function fail(msg){show('#import-view');$('#import-error').hidden=false;$('#import-error').textContent=msg}
filesEl.addEventListener('change',async()=>{const fs=[...filesEl.files];if(!fs.length)return;const bad=fs.find(f=>!f.name.toLowerCase().endsWith('.txt'));if(bad)return fail('Bitte nur WhatsApp-.txt-Exporte auswählen. ZIPs und Medien bleiben außerhalb der Analyse.');try{show('#loading');$('#loading-text').textContent=`${fs.length} Datei${fs.length===1?'':'en'} werden lokal gelesen.`;rawFiles=await Promise.all(fs.map(async(f,i)=>({id:'f'+i,name:f.name,text:await f.text()})));startWorker();inspection=await ask('inspect',{files:rawFiles});autoMe=commonIdentity(inspection);if(autoMe&&inspection.every(f=>!f.ambiguous)){await buildWithConfig(Object.fromEntries(inspection.map(f=>[f.id,{me:autoMe,dateOrder:f.dateOrder}])));return}renderReview();show('#review')}catch(e){fail(e.message)}});
function commonIdentity(files){if(!files.length)return null;let common=new Set(files[0].participants);for(const f of files.slice(1))common=new Set([...common].filter(name=>f.participants.includes(name)));return common.size===1?[...common][0]:null}
function renderReview(){$('#file-review').innerHTML=inspection.map(f=>`<article class="file-card" data-id="${esc(f.id)}"><header><div><strong>${esc(f.name)}</strong><div class="meta">${num(f.total)} Nachrichten · ${fmt(f.first)}–${fmt(f.last)}</div></div><span class="meta">${f.participants.length} Person${f.participants.length===1?'':'en'}</span></header><div class="identity-row">${autoMe?`<label>Als „Ich“ erkannt<div class="identity-fixed">${esc(autoMe)}</div><input class="me" type="hidden" value="${esc(autoMe)}"></label>`:`<label>Wer bist du?<select class="me"><option value="">Bitte bestätigen …</option>${f.participants.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label>`}${f.ambiguous?`<label>Datumsformat<select class="date"><option value="">Bitte bestätigen …</option><option value="DMY">Tag / Monat / Jahr</option><option value="MDY">Monat / Tag / Jahr</option></select><small class="meta">Beispiel: ${esc(f.example)}</small></label>`:`<label>Datumsformat<input value="${f.dateOrder==='DMY'?'Tag / Monat / Jahr':'Monat / Tag / Jahr'}" disabled><input class="date" type="hidden" value="${f.dateOrder}"></label>`}</div></article>`).join('')}
$('#review-back').onclick=reset;$('#clear').onclick=reset;function reset(){worker?.terminate();worker=null;rawFiles=[];inspection=[];built=null;autoMe=null;filesEl.value='';show('#import-view')}
$('#analyze').onclick=async()=>{const config={},cards=[...document.querySelectorAll('.file-card')];for(const c of cards){const me=c.querySelector('.me').value,dateOrder=c.querySelector('.date').value;if(!me||!dateOrder){$('#review-error').hidden=false;$('#review-error').textContent='Bitte die noch mehrdeutigen Angaben bestätigen.';return}config[c.dataset.id]={me,dateOrder}}$('#review-error').hidden=true;await buildWithConfig(config)};
async function buildWithConfig(config){try{show('#loading');$('#loading-text').textContent=autoMe?`„${autoMe}“ wurde in allen Exporten erkannt. Chats werden lokal zusammengeführt.`:'Chats werden lokal zusammengeführt und exakt dedupliziert.';built=await ask('build',{files:rawFiles,config});renderImport();renderMetrics(built.metrics);show('#dashboard')}catch(e){if(inspection.length){renderReview();show('#review');$('#review-error').hidden=false;$('#review-error').textContent=e.message}else fail(e.message)}}
function kpi(value,label){return`<div class="kpi"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function renderImport(){const s=built.summary;$('#dash-sub').textContent=`${s.files} Exporte · ${s.chats} erkannte Chats · ${fmt(s.first)}–${fmt(s.last)}`;$('#from').min=$('#to').min=iso(s.first);$('#from').max=$('#to').max=iso(s.last);$('#import-kpis').innerHTML=kpi(num(s.files),'Dateien')+kpi(num(s.chats),'erkannte Chats')+kpi(num(s.unique),'eindeutige Nachrichten')+kpi(num(s.duplicates),'exakte Dubletten entfernt');const items=[...built.wholeDuplicates.map(x=>`<div class="overlap"><strong>Identische Datei</strong><p>${esc(x.file)} entspricht ${esc(x.duplicateOf)}.</p></div>`),...built.overlaps.map(x=>`<div class="overlap"><strong>${esc(x.chat)}</strong><p>${fmt(x.start)}–${fmt(x.end)} · ${esc(x.a)} ↔ ${esc(x.b)}<br>${esc(x.note)}</p></div>`)];const dups=built.duplicateRecords||[],debug=s.duplicates?`<details class="debug-details"><summary>Debugbericht: ${num(s.duplicates)} entfernte exakte Dublette${s.duplicates===1?'':'n'} anzeigen</summary><div class="debug-body"><p class="debug-note">Lokale Diagnose. Angezeigt werden maximal 500 entfernte Datensätze; nichts davon wird gespeichert oder übertragen.${built.duplicateRecordsTruncated?' Die Liste wurde für die Darstellung gekürzt.':''}</p>${dups.map(x=>`<div class="debug-row"><strong>${esc(x.chat)} · ${fmtDateTime(x.dateMs)}</strong><div>${esc(x.file)} ← bereits aus ${esc(x.duplicateOf)}</div><code>${esc(x.sender)} · ${esc(x.type)}${x.preview?' · '+esc(x.preview):''}</code></div>`).join('')}</div></details>`:'';$('#overlaps').innerHTML=`<h3>Überlappungen & Dubletten</h3>${items.length?items.join(''):'<p class="muted">Keine überlappenden Exportbereiche erkannt.</p>'}${debug}`}
function fmtDateTime(ms){return ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ms)):'–'}
function iso(ms){if(!ms)return'';const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
$('#apply-range').onclick=async()=>{const start=$('#from').value,end=$('#to').value;if(start&&end&&start>end)return;const m=await ask('metrics',{range:{start,end}});$('#range-label').textContent=start||end?`${start||'…'} – ${end||'…'}`:'Gesamter Zeitraum';renderMetrics(m)};$('#all-range').onclick=async()=>{$('#from').value=$('#to').value='';$('#range-label').textContent='Gesamter Zeitraum';renderMetrics(await ask('metrics',{range:null}))};
function renderMetrics(m){drawLine($('#messages-chart'),m.series,'Nachrichten');drawLine($('#length-chart'),m.lengthSeries,'Median Zeichen');drawLine($('#active-chart'),m.activeSeries,'Aktive Chats');bars($('#hours'),m.hours.map((v,i)=>({label:String(i).padStart(2,'0')+'h',value:v})));const wd=['So','Mo','Di','Mi','Do','Fr','Sa'];bars($('#weekdays'),m.weekdays.map((v,i)=>({label:wd[i],value:v})));heat(m.yearHour);$('#style-kpis').innerHTML=kpi(num(m.messagesPerActiveDay,1),'Nachrichten pro aktivem Tag')+kpi(num(m.questions),'Fragen')+kpi(num(m.links),'Links')+kpi(num(m.attachments),'Anhang-Platzhalter');rank($('#emoji'),m.emoji,x=>`${num(x.rate,1)} / 1.000`,x=>x.label);rank($('#words'),m.language,x=>`${num(x.rate,1)} / 10k`,x=>`${x.label} · ${x.type}`);const total=m.chatCounts.reduce((s,x)=>s+x.value,0);rank($('#chat-share'),m.chatCounts,x=>`${num(x.value)} · ${num(total?x.value/total*100:0,1)} %`,x=>x.label);chatTable(m.chatMonth)}
function bars(el,data){const max=Math.max(1,...data.map(x=>x.value));el.innerHTML=data.map(x=>`<div class="barrow"><span>${esc(x.label)}</span><div class="track"><div class="fill" style="width:${x.value/max*100}%"></div></div><strong>${num(x.value)}</strong></div>`).join('')}
function rank(el,data,val,label){el.innerHTML=data.length?data.map(x=>`<div class="rankrow"><span>${esc(label(x))}</span><strong>${esc(val(x))}</strong></div>`).join(''):'<p class="muted">Keine Daten im Zeitraum.</p>'}
function heat(rows){const el=$('#year-hour');if(!rows.length){el.innerHTML='<p class="muted">Keine Daten.</p>';return}const max=Math.max(1,...rows.flatMap(r=>r.values));let h=`<div class="heatgrid" style="grid-template-columns:70px repeat(24,1fr)"><span></span>${Array.from({length:24},(_,i)=>`<span class="heatlabel">${i}</span>`).join('')}`;for(const r of rows){h+=`<span class="heatlabel">${r.year}</span>`+r.values.map((v,i)=>`<div class="heatcell" data-v="${v}" title="${r.year} · ${String(i).padStart(2,'0')}:00 · ${v} Nachrichten" style="--level:${v/max}"></div>`).join('')}el.innerHTML=h+'</div>'}
function chatTable(rows){const chats=[...new Set(rows.flatMap(r=>r.values.map(x=>x.chat)))].slice(0,12);let h='<table><thead><tr><th>Monat</th>'+chats.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>';for(const r of rows){const map=new Map(r.values.map(x=>[x.chat,x.value])),sum=r.values.reduce((s,x)=>s+x.value,0);h+=`<tr><td>${esc(r.label)}</td>`+chats.map(c=>`<td>${map.has(c)?num(map.get(c))+' · '+num(map.get(c)/sum*100,0)+' %':'–'}</td>`).join('')+'</tr>'}$('#chat-time').innerHTML=h+'</tbody></table>'}
function drawLine(svg,data,label){const W=900,H=280,L=54,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B,max=Math.max(1,...data.map(x=>x.value));svg.innerHTML='';if(!data.length){svg.innerHTML='<text x="450" y="140" text-anchor="middle" class="axistext">Keine Daten im Zeitraum</text>';return}for(let i=0;i<=4;i++){const y=T+ih*i/4;svg.insertAdjacentHTML('beforeend',`<line class="gridline" x1="${L}" y1="${y}" x2="${W-R}" y2="${y}"/><text class="axistext" x="${L-8}" y="${y+4}" text-anchor="end">${num(max*(1-i/4),0)}</text>`)}const pts=data.map((d,i)=>({x:L+(data.length===1?iw/2:i*iw/(data.length-1)),y:T+ih-(d.value/max*ih),...d}));svg.insertAdjacentHTML('beforeend',`<path class="series" d="${pts.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')}"/>`);const ticks=[0,Math.floor((data.length-1)/2),data.length-1].filter((v,i,a)=>a.indexOf(v)===i);ticks.forEach(i=>svg.insertAdjacentHTML('beforeend',`<text class="axistext" x="${pts[i].x}" y="${H-12}" text-anchor="middle">${esc(data[i].label)}</text>`));const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('visibility','hidden');g.innerHTML=`<line class="focusline" y1="${T}" y2="${H-B}"/><circle class="focusdot" r="5"/><rect class="tooltipbg" rx="5" width="190" height="28"/><text class="tooltiptext" y="18"></text>`;svg.append(g);const line=g.children[0],dot=g.children[1],box=g.children[2],text=g.children[3];function move(ev){const ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(ctm.inverse()),idx=Math.max(0,Math.min(pts.length-1,Math.round((p.x-L)/iw*(pts.length-1)))),q=pts[idx],tx=Math.min(W-200,Math.max(8,q.x+10));g.setAttribute('visibility','visible');line.setAttribute('x1',q.x);line.setAttribute('x2',q.x);dot.setAttribute('cx',q.x);dot.setAttribute('cy',q.y);box.setAttribute('x',tx);box.setAttribute('y',Math.max(4,q.y-38));text.setAttribute('x',tx+8);text.setAttribute('y',Math.max(22,q.y-20));text.textContent=`${q.label} · ${num(q.value,1)} ${label}`}
svg.onpointermove=move;svg.onpointerdown=e=>{svg.setPointerCapture?.(e.pointerId);move(e)};svg.onpointerleave=e=>{if(e.pointerType==='mouse')g.setAttribute('visibility','hidden')}}
startWorker();
