'use strict';
const $=s=>document.querySelector(s), filesEl=$('#files'), views=['#import-view','#loading','#review','#dashboard'];let worker,rawFiles=[],inspection=[],built=null,autoMe=null,req=0,pending=new Map(),lastMetrics=null,chatTimeMode='month',activityMode='month',stopMode='de',sessionGapHours=6,sessionTimeMode='month',currentRange=null,calendarYear=null,aliasCandidates=[];
function show(id){views.forEach(v=>$(v).hidden=v!==id)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(ms){return ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(ms)):'–'}function num(n,d=0){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:d}).format(n||0)}
const STOPWORDS_DE='aber alle allem allen aller alles als also am an andere anderen anderer anderes auch auf aus bei bin bis bist da damit dann das dass dein deine dem den denn der des die dies diese doch dort du durch ein eine einem einen einer eines er es etwas für gegen gewesen hat hatte haben hier hin hinter ich im in ist ja jede jedem jeden jeder jedes jener jenes jetzt kann kein keine mit muss nach nicht nichts noch nun nur ob oder ohne sehr sein seine selbst sich sie sind so solche um und uns unser unter vom von vor war waren warst was weg weil weiter welche welcher welches wenn werde werden wie wieder will wir wird wo zu zum zur über'.split(' ');
const STOPWORDS_EN='a an and are as at be been but by can could did do does for from had has have he her hers him his how i if in into is it its me more my no not of on one or our ours she so than that the their theirs them then there these they this those to too up us was we were what when where which who why will with would you your yours'.split(' ');
function shortSeriesLabel(v){if(/^\d{4}-\d{2}-\d{2}$/.test(v)){const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit'}).format(d)}if(/^\d{4}-\d{2}$/.test(v))return new Intl.DateTimeFormat('de-DE',{month:'short',year:'2-digit'}).format(new Date(v+'-01T12:00:00'));return v}
function seriesTooltipLabel(v){if(/^\d{4}-\d{2}-\d{2}$/.test(v))return formatPeriod(v,'day');if(/^\d{4}-\d{2}$/.test(v))return formatPeriod(v,'month');return v}
function startWorker(){worker?.terminate();worker=new Worker('analyzer-worker.js');worker.onmessage=e=>{const m=e.data||{};if(m.requestId&&pending.has(m.requestId)){const p=pending.get(m.requestId);pending.delete(m.requestId);m.type==='error'?p.reject(Error(m.message)):p.resolve(m.data)}else if(m.type==='error')fail(m.message)}}function ask(type,data={}){const requestId=++req;return new Promise((resolve,reject)=>{pending.set(requestId,{resolve,reject});worker.postMessage({type,requestId,...data})})}function fail(msg){show('#import-view');$('#import-error').hidden=false;$('#import-error').textContent=msg}
filesEl.addEventListener('change',()=>handleFiles([...filesEl.files]));
const drop=$('#file-drop');['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();drop.classList.add('drag')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>handleFiles([...e.dataTransfer.files]));
async function handleFiles(fs){if(!fs.length)return;const bad=fs.find(f=>!f.name.toLowerCase().endsWith('.txt'));if(bad)return fail('Bitte nur WhatsApp-.txt-Exporte auswählen. ZIPs und Medien bleiben außerhalb der Analyse.');try{show('#loading');$('#loading-text').textContent=`${fs.length} Datei${fs.length===1?'':'en'} werden lokal ergänzt · danach ${rawFiles.length+fs.length} insgesamt.`;const offset=rawFiles.length;const added=await Promise.all(fs.map(async(f,i)=>({id:'f'+(offset+i),name:f.name,text:await f.text()})));rawFiles.push(...added);filesEl.value='';
startWorker();inspection=await ask('inspect',{files:rawFiles});autoMe=commonIdentity(inspection);aliasCandidates=findAliasCandidates(inspection);if(autoMe&&inspection.every(f=>!f.ambiguous)&&!aliasCandidates.length){await buildWithConfig(Object.fromEntries(inspection.map(f=>[f.id,{me:autoMe,dateOrder:f.dateOrder}])));return}renderReview();show('#review')}catch(e){fail(e.message)}}
function commonIdentity(files){if(!files.length)return null;let common=new Set(files[0].participants);for(const f of files.slice(1))common=new Set([...common].filter(name=>f.participants.includes(name)));return common.size===1?[...common][0]:null}
function aliasKey(name){return String(name||'').trim().replace(/^~+\s*/, '').replace(/\s+/g,' ').toLocaleLowerCase('de')}
function aliasLabel(names){const clean=names.map(x=>x.trim().replace(/^~+\s*/, '')).filter(Boolean);return clean[0]||names[0]}
function findAliasCandidates(files){const names=[...new Set(files.flatMap(f=>f.participants))],groups=new Map();for(const name of names){const key=aliasKey(name);if(!key)continue;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(name)}return[...groups.values()].filter(g=>g.length>1).map((names,i)=>({id:'a'+i,names:[...names].sort((a,b)=>a.localeCompare(b,'de')),canonical:aliasLabel(names)}))}
function renderAliasReview(){const root=$('#alias-review');if(!aliasCandidates.length){root.hidden=true;root.innerHTML='';return}root.hidden=false;root.innerHTML=`<div class="alias-head"><p class="eyebrow">PERSONEN PRÜFEN</p><h2>Mögliche Namensvarianten</h2><p class="muted">Nur bestätigte Vorschläge werden zusammengeführt. Die Originalnamen bleiben intern für Import- und Debug-Nachweise erhalten.</p></div><div class="alias-list">${aliasCandidates.map(a=>`<label class="alias-card"><input type="checkbox" class="alias-merge" data-alias="${esc(a.id)}"><span><strong>${a.names.map(esc).join(' ↔ ')}</strong><small>Zusammenführen als</small><input class="alias-canonical" data-alias-name="${esc(a.id)}" value="${esc(a.canonical)}" aria-label="Kanonischer Name"></span></label>`).join('')}</div>`}
function selectedAliases(){const out={};for(const a of aliasCandidates){const box=document.querySelector(`.alias-merge[data-alias="${a.id}"]`);if(!box?.checked)continue;const input=document.querySelector(`.alias-canonical[data-alias-name="${a.id}"]`),canonical=input?.value.trim();if(!canonical)throw Error('Bitte für jede bestätigte Zusammenführung einen Namen angeben.');for(const raw of a.names)out[raw]=canonical}return out}
function renderReview(){$('#file-review').innerHTML=inspection.map(f=>`<article class="file-card" data-id="${esc(f.id)}"><header><div><strong>${esc(f.name)}</strong><div class="meta">${num(f.total)} Nachrichten · ${fmt(f.first)}–${fmt(f.last)}</div></div><span class="meta">${f.participants.length} Person${f.participants.length===1?'':'en'}</span></header><div class="identity-row">${autoMe?`<label>Als „Ich“ erkannt<div class="identity-fixed">${esc(autoMe)}</div><input class="me" type="hidden" value="${esc(autoMe)}"></label>`:`<label>Wer bist du?<select class="me"><option value="">Bitte bestätigen …</option>${f.participants.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label>`}${f.ambiguous?`<label>Datumsformat<select class="date"><option value="">Bitte bestätigen …</option><option value="DMY">Tag / Monat / Jahr</option><option value="MDY">Monat / Tag / Jahr</option></select><small class="meta">Beispiel: ${esc(f.example)}</small></label>`:`<label>Datumsformat<input value="${f.dateOrder==='DMY'?'Tag / Monat / Jahr':'Monat / Tag / Jahr'}" disabled><input class="date" type="hidden" value="${f.dateOrder}"></label>`}</div></article>`).join('');renderAliasReview()}
$('#review-back').onclick=reset;$('#clear').onclick=reset;function reset(){worker?.terminate();worker=null;rawFiles=[];inspection=[];built=null;autoMe=null;aliasCandidates=[];filesEl.value='';show('#import-view')}
$('#analyze').onclick=async()=>{const config={},cards=[...document.querySelectorAll('.file-card')];for(const c of cards){const me=c.querySelector('.me').value,dateOrder=c.querySelector('.date').value;if(!me||!dateOrder){$('#review-error').hidden=false;$('#review-error').textContent='Bitte die noch mehrdeutigen Angaben bestätigen.';return}config[c.dataset.id]={me,dateOrder}}try{const aliases=selectedAliases();$('#review-error').hidden=true;await buildWithConfig(config,aliases)}catch(e){$('#review-error').hidden=false;$('#review-error').textContent=e.message}};
async function buildWithConfig(config,aliases={}){try{show('#loading');$('#loading-text').textContent=autoMe?`„${autoMe}“ wurde in allen Exporten erkannt. Chats werden lokal zusammengeführt.`:'Chats werden lokal zusammengeführt und exakt dedupliziert.';built=await ask('build',{files:rawFiles,config,aliases});renderImport();currentRange=null;renderMetrics(built.metrics);show('#dashboard')}catch(e){if(inspection.length){renderReview();show('#review');$('#review-error').hidden=false;$('#review-error').textContent=e.message}else fail(e.message)}}
function kpi(value,label){return`<div class="kpi"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function renderImport(){const s=built.summary;$('#dash-sub').textContent=`${s.files} Exporte · ${s.chats} erkannte Chats · ${fmt(s.first)}–${fmt(s.last)}`;$('#from').min=$('#to').min=iso(s.first);$('#from').max=$('#to').max=iso(s.last);$('#import-kpis').innerHTML=kpi(num(s.files),'Dateien')+kpi(num(s.chats),'erkannte Chats')+kpi(num(s.unique),'eindeutige Nachrichten')+kpi(num(s.duplicates),'exakte Dubletten entfernt')+kpi(num(s.aliases||0),'bestätigte Alias-Namen');const aliasInfo=(built.aliasMerges||[]).length?`<details class="debug-details"><summary>Zusammengeführte Personen (${num(built.aliasMerges.length)})</summary><div class="debug-body">${built.aliasMerges.map(x=>`<div class="debug-row"><strong>${esc(x.raw)} → ${esc(x.canonical)}</strong></div>`).join('')}</div></details>`:'';const items=[...built.wholeDuplicates.map(x=>`<div class="overlap"><strong>Identische Datei</strong><p>${esc(x.file)} entspricht ${esc(x.duplicateOf)}.</p></div>`),...built.overlaps.map(x=>`<div class="overlap"><strong>${esc(x.chat)}</strong><p>${fmt(x.start)}–${fmt(x.end)} · ${esc(x.a)} ↔ ${esc(x.b)}<br>${esc(x.note)}</p></div>`)];const dups=built.duplicateRecords||[],debug=s.duplicates?`<details class="debug-details"><summary>Debugbericht: ${num(s.duplicates)} entfernte exakte Dublette${s.duplicates===1?'':'n'} anzeigen</summary><div class="debug-body"><p class="debug-note">Lokale Diagnose. Angezeigt werden maximal 500 entfernte Datensätze; nichts davon wird gespeichert oder übertragen.${built.duplicateRecordsTruncated?' Die Liste wurde für die Darstellung gekürzt.':''}</p>${dups.map(x=>`<div class="debug-row"><strong>${esc(x.chat)} · ${fmtDateTime(x.dateMs)}</strong><div>${esc(x.file)} ← bereits aus ${esc(x.duplicateOf)}</div><code>${esc(x.sender)} · ${esc(x.type)}${x.preview?' · '+esc(x.preview):''}</code></div>`).join('')}</div></details>`:'';$('#overlaps').innerHTML=`<h3>Überlappungen & Dubletten</h3>${items.length?items.join(''):'<p class="muted">Keine überlappenden Exportbereiche erkannt.</p>'}${aliasInfo}${debug}`}
function fmtDateTime(ms){return ms?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ms)):'–'}
function iso(ms){if(!ms)return'';const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function refreshMetrics(){renderMetrics(await ask('metrics',{range:currentRange,options:{stopMode,sessionGapHours}}))}
function setRange(start='',end='',label='Gesamter Zeitraum'){$('#from').value=start;$('#to').value=end;currentRange=start||end?{start,end}:null;$('#range-label').textContent=label;document.querySelectorAll('.preset').forEach(b=>b.classList.remove('active'))}
$('#apply-range').onclick=async()=>{const start=$('#from').value,end=$('#to').value;if(start&&end&&start>end)return;setRange(start,end,start||end?`${start||'…'} – ${end||'…'}`:'Gesamter Zeitraum');await refreshMetrics()};
$('#all-range').onclick=async()=>{setRange();document.querySelector('[data-preset="all"]').classList.add('active');await refreshMetrics()};
function clampRange(a,b){const min=iso(built.summary.first),max=iso(built.summary.last);return[a<min?min:a,b>max?max:b]}
function dateISO(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function applyPreset(kind){const last=new Date(built.summary.last),first=new Date(built.summary.first);last.setHours(12,0,0,0);first.setHours(12,0,0,0);let a=new Date(first),b=new Date(last),label='Gesamter Zeitraum';if(kind==='30d'){a=new Date(last);a.setDate(a.getDate()-29);label='Letzte 30 Tage'}else if(kind==='last-month'){a=new Date(last.getFullYear(),last.getMonth()-1,1,12);b=new Date(last.getFullYear(),last.getMonth(),0,12);label='Letzter vollständiger Monat'}else if(kind==='12m'){a=new Date(last);a.setFullYear(a.getFullYear()-1);a.setDate(a.getDate()+1);label='Letzte 12 Monate'}else if(kind==='prev-year'){const y=last.getFullYear()-1;a=new Date(y,0,1,12);b=new Date(y,11,31,12);label=`Kalenderjahr ${y}`}else if(kind==='all'){setRange();label='Gesamter Zeitraum';document.querySelectorAll('.preset').forEach(x=>x.classList.toggle('active',x.dataset.preset==='all'));await refreshMetrics();return}let [start,end]=clampRange(dateISO(a),dateISO(b));setRange(start,end,label);document.querySelectorAll('.preset').forEach(x=>x.classList.toggle('active',x.dataset.preset===kind));await refreshMetrics()}
document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
$('#month-preset').onchange=async e=>{if(!e.target.value)return;const [y,m]=e.target.value.split('-').map(Number),a=new Date(y,m-1,1,12),b=new Date(y,m,0,12);let[start,end]=clampRange(dateISO(a),dateISO(b));setRange(start,end,new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(a));await refreshMetrics()};

function activitySeries(m){return activityMode==='day'?m.daySeries:activityMode==='year'?m.yearSeries:m.monthSeries}
function renderMetrics(m){lastMetrics=m;renderActivity(m);drawLine($('#length-chart'),m.lengthSeries,'Median Zeichen');drawLine($('#active-chart'),m.activeSeries,'Aktive Chats');renderLengthBuckets(m.lengthBuckets);renderCalendar(m);renderHourChart(m.hours);renderWeekdays(m);renderHourWeekday(m.hourWeekday);renderYearHour(m.yearHour);$('#style-kpis').innerHTML=kpi(num(m.messagesPerActiveDay,1),'Nachrichten pro aktivem Tag')+kpi(num(m.questions),'Fragen')+kpi(num(m.links),'Links')+kpi(num(m.attachments),'Anhang-Platzhalter');rateRank($('#emoji'),m.emojiTrend,'1.000');renderEmojiAll(m);rateRank($('#words'),m.wordRates,'10.000');rateRank($('#phrases'),m.phraseRates,'10.000');renderContents(m);const total=m.chatCounts.reduce((s,x)=>s+x.value,0);rank($('#chat-share'),m.chatCounts,x=>`${num(x.value)} · ${num(total?x.value/total*100:0,1)} %`,x=>x.label);renderChatTime();renderSessions(m.sessions)}
function renderActivity(m){drawLine($('#messages-chart'),activitySeries(m),'Nachrichten');$('#activity-unit-label').textContent=activityMode==='day'?'pro Tag':activityMode==='year'?'pro Jahr':'pro Monat';const dayText=m.activeDay?`${formatPeriod(m.activeDay.label,'day')} · ${num(m.activeDay.value)}`:'–',monthText=m.activeMonth?`${formatPeriod(m.activeMonth.label,'month')} · ${num(m.activeMonth.value)}`:'–',yearText=m.activeYear?`${m.activeYear.label} · ${num(m.activeYear.value)}`:'–';$('#activity-records').innerHTML=`<div class="record"><span>Aktivster Tag</span><strong>${esc(dayText)}</strong></div><div class="record"><span>Aktivster Monat</span><strong>${esc(monthText)}</strong></div><div class="record"><span>Aktivstes Jahr</span><strong>${esc(yearText)}</strong></div><div class="record"><span>Längste tägliche Serie</span><strong>${num(m.longestStreak)} Tage</strong><small>${m.streakStart&&m.streakEnd?fmt(m.streakStart)+' – '+fmt(m.streakEnd):'–'}</small></div><div class="record"><span>Längste Pause</span><strong>${num(m.longestPause)} Tage</strong><small>${m.pauseStart&&m.pauseEnd?fmt(m.pauseStart)+' – '+fmt(m.pauseEnd):'–'}</small></div>`}
function formatPeriod(v,mode){if(mode==='day')return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v+'T12:00:00'));if(mode==='month')return new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date(v+'-01T12:00:00'));return v}
function setActivityMode(mode){activityMode=mode;['day','month','year'].forEach(x=>$('#activity-'+x).classList.toggle('active',x===mode));if(lastMetrics)renderActivity(lastMetrics)}
$('#activity-day').onclick=()=>setActivityMode('day');$('#activity-month').onclick=()=>setActivityMode('month');$('#activity-year').onclick=()=>setActivityMode('year');
function bars(el,data){const max=Math.max(1,...data.map(x=>x.value));el.innerHTML=data.map(x=>`<div class="barrow"><span>${esc(x.label)}</span><div class="track"><div class="fill" style="width:${x.value/max*100}%"></div></div><strong>${num(x.value)}</strong></div>`).join('')}
function rank(el,data,val,label){el.innerHTML=data.length?data.map(x=>`<div class="rankrow"><span>${esc(label(x))}</span><strong>${esc(val(x))}</strong></div>`).join(''):'<p class="muted">Keine Daten im Zeitraum.</p>'}
function rateRank(el,data,unit){el.innerHTML=data.length?data.map(x=>`<div class="rankrow"><span>${esc(x.label)}${x.type?` · ${esc(x.type)}`:''}</span><strong>${num(x.rate,1)} / ${unit}</strong></div>`).join(''):'<p class="muted">Keine Daten im Zeitraum.</p>'}
function renderLengthBuckets(rows){bars($('#length-buckets'),rows)}
function renderCalendar(m){const select=$('#calendar-year'),detail=$('#calendar-detail'),years=[...new Set(m.daySeries.map(x=>x.label.slice(0,4)))];if(!years.length){select.innerHTML='';$('#calendar-heatmap').innerHTML='<p class="muted">Keine Daten im Zeitraum.</p>';detail.textContent='';return}if(!calendarYear||!years.includes(calendarYear))calendarYear=years.at(-1);select.innerHTML=years.map(y=>`<option value="${y}"${y===calendarYear?' selected':''}>${y}</option>`).join('');select.onchange=e=>{calendarYear=e.target.value;renderCalendar(lastMetrics)};const map=new Map(m.daySeries.map(x=>[x.label,x.value])),vals=m.daySeries.filter(x=>x.label.startsWith(calendarYear+'-')).map(x=>x.value),max=Math.max(1,...vals),months=[];for(let mo=0;mo<12;mo++){const days=new Date(+calendarYear,mo+1,0).getDate();let cells='';for(let d=1;d<=days;d++){const key=`${calendarYear}-${String(mo+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,v=map.get(key)||0,level=v?Math.min(4,Math.ceil(v/max*4)):0;cells+=`<button type="button" class="calendar-day ${v?'level'+level:''}" data-date="${key}" data-value="${v}" aria-label="${formatPeriod(key,'day')}: ${num(v)} Nachrichten"><span>${d}</span></button>`}months.push(`<div class="calendar-month"><strong>${new Intl.DateTimeFormat('de-DE',{month:'long'}).format(new Date(+calendarYear,mo,1))}</strong><div class="calendar-days">${cells}</div></div>`)}const root=$('#calendar-heatmap');root.innerHTML=months.join('');const showDay=(b,persist=false)=>{const text=`${formatPeriod(b.dataset.date,'day')} · ${num(+b.dataset.value)} eigene Nachrichten`;detail.textContent=text;if(persist){root.querySelectorAll('.calendar-day.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}};root.querySelectorAll('.calendar-day').forEach(b=>{b.onclick=()=>showDay(b,true);b.onpointerenter=()=>showDay(b,false);b.onfocus=()=>showDay(b,false)});detail.textContent='Tag auswählen, um Details anzuzeigen.'}
function renderHourWeekday(matrix){const root=$('#hour-weekday'),names=['So','Mo','Di','Mi','Do','Fr','Sa'],order=[1,2,3,4,5,6,0],max=Math.max(1,...matrix.flat());let h='<div class="matrix weekday-hour-matrix"><span></span>'+Array.from({length:24},(_,i)=>`<span class="matrix-cell head">${i%3===0?String(i).padStart(2,'0'):''}</span>`).join('');for(const d of order)h+=`<span class="matrix-cell head year-label">${names[d]}</span>`+matrix[d].map((v,i)=>`<span class="matrix-cell interactive-cell ${v?'level'+Math.min(4,Math.ceil(v/max*4)):''}" data-day="${names[d]}" data-hour="${i}" data-value="${v}"></span>`).join('');root.innerHTML=h+'</div>';bindMatrixCells(root,'weekday')}
function bindMatrixCells(root,type){let tip=document.createElement('div');tip.className='cell-tip';tip.hidden=true;root.append(tip);const show=(c,e)=>{tip.textContent=type==='weekday'?`${c.dataset.day} · ${String(c.dataset.hour).padStart(2,'0')}:00–${String(c.dataset.hour).padStart(2,'0')}:59 · ${num(+c.dataset.value)} Nachrichten`:`${c.dataset.year} · ${String(c.dataset.hour).padStart(2,'0')}:00–${String(c.dataset.hour).padStart(2,'0')}:59 · ${num(+c.dataset.value)} Nachrichten`;tip.hidden=false;const rr=root.getBoundingClientRect();tip.style.left=Math.max(6,Math.min(rr.width-tip.offsetWidth-6,e.clientX-rr.left+root.scrollLeft+10))+'px';tip.style.top=Math.max(6,e.clientY-rr.top+root.scrollTop-38)+'px'};root.querySelectorAll('.interactive-cell').forEach(c=>{c.onpointerenter=e=>show(c,e);c.onpointermove=e=>show(c,e);c.onpointerdown=e=>show(c,e)});root.onpointerleave=e=>{if(e.pointerType==='mouse')tip.hidden=true}}
function renderEmojiAll(m){const rows=m.emojiAll||[];$('#emoji-all').innerHTML=rows.length?`<table><thead><tr><th>Emoji</th><th>Anzahl</th><th>Anteil</th><th>Erstmals</th><th>Zuletzt</th><th>Ø / Tag</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="emoji-cell">${esc(x.label)}</td><td>${num(x.count)}</td><td>${num(x.share,2)} %</td><td>${fmt(x.first)}</td><td>${fmt(x.last)}</td><td>${num(x.perDay,2)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Keine Emojis im Zeitraum.</p>'}
function renderContents(m){const a=m.attachmentTypes||{};$('#content-kpis').innerHTML=kpi(num(m.links),'Links')+kpi(num(m.attachments),'Anhänge')+kpi(num(a.image),'Bilder')+kpi(num(a.audio),'Audio');bars($('#attachment-types'),[{label:'Bilder',value:a.image||0},{label:'Videos',value:a.video||0},{label:'Audio',value:a.audio||0},{label:'Dokumente',value:a.document||0},{label:'Sonstige Medien',value:a.media||0}]);rank($('#domains'),m.domains||[],x=>num(x.value),x=>x.label)}
document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=async()=>{stopMode=b.dataset.stop;document.querySelectorAll('[data-stop]').forEach(x=>x.classList.toggle('active',x===b));await refreshMetrics()});
function renderWeekdays(m){const names=['So','Mo','Di','Mi','Do','Fr','Sa'],occ=weekdayOccurrences(m),avgs=m.weekdays.map((v,i)=>occ[i]?v/occ[i]:0),max=Math.max(1,...avgs),total=m.weekdays.reduce((a,b)=>a+b,0);$('#weekday-chart').innerHTML=[1,2,3,4,5,6,0].map(i=>`<div class="hbar weekday-row"><span>${names[i]}</span><div class="track"><div class="fill" style="width:${avgs[i]/max*100}%"></div></div><strong><span>Ø ${num(avgs[i],1)}</span><small>${num(m.weekdays[i])} · ${total?num(m.weekdays[i]/total*100,1):0}%</small></strong></div>`).join('')}
function weekdayOccurrences(m){const out=Array(7).fill(0);if(!m.first||!m.last)return out;const a=new Date(m.first),b=new Date(m.last);a.setHours(12,0,0,0);b.setHours(12,0,0,0);for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))out[d.getDay()]++;return out}
function renderHourChart(hours){const svg=$('#hour-chart'),w=720,h=245,pL=48,pR=14,pT=14,pB=34,max=Math.max(1,...hours),plotH=h-pT-pB,barW=(w-pL-pR)/24,total=hours.reduce((a,b)=>a+b,0);let grid='',barsHtml='',labels='';for(let i=0;i<=4;i++){const value=Math.round(max*(4-i)/4),y=pT+plotH*i/4;grid+=`<line class="gridline" x1="${pL}" y1="${y}" x2="${w-pR}" y2="${y}"/><text class="axistext" x="${pL-8}" y="${y+3}" text-anchor="end">${num(value)}</text>`}hours.forEach((v,i)=>{const bh=v/max*plotH,x=pL+i*barW+2,y=pT+plotH-bh;barsHtml+=`<rect class="hour-bar" x="${x}" y="${y}" width="${Math.max(3,barW-4)}" height="${Math.max(v?2:0,bh)}"></rect>`;if(i%3===0)labels+=`<text class="axistext" x="${x+barW/2-2}" y="${h-10}" text-anchor="middle">${String(i).padStart(2,'0')}</text>`});svg.innerHTML=`${grid}${barsHtml}${labels}<g class="hour-focus" visibility="hidden"><line class="focusline" y1="${pT}" y2="${h-pB}"/><circle class="focusdot" r="5"/><rect class="tooltipbg" rx="5" width="235" height="28"/><text class="tooltiptext"></text></g><rect class="chart-hit" x="${pL}" y="${pT}" width="${w-pL-pR}" height="${h-pT-pB}"/>`;const focus=svg.querySelector('.hour-focus'),line=focus.children[0],dot=focus.children[1],box=focus.children[2],text=focus.children[3];function move(ev){const ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(ctm.inverse()),idx=Math.max(0,Math.min(23,Math.floor((p.x-pL)/barW))),v=hours[idx],cx=pL+(idx+.5)*barW,cy=pT+plotH-v/max*plotH,tx=Math.min(w-245,Math.max(5,cx+8));focus.setAttribute('visibility','visible');line.setAttribute('x1',cx);line.setAttribute('x2',cx);dot.setAttribute('cx',cx);dot.setAttribute('cy',cy);box.setAttribute('x',tx);box.setAttribute('y',Math.max(3,cy-38));text.setAttribute('x',tx+8);text.setAttribute('y',Math.max(21,cy-20));text.textContent=`${String(idx).padStart(2,'0')}:00–${String(idx).padStart(2,'0')}:59 · ${num(v)} · ${total?num(v/total*100,1):0} %`}svg.onpointermove=move;svg.onpointerdown=e=>{svg.setPointerCapture?.(e.pointerId);move(e)};svg.onpointerleave=e=>{if(e.pointerType==='mouse')focus.setAttribute('visibility','hidden')}}
function renderYearHour(rows){const root=$('#year-hour');if(!rows.length){root.innerHTML='<p class="muted">Keine Daten.</p>';return}let h='<div class="matrix year-hour-matrix"><span></span>'+Array.from({length:24},(_,i)=>`<span class="matrix-cell head">${i%3===0?String(i).padStart(2,'0'):''}</span>`).join('');for(const r of rows){const rowMax=Math.max(1,...r.values);h+=`<span class="matrix-cell head year-label">${esc(r.year)}</span>`+r.values.map((v,i)=>`<span class="matrix-cell interactive-cell ${v?'level'+Math.min(4,Math.ceil(v/rowMax*4)):''}" data-year="${esc(r.year)}" data-hour="${i}" data-value="${v}" title="${esc(r.year)} · ${String(i).padStart(2,'0')}:00–${String(i).padStart(2,'0')}:59 · ${num(v)} Nachrichten"></span>`).join('')}root.innerHTML=h+'</div>';bindCells(root)}
function bindCells(root){let tip=root.querySelector('.cell-tip');if(!tip){tip=document.createElement('div');tip.className='cell-tip';root.append(tip)}const cells=[...root.querySelectorAll('.interactive-cell')];const show=(cell,e)=>{tip.textContent=`${cell.dataset.year} · ${String(cell.dataset.hour).padStart(2,'0')}:00–${String(cell.dataset.hour).padStart(2,'0')}:59 · ${num(+cell.dataset.value)} Nachrichten`;tip.hidden=false;const rr=root.getBoundingClientRect();tip.style.left=Math.max(6,Math.min(rr.width-tip.offsetWidth-6,e.clientX-rr.left+root.scrollLeft+10))+'px';tip.style.top=Math.max(6,e.clientY-rr.top+root.scrollTop-38)+'px'};cells.forEach(c=>{c.onpointerenter=e=>show(c,e);c.onpointermove=e=>show(c,e);c.onpointerdown=e=>show(c,e)});root.onpointerleave=e=>{if(e.pointerType==='mouse')tip.hidden=true}}
function aggregateYears(rows){const years=new Map();for(const r of rows){const y=r.label.slice(0,4);if(!years.has(y))years.set(y,new Map());const map=years.get(y);for(const x of r.values)map.set(x.chat,(map.get(x.chat)||0)+x.value)}return[...years].sort().map(([label,map])=>({label,values:[...map].sort((a,b)=>b[1]-a[1]).map(([chat,value])=>({chat,value}))}))}
function renderChatTime(){if(!lastMetrics)return;chatTable(chatTimeMode==='year'?aggregateYears(lastMetrics.chatMonth):lastMetrics.chatMonth,chatTimeMode==='year'?'Jahr':'Monat')}
function chatTable(rows,heading){const chats=[...new Set(rows.flatMap(r=>r.values.map(x=>x.chat)))].slice(0,12);let h=`<table><thead><tr><th>${heading}</th>`+chats.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>';for(const r of rows){const map=new Map(r.values.map(x=>[x.chat,x.value])),sum=r.values.reduce((s,x)=>s+x.value,0);h+=`<tr><td>${esc(r.label)}</td>`+chats.map(c=>`<td>${map.has(c)?num(map.get(c))+' · '+num(map.get(c)/sum*100,0)+' %':'–'}</td>`).join('')+'</tr>'}$('#chat-time').innerHTML=h+'</tbody></table>'}
function setChatTimeMode(mode){chatTimeMode=mode;$('#chat-time-month').classList.toggle('active',mode==='month');$('#chat-time-year').classList.toggle('active',mode==='year');renderChatTime()}
$('#chat-time-month').onclick=()=>setChatTimeMode('month');$('#chat-time-year').onclick=()=>setChatTimeMode('year');
function renderSessions(s){if(!s)return;const total=s.chats.reduce((a,x)=>a+x.total,0),mine=s.chats.reduce((a,x)=>a+x.mine,0),eligible=s.chats.filter(x=>x.total>=5),won=eligible.filter(x=>x.mine>x.total/2).length;$('#session-kpis').innerHTML=kpi(num(total),'Gesprächsphasen')+kpi(total?num(mine/total*100,1)+' %':'–','von dir gestartet')+kpi(eligible.length?num(won/eligible.length*100,1)+' %':'–',`Chats überwiegend von dir · ${won}/${eligible.length}`);$('#session-chat-table').innerHTML=s.chats.length?`<table><thead><tr><th>Chat</th><th>Phasen</th><th>Ich starte</th><th>Andere</th></tr></thead><tbody>${s.chats.map(x=>`<tr><td>${esc(x.chat)}</td><td>${num(x.total)}</td><td>${num(x.mineShare,1)} % · ${num(x.mine)}</td><td>${num(100-x.mineShare,1)} % · ${num(x.other)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Keine Gesprächsphasen.</p>';const sel=$('#session-chat'),old=sel.value;sel.innerHTML=s.chats.map(x=>`<option value="${esc(x.chat)}">${esc(x.chat)}</option>`).join('');if(s.chats.some(x=>x.chat===old))sel.value=old;sel.onchange=()=>renderSessionChart();renderSessionChart();renderSessionDominance()}
function renderSessionChart(){if(!lastMetrics?.sessions)return;const c=lastMetrics.sessions.chats.find(x=>x.chat===$('#session-chat').value)||lastMetrics.sessions.chats[0];if(!c){drawLine($('#session-chart'),[],'%');return}const rows=(sessionTimeMode==='year'?c.yearly:c.monthly).map(x=>({label:x.label,value:x.share,detail:x.total}));drawLine($('#session-chart'),rows,'% gestartet')}
function renderSessionDominance(){if(!lastMetrics?.sessions)return;const rows=(sessionTimeMode==='year'?lastMetrics.sessions.dominanceYear:lastMetrics.sessions.dominanceMonth).filter(x=>x.eligible).map(x=>({label:x.label,value:x.share}));drawLine($('#session-dominance'),rows,'% Chats')}
$('#session-month').onclick=()=>{sessionTimeMode='month';$('#session-month').classList.add('active');$('#session-year').classList.remove('active');renderSessionChart();renderSessionDominance()};$('#session-year').onclick=()=>{sessionTimeMode='year';$('#session-year').classList.add('active');$('#session-month').classList.remove('active');renderSessionChart();renderSessionDominance()};$('#session-gap').onchange=async e=>{sessionGapHours=+e.target.value;await refreshMetrics()};
function drawLine(svg,data,label){const W=900,H=280,L=54,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B,max=Math.max(1,...data.map(x=>x.value));svg.innerHTML='';if(!data.length){svg.innerHTML='<text x="450" y="140" text-anchor="middle" class="axistext">Keine Daten im Zeitraum</text>';return}for(let i=0;i<=4;i++){const y=T+ih*i/4;svg.insertAdjacentHTML('beforeend',`<line class="gridline" x1="${L}" y1="${y}" x2="${W-R}" y2="${y}"/><text class="axistext" x="${L-8}" y="${y+4}" text-anchor="end">${num(max*(1-i/4),0)}</text>`)}const pts=data.map((d,i)=>({x:L+(data.length===1?iw/2:i*iw/(data.length-1)),y:T+ih-(d.value/max*ih),...d}));svg.insertAdjacentHTML('beforeend',`<path class="series" d="${pts.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')}"/>`);const ticks=[0,Math.floor((data.length-1)/2),data.length-1].filter((v,i,a)=>a.indexOf(v)===i);ticks.forEach(i=>svg.insertAdjacentHTML('beforeend',`<text class="axistext" x="${pts[i].x}" y="${H-12}" text-anchor="middle">${esc(shortSeriesLabel(data[i].label))}</text>`));const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('visibility','hidden');g.innerHTML=`<line class="focusline" y1="${T}" y2="${H-B}"/><circle class="focusdot" r="5"/><rect class="tooltipbg" rx="5" width="190" height="28"/><text class="tooltiptext" y="18"></text>`;svg.append(g);const line=g.children[0],dot=g.children[1],box=g.children[2],text=g.children[3];function move(ev){const ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(ctm.inverse()),idx=Math.max(0,Math.min(pts.length-1,Math.round((p.x-L)/iw*(pts.length-1)))),q=pts[idx],tx=Math.min(W-200,Math.max(8,q.x+10));g.setAttribute('visibility','visible');line.setAttribute('x1',q.x);line.setAttribute('x2',q.x);dot.setAttribute('cx',q.x);dot.setAttribute('cy',q.y);box.setAttribute('x',tx);box.setAttribute('y',Math.max(4,q.y-38));text.setAttribute('x',tx+8);text.setAttribute('y',Math.max(22,q.y-20));text.textContent=`${seriesTooltipLabel(q.label)} · ${num(q.value,1)} ${label}`}
svg.onpointermove=move;svg.onpointerdown=e=>{svg.setPointerCapture?.(e.pointerId);move(e)};svg.onpointerleave=e=>{if(e.pointerType==='mouse')g.setAttribute('visibility','hidden')}}
$('#stopwords-de').textContent=STOPWORDS_DE.join(' · ');$('#stopwords-en').textContent=STOPWORDS_EN.join(' · ');
startWorker();
