import {renderTable,renderOverlay} from './ui.js';
const $=s=>document.querySelector(s);let code='',token='',state=null,ws=null;
function credentials(){const q=new URLSearchParams(location.search);code=(q.get('code')||'').toUpperCase();const h=new URLSearchParams(location.hash.slice(1));token=h.get('token')||'';if(code)$('#join-code').value=code;if(token)$('#join-token').value=token;}
async function api(action='',body={}){const r=await fetch(`/x/poker/live/api/sessions/${code}/${action}`,{method:action?'POST':'GET',headers:{'Content-Type':'application/json','X-Poker-Controller':token},body:action?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return d;}
function connect(){if(ws)ws.close();const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/x/poker/live/api/sessions/${code}/ws`);ws.addEventListener('open',()=>{});/* WebSocket snapshot is read-only; mutations use token-protected HTTP. */ws.addEventListener('message',e=>{const d=JSON.parse(e.data);if(d.state){state=d.state;render();}});ws.addEventListener('close',()=>setTimeout(connect,1800));}
async function open(){code=$('#join-code').value.trim().toUpperCase();token=$('#join-token').value.trim();const d=await api();if(!d.controller)throw new Error('Controller-Schlüssel ungültig.');state=d.state;history.replaceState(null,'',`?code=${code}#token=${token}`);$('#join-view').hidden=true;$('#controller-view').hidden=false;connect();render();}
function render(){if(!state)return;$('#level-label').textContent='AKTUELLE BLINDS';$('#blinds').textContent=`${state.currentBlinds.sb} / ${state.currentBlinds.bb}`;$('#round-label').textContent=`Runde ${Math.min(state.round,state.roundsPerLevel)} von ${state.roundsPerLevel} · Hand ${state.hand}`;renderTable($('#table'),state,player=>playerMenu(player));$('#share-code').textContent=code;$('#display-link').href=`./display/?code=${code}`;$('#next-hand').disabled=state.status!=='running';$('#pause').textContent=state.status==='paused'?'Weiter':'Pause';$('#next-level').hidden=state.status!=='level-change';$('#status-banner').innerHTML=state.status==='level-change'?'<div class="live-status"><strong>Blindstufe abgeschlossen.</strong> Neue Blinds bewusst starten.</div>':state.status==='paused'?'<div class="live-status"><strong>Pause</strong> · Spielstand bleibt erhalten.</div>':'';renderOverlay($('#overlay'),state.overlay);bindOverlayClose();}
async function action(name,body){try{const d=await api(name,body);state=d.state;render();}catch(e){alert(e.message)}}
function playerMenu(p){if(confirm(`${p.name} scheidet nach der aktuellen Hand aus?`))action('eliminate',{playerId:p.id});}
function bindOverlayClose(){const b=$('#overlay [data-close]');if(b)b.onclick=()=>action('overlay',{overlay:null});}
$('#join-code').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)});$('#join-button').onclick=()=>open().catch(e=>alert(e.message));$('#next-hand').onclick=()=>action('next-hand');$('#pause').onclick=()=>action('pause');$('#next-level').onclick=()=>action('next-level');$('#ranks').onclick=()=>action('overlay',{overlay:'ranks'});$('#rules').onclick=()=>action('overlay',{overlay:'rules'});$('#players').onclick=()=>alert('Spieler direkt am Tisch antippen, um ein Ausscheiden nach der aktuellen Hand zu markieren.');credentials();if(code&&token)open().catch(()=>{});
