import {renderTable,renderOverlay} from './ui.js';
const $=s=>document.querySelector(s);let code='',token='',state=null,ws=null;
function credentials(){const q=new URLSearchParams(location.search);code=(q.get('code')||'').toUpperCase();const h=new URLSearchParams(location.hash.slice(1));token=h.get('token')||'';if(code)$('#join-code').value=code;if(token)$('#join-token').value=token;}
async function api(action='',body={}){const r=await fetch(`/x/poker/live/api/sessions/${code}/${action}`,{method:action?'POST':'GET',headers:{'Content-Type':'application/json','X-Poker-Controller':token},body:action?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return d;}
function connect(){if(ws)ws.close();const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/x/poker/live/api/sessions/${code}/ws`);ws.addEventListener('message',e=>{const d=JSON.parse(e.data);if(d.state){state=d.state;render();}});ws.addEventListener('close',()=>setTimeout(connect,1800));}
async function open(){code=$('#join-code').value.trim().toUpperCase();token=$('#join-token').value.trim();const d=await api();if(!d.controller)throw new Error('Controller-Schlüssel ungültig.');state=d.state;history.replaceState(null,'',`?code=${code}#token=${token}`);$('#join-view').hidden=true;$('#controller-view').hidden=false;connect();render();}
function render(){if(!state)return;$('#level-label').textContent='AKTUELLE BLINDS';$('#blinds').textContent=`${state.currentBlinds.sb} / ${state.currentBlinds.bb}`;$('#round-label').textContent=`Runde ${Math.min(state.round,state.roundsPerLevel)} von ${state.roundsPerLevel} · Hand ${state.hand}`;renderTable($('#table'),state,player=>playerMenu(player));$('#share-code').textContent=code;$('#display-link').href=`./display/?code=${code}`;$('#next-hand').disabled=state.status!=='running';$('#pause').textContent=state.status==='paused'?'Weiter':'Pause';$('#next-level').hidden=state.status!=='level-change';$('#undo').disabled=!state.canUndo;$('#undo').title=state.undoLabel||'Keine Aktion zum Rückgängigmachen';renderHistory();const colorUps=state.colorUpsDue||[];$('#status-banner').innerHTML=state.status==='level-change'?(colorUps.length?`<div class="live-status colorup-status"><strong>Color-up: ${colorUps.join(' / ')}er-Chips raus.</strong> Chips jetzt wechseln, danach die neuen Blinds starten.</div>`:'<div class="live-status"><strong>Blindstufe abgeschlossen.</strong> Neue Blinds bewusst starten.</div>'):state.status==='paused'?'<div class="live-status"><strong>Pause</strong> · Spielstand bleibt erhalten.</div>':'';renderOverlay($('#overlay'),state.overlay==='rules'?'rules':null);bindOverlayClose();$('#ranks').checked=state.overlay==='ranks';$('#view-table').classList.toggle('is-active',(state.displayMode||'table')==='table');$('#view-broadcast').classList.toggle('is-active',state.displayMode==='broadcast');$('#view-minimal').classList.toggle('is-active',state.displayMode==='minimal');}
async function action(name,body){try{const d=await api(name,body);state=d.state;render();}catch(e){alert(e.message)}}
function playerMenu(p){if(state.pendingEliminations.includes(p.id)){if(confirm(`${p.name}: Ausscheiden nach dieser Hand zurücknehmen?`))action('cancel-elimination',{playerId:p.id});return}if(confirm(`${p.name} scheidet nach der aktuellen Hand aus?`))action('eliminate',{playerId:p.id});}
function bindOverlayClose(){const b=$('#overlay [data-close]');if(b)b.onclick=()=>action('overlay',{overlay:null});}
function renderHistory(){const log=state.eventLog||[];$('#event-log').innerHTML=log.length?log.slice(0,20).map(e=>`<div class="controller-event"><time>${new Date(e.at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</time><strong>${escapeHtml(e.label)}</strong></div>`).join(''):'<p class="helper-copy">Noch keine Aktionen.</p>';}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function correctPositions(){const seats=state.players.map(p=>`${p.seat}=${p.name}${p.status==='out'?' (raus)':''}`).join('\n');const d=prompt(`Dealer-Sitz eingeben:\n${seats}`,String(state.buttonSeat));if(d===null)return;const sb=prompt('Small-Blind-Sitz eingeben. 0 = kein Small Blind.',String(state.smallBlindSeat??0));if(sb===null)return;const bb=prompt('Big-Blind-Sitz eingeben.',String(state.bigBlindSeat));if(bb===null)return;if(confirm(`Positionen wirklich setzen?\nD Sitz ${d} · SB ${Number(sb)===0?'–':`Sitz ${sb}`} · BB Sitz ${bb}`))action('correct-roles',{buttonSeat:Number(d),smallBlindSeat:Number(sb)===0?null:Number(sb),bigBlindSeat:Number(bb)});}
$('#join-code').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)});$('#join-button').onclick=()=>open().catch(e=>alert(e.message));$('#next-hand').onclick=()=>action('next-hand');$('#pause').onclick=()=>action('pause');$('#next-level').onclick=()=>action('next-level');$('#undo').onclick=()=>{if(state.canUndo&&confirm(`Letzte Aktion rückgängig machen?\n${state.undoLabel||''}`))action('undo')};$('#history').onclick=()=>{$('#controller-log').hidden=false;$('#controller-log').scrollIntoView({behavior:'smooth',block:'nearest'})};$('#close-history').onclick=()=>{$('#controller-log').hidden=true};$('#correct').onclick=correctPositions;$('#ranks').onchange=e=>action('overlay',{overlay:e.target.checked?'ranks':null});$('#rules').onclick=()=>action('overlay',{overlay:state?.overlay==='rules'?null:'rules'});$('#view-table').onclick=()=>action('display-mode',{mode:'table'});$('#view-broadcast').onclick=()=>action('display-mode',{mode:'broadcast'});$('#view-minimal').onclick=()=>action('display-mode',{mode:'minimal'});$('#players').onclick=()=>alert('Spieler direkt am Tisch antippen. Eine gelb markierte Ausscheidens-Markierung kann dort auch wieder zurückgenommen werden.');credentials();if(code&&token)open().catch(()=>{});
