import {renderTable,renderOverlay} from './ui.js';
const $=s=>document.querySelector(s);let code='',token='',state=null,ws=null,busy=false,retryTimer=null;
function credentials(){const q=new URLSearchParams(location.search);code=(q.get('code')||'').toUpperCase();const h=new URLSearchParams(location.hash.slice(1));token=h.get('token')||'';if(code)$('#join-code').value=code;if(token)$('#join-token').value=token;}
async function api(action='',body={}){const payload=action?{...body,_actionId:crypto.randomUUID()}:body;const r=await fetch(`/x/poker/live/api/sessions/${code}/${action}`,{method:action?'POST':'GET',headers:{'Content-Type':'application/json','X-Poker-Controller':token},body:action?JSON.stringify(payload):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return d;}
function connection(label,kind=''){const el=$('#connection-state');if(!el)return;el.textContent=label;el.className=`connection-state ${kind}`;}
function connect(){clearTimeout(retryTimer);if(ws)ws.close();connection('Verbinden …');const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/x/poker/live/api/sessions/${code}/ws`);ws.addEventListener('open',()=>connection('Live verbunden','is-online'));ws.addEventListener('message',e=>{const d=JSON.parse(e.data);if(d.state){state=d.state;render();}});ws.addEventListener('close',()=>{connection('Verbindung unterbrochen · neuer Versuch','is-offline');retryTimer=setTimeout(connect,1800)});}
async function open(){code=$('#join-code').value.trim().toUpperCase();token=$('#join-token').value.trim();const d=await api();if(!d.controller)throw new Error('Controller-Schlüssel ungültig.');state=d.state;history.replaceState(null,'',`?code=${code}#token=${token}`);$('#join-view').hidden=true;$('#controller-view').hidden=false;connect();render();}
function render(){if(!state)return;$('#level-label').textContent='AKTUELLE BLINDS';$('#blinds').textContent=`${state.currentBlinds.sb} / ${state.currentBlinds.bb}`;$('#round-label').textContent=`Runde ${Math.min(state.round,state.roundsPerLevel)} von ${state.roundsPerLevel} · Hand ${state.hand}`;renderTable($('#table'),state,player=>playerMenu(player));$('#share-code').textContent=code;$('#display-link').href=`./display/?code=${code}`;$('#next-hand').disabled=busy||state.status!=='running';$('#pause').disabled=busy||state.status==='finished'||state.status==='level-change';$('#pause').textContent=state.status==='paused'?'Weiter':'Pause';$('#next-level').hidden=state.status!=='level-change';$('#next-level').disabled=busy;$('#finish-session').disabled=busy||state.status==='finished';$('#undo').disabled=busy||!state.canUndo;$('#undo').title=state.undoLabel||'Keine Aktion zum Rückgängigmachen';renderHistory();const colorUps=state.colorUpsDue||[];$('#status-banner').innerHTML=state.status==='finished'?'<div class="live-status"><strong>Pokerabend beendet.</strong> Der letzte Stand bleibt auf Controller und Display sichtbar.</div>':state.status==='level-change'?(colorUps.length?`<div class="live-status colorup-status"><strong>Color-up: ${colorUps.join(' / ')}er-Chips raus.</strong> Chips jetzt wechseln, danach die neuen Blinds starten.</div>`:'<div class="live-status"><strong>Blindstufe abgeschlossen.</strong> Neue Blinds bewusst starten.</div>'):state.status==='paused'?'<div class="live-status"><strong>Pause</strong> · Spielstand bleibt erhalten.</div>':'';renderOverlay($('#overlay'),state.overlay==='rules'?'rules':null);bindOverlayClose();$('#ranks').checked=state.overlay==='ranks';$('#view-table').classList.toggle('is-active',(state.displayMode||'table')==='table');$('#view-broadcast').classList.toggle('is-active',state.displayMode==='broadcast');$('#view-minimal').classList.toggle('is-active',state.displayMode==='minimal');}
async function action(name,body={}){if(busy)return;busy=true;render();try{const d=await api(name,body);state=d.state;}catch(e){alert(e.message)}finally{busy=false;render();}}
function playerMenu(p){if(state.status==='finished')return;if(state.pendingEliminations.includes(p.id)){if(confirm(`${p.name}: Ausscheiden nach dieser Hand zurücknehmen?`))action('cancel-elimination',{playerId:p.id});return}if(confirm(`${p.name} scheidet nach der aktuellen Hand aus?`))action('eliminate',{playerId:p.id});}
function bindOverlayClose(){const b=$('#overlay [data-close]');if(b)b.onclick=()=>action('overlay',{overlay:null});}
function renderHistory(){const log=state.eventLog||[];$('#event-log').innerHTML=log.length?log.slice(0,20).map(e=>`<div class="controller-event"><time>${new Date(e.at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</time><strong>${escapeHtml(e.label)}</strong></div>`).join(''):'<p class="helper-copy">Noch keine Aktionen.</p>';}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nextActiveSeatFrom(seat){const total=state.players.length;for(let i=1;i<=total;i++){const candidate=((Number(seat)-1+i)%total)+1;const player=state.players.find(p=>p.seat===candidate);if(player?.status==='active')return candidate;}return null;}
function correctPositions(){if(state.status==='finished')return;const seats=state.players.map(p=>`${p.seat}=${p.name}${p.status==='out'?' (raus)':''}`).join('\n');const dRaw=prompt(`Dealer-Sitz eingeben:\n${seats}`,String(state.buttonSeat));if(dRaw===null)return;const d=Number(dRaw);if(!Number.isInteger(d)||d<1||d>state.players.length){alert('Bitte eine gültige Dealer-Sitznummer eingeben.');return;}const active=state.players.filter(p=>p.status==='active');let suggestedSb,suggestedBb;if(active.length===2){suggestedSb=d;suggestedBb=nextActiveSeatFrom(d);}else{suggestedSb=nextActiveSeatFrom(d);suggestedBb=nextActiveSeatFrom(suggestedSb);}const sbRaw=prompt(`Small-Blind-Sitz eingeben. 0 = kein Small Blind.\nVorschlag passend zu Dealer Sitz ${d}:`,String(suggestedSb??0));if(sbRaw===null)return;const sb=Number(sbRaw);const bbDefault=sb===0?nextActiveSeatFrom(d):nextActiveSeatFrom(sb);const bbRaw=prompt('Big-Blind-Sitz eingeben:',String(bbDefault??suggestedBb??state.bigBlindSeat));if(bbRaw===null)return;const bb=Number(bbRaw);if(confirm(`Positionen wirklich setzen?\nD Sitz ${d} · SB ${sb===0?'–':`Sitz ${sb}`} · BB Sitz ${bb}`))action('correct-roles',{buttonSeat:d,smallBlindSeat:sb===0?null:sb,bigBlindSeat:bb});}
$('#join-code').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)});$('#join-button').onclick=()=>open().catch(e=>alert(e.message));$('#next-hand').onclick=()=>action('next-hand');$('#pause').onclick=()=>action('pause');$('#next-level').onclick=()=>action('next-level');$('#undo').onclick=()=>{if(state.canUndo&&confirm(`Letzte Aktion rückgängig machen?\n${state.undoLabel||''}`))action('undo')};$('#history').onclick=()=>{$('#controller-log').hidden=false;$('#controller-log').scrollIntoView({behavior:'smooth',block:'nearest'})};$('#close-history').onclick=()=>{$('#controller-log').hidden=true};$('#correct').onclick=correctPositions;$('#finish-session').onclick=()=>{if(confirm('Pokerabend wirklich beenden?\n\nDer aktuelle Stand bleibt sichtbar. Mit Rückgängig kann der Abschluss korrigiert werden.'))action('finish')};$('#ranks').onchange=e=>action('overlay',{overlay:e.target.checked?'ranks':null});$('#rules').onclick=()=>action('overlay',{overlay:state?.overlay==='rules'?null:'rules'});$('#view-table').onclick=()=>action('display-mode',{mode:'table'});$('#view-broadcast').onclick=()=>action('display-mode',{mode:'broadcast'});$('#view-minimal').onclick=()=>action('display-mode',{mode:'minimal'});$('#players').onclick=()=>alert('Spieler direkt am Tisch antippen. Eine gelb markierte Ausscheidens-Markierung kann dort auch wieder zurückgenommen werden.');credentials();if(code&&token)open().catch(()=>{});
