export const rankNames=['Royal Flush','Straight Flush','Vierling','Full House','Flush','Straße','Drilling','Zwei Paare','Ein Paar','Höchste Karte'];
export function renderTable(el,s,onPlayer){el.querySelectorAll('.live-seat').forEach(n=>n.remove());const n=s.players.length;for(const p of s.players){const angle=-Math.PI/2+(p.seat-1)*2*Math.PI/n;const x=50+47*Math.cos(angle),y=50+43*Math.sin(angle);const node=document.createElement(onPlayer?'button':'div');node.className=`live-seat ${p.status==='out'?'is-out':''} ${s.pendingEliminations.includes(p.id)?'is-pending':''}`;node.style.left=`${x}%`;node.style.top=`${y}%`;const badges=[];if(s.buttonSeat===p.seat)badges.push(`<span class="role-badge ${p.status==='out'?'dead':''}">D</span>`);if(s.smallBlindSeat===p.seat)badges.push('<span class="role-badge">SB</span>');if(s.bigBlindSeat===p.seat)badges.push('<span class="role-badge">BB</span>');node.innerHTML=`<div class="seat-name">${escapeHtml(p.name)}</div><div class="seat-badges">${badges.join('')}</div>${p.status==='out'?'<small>ausgeschieden</small>':s.pendingEliminations.includes(p.id)?'<small>nach Hand raus</small>':''}`;if(onPlayer&&p.status==='active')node.addEventListener('click',()=>onPlayer(p));el.append(node);}el.querySelector('.table-center').innerHTML=s.buttonSeat&&!s.players.some(p=>p.seat===s.buttonSeat&&p.status==='active')?'<strong>Dead Button</strong><br>Dealer-Markierung liegt an leerem Sitz.':'';}
const rankExamples=[
  [['A','♠'],['K','♠'],['Q','♠'],['J','♠'],['10','♠']],
  [['9','♥'],['8','♥'],['7','♥'],['6','♥'],['5','♥']],
  [['K','♠'],['K','♥'],['K','♦'],['K','♣'],['4','♠']],
  [['Q','♠'],['Q','♥'],['Q','♦'],['8','♣'],['8','♥']],
  [['A','♦'],['J','♦'],['8','♦'],['5','♦'],['2','♦']],
  [['9','♠'],['8','♥'],['7','♦'],['6','♣'],['5','♠']],
  [['J','♠'],['J','♥'],['J','♦'],['7','♣'],['3','♠']],
  [['10','♠'],['10','♥'],['4','♦'],['4','♣'],['A','♠']],
  [['A','♠'],['A','♥'],['9','♦'],['6','♣'],['3','♠']],
  [['A','♠'],['J','♥'],['8','♦'],['5','♣'],['2','♠']]
];
function rankCards(i){return rankExamples[i].map(([r,s])=>`<span class="rank-card ${s==='♥'||s==='♦'?'red':''}">${r}${s}</span>`).join('')}
export function renderOverlay(el,type){
  if(!type){el.hidden=true;el.classList.remove('ranks-panel');return}
  el.hidden=false;el.classList.toggle('ranks-panel',type==='ranks');
  if(type==='ranks')el.innerHTML=`<button class="picker-close" data-close>×</button><p class="eyebrow">HANDRANGFOLGE</p><h2>Welche Hand schlägt welche?</h2><div class="rank-compact">${rankNames.map((x,i)=>`<div><strong>${i+1}</strong><span class="rank-name">${x}</span><span class="rank-cards">${rankCards(i)}</span></div>`).join('')}</div>`;
  else el.innerHTML=`<button class="picker-close" data-close>×</button><p class="eyebrow">REGELHILFE</p><h2>Button & besondere Situationen</h2><div class="rule-help"><h3>Dead Button</h3><p>Im Turnier wird nach Poker TDA mit Dead Button gespielt. Maßgeblich ist, wer als Nächstes den Big Blind schuldet; Small Blind und Button werden daraus rückwärts bestimmt. Dadurch kann der Button an einem leeren Sitz liegen oder derselbe Spieler in zwei aufeinanderfolgenden Händen die letzte Aktion nach dem Flop haben.</p><p><strong>Beispiel: Der nächste Big Blind scheidet aus.</strong> Dieser Sitz wird übersprungen und der Big Blind geht an den nächsten aktiven Spieler. Small Blind und Button werden passend dazu gesetzt.</p><p><strong>Beispiel: Der aktuelle Big Blind scheidet aus.</strong> Der nächste aktive Spieler links davon wird Big Blind. Dadurch kann der bisherige Dealer in der nächsten Hand erneut die Dealer-Position behalten – das ist beim Dead-Button-Verfahren beabsichtigt.</p><p>Poker TDA 2026 schreibt den Dead Button in Regel 34 vor; Regel 36 beschreibt Platzierung und Bewegung des Buttons.</p><h3>Heads-up</h3><p>Bei zwei Spielern ist der Button zugleich Small Blind. Er handelt preflop zuerst und nach dem Flop zuletzt. Beim Übergang kann die Position angepasst werden, damit niemand zweimal nacheinander Big Blind ist (Regel 36-C).</p><h3>Neues Blindlevel</h3><p>Neue Limits gelten ab der nächsten Hand. Eine bereits begonnene Hand bleibt grundsätzlich im bisherigen Level.</p><p><a href="https://www.pokertda.com/view-poker-tda-rules/" target="_blank" rel="noreferrer noopener">Poker TDA 2026 · Regeln 25, 34 und 36 ↗</a></p></div>`;
}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
